# netlify.toml
[build]
  command = "hugo --gc --minify" # Comando de build do Hugo
  publish = "docs"             # Pasta onde o Hugo gera o site
  functions = "netlify/functions"  # Onde o Netlify encontra as suas funções
