[build]
  command = "hugo mod get -u && hugo --gc --minify"  # Atualiza módulos antes do build
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  HUGO_VERSION = "0.125.4"  # Versão mais recente (24/06/2024)
  NODE_VERSION = "18"