[build]
  command = "hugo --gc --minify"
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  HUGO_VERSION = "0.125.4"
  NODE_VERSION = "18"
  GO_VERSION = "1.21"
  WC_POST_CSS = "true"