[build]
  command = "hugo --gc --minify"
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  HUGO_VERSION = "0.125.4"  # Versão EXTENDED (obrigatória para temas modernos)
  NODE_VERSION = "18"
  GO_VERSION = "1.21"        # Necessário para módulos Go do Hugo

[context.production.environment]
  HUGO_ENV = "production"