# netlify.toml
[build]
  command = "hugo --gc --minify" # Comando para construir o seu site Hugo
  publish = "public"             # Pasta onde o Hugo gera o site construído
  functions = "netlify/functions"  # Onde o Netlify encontra as suas funções

[dev] # Configurações para desenvolvimento local com Netlify Dev (opcional)
  command = "hugo server -D"
  port = 1313
  publish = "public"
  targetPort = 1313
  framework = "#hugo"
  functions = "netlify/functions"
  autoLaunch = false
