"""
update_readme_stats.py — keep README.md's headline counts in sync with the data.

Reads the metadata in data/crimenet.json (node/edge/profiled/unprofiled/defunct
counts) plus the number of source articles, and rewrites the one stats sentence
in README.md that lives between the markers:

    <!-- crimenet-stats:start ... -->
    ...the sentence...
    <!-- crimenet-stats:end -->

Idempotent: it only writes if the numbers actually changed, so re-running (or a
pipeline that runs it every build) won't churn the file. 7_apply_corrections.py
calls this automatically after it writes the final crimenet.json,
so the README tracks the data without anyone remembering to update it.

Usage:
    python tools/update_readme_stats.py
    python tools/update_readme_stats.py --crimenet data/crimenet.json --readme README.md
"""

import argparse
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
START = "<!-- crimenet-stats:start"
END = "<!-- crimenet-stats:end -->"
BLOCK_RE = re.compile(re.escape(START) + r".*?" + re.escape(END), re.DOTALL)


def count_articles(txts_dir, articles_csv):
    """Number of source articles: subdirectories of data/txts (fall back to the
    data rows of articles.csv)."""
    txts_dir, articles_csv = Path(txts_dir), Path(articles_csv)
    if txts_dir.is_dir():
        n = sum(1 for p in txts_dir.iterdir() if p.is_dir())
        if n:
            return n
    if articles_csv.exists():
        rows = articles_csv.read_text("utf-8").splitlines()
        return max(0, len(rows) - 1)   # minus the header
    return 0


def stats_from(crimenet_path):
    """(nodes, edges, profiled, mentions, defunct) from crimenet.json — prefer
    its metadata block, else recompute from the nodes."""
    data = json.loads(Path(crimenet_path).read_text("utf-8"))
    meta = data.get("metadata") or {}
    nodes = data.get("nodes", [])
    n_nodes = meta.get("n_nodes", len(nodes))
    n_edges = meta.get("n_edges", len(data.get("edges", [])))
    n_prof = meta.get("n_profiled", sum(1 for n in nodes if n.get("profiled")))
    n_unprof = meta.get("n_unprofiled", n_nodes - n_prof)
    n_defunct = meta.get("n_defunct", sum(1 for n in nodes if n.get("is_defunct") is True))
    return n_nodes, n_edges, n_prof, n_unprof, n_defunct


def connectivity_from(crimenet_path):
    """(connected, isolated) node counts from crimenet.json: how many
    organizations have at least one extracted relationship vs none."""
    data = json.loads(Path(crimenet_path).read_text("utf-8"))
    nodes = data.get("nodes", [])
    linked = set()
    for e in data.get("edges", []):
        if e.get("source"):
            linked.add(e["source"])
        if e.get("target"):
            linked.add(e["target"])
    connected = sum(1 for n in nodes if n.get("standard_name") in linked)
    return connected, len(nodes) - connected


def build_block(nodes, edges, profiled, mentions, defunct, articles,
                connected, isolated):
    pct_conn = round(100 * connected / nodes) if nodes else 0
    pct_iso = 100 - pct_conn
    sentence = (
        f"The current build holds **{nodes:,} organizations** and "
        f"**{edges:,} relationships** ({profiled:,} organizations are profiled "
        f"from their own article; {mentions:,} are kept as mentions; "
        f"{defunct:,} are flagged defunct), extracted from {articles:,} Wikipedia "
        f"articles across four languages."
    )
    connectivity = (
        f" Of these organizations, **{connected:,} ({pct_conn}%)** are connected "
        f"to at least one other and **{isolated:,} ({pct_iso}%)** are isolated, "
        f"with no relationship extracted. An isolated organization reflects the "
        f"absence of a documented tie in the Wikipedia articles processed, not "
        f"necessarily the absence of any real-world connection."
    )
    return (f"{START} — auto-generated by tools/update_readme_stats.py; "
            f"do not edit by hand -->\n{sentence}{connectivity}\n{END}")


def build_about_block(nodes, edges, articles):
    """The stat-card block for app/about.html (same markers as the README)."""
    return (f"{START} — auto-generated by tools/update_readme_stats.py; "
            f"do not edit by hand -->\n"
            f'  <div class="stat all"><b>{nodes:,}</b><span>Organizations</span></div>\n'
            f'  <div class="stat"><b>{edges:,}</b><span>Relationships</span></div>\n'
            f'  <div class="stat"><b>{articles:,}</b><span>Wikipedia Articles</span></div>\n'
            f"  {END}")


def sync_marker_file(path, block, label, quiet):
    """Replace the crimenet-stats marker block in `path` with `block`.
    Best-effort: a missing file or missing markers is not an error."""
    path = Path(path)
    if not path.exists():
        return
    text = path.read_text("utf-8")
    if not BLOCK_RE.search(text):
        if not quiet:
            print(f"update_readme_stats: no markers in {path.name} — skipped.")
        return
    new_text = BLOCK_RE.sub(lambda _: block, text, count=1)
    if new_text != text:
        path.write_text(new_text, "utf-8")
        if not quiet:
            print(f"update_readme_stats: updated {label} ({path.name}).")


def main():
    ap = argparse.ArgumentParser(description="Sync README.md headline counts with data/crimenet.json.")
    ap.add_argument("--crimenet", default=str(REPO_ROOT / "data" / "crimenet.json"))
    ap.add_argument("--readme", default=str(REPO_ROOT / "README.md"))
    ap.add_argument("--about", default=str(REPO_ROOT / "app" / "about.html"),
                    help="app/about.html to sync too (best-effort; skipped if absent)")
    ap.add_argument("--txts", default=str(REPO_ROOT / "data" / "txts"))
    ap.add_argument("--articles-csv", default=str(REPO_ROOT / "data" / "articles.csv"))
    ap.add_argument("--quiet", action="store_true")
    args = ap.parse_args()

    cpath, rpath = Path(args.crimenet), Path(args.readme)
    if not cpath.exists() or not rpath.exists():
        if not args.quiet:
            print(f"update_readme_stats: skipped (missing {cpath if not cpath.exists() else rpath})")
        return 0

    nodes, edges, profiled, mentions, defunct = stats_from(cpath)
    connected, isolated = connectivity_from(cpath)
    articles = count_articles(args.txts, args.articles_csv)
    block = build_block(nodes, edges, profiled, mentions, defunct, articles,
                        connected, isolated)

    # Keep app/about.html's stat cards in sync too (best-effort).
    sync_marker_file(args.about, build_about_block(nodes, edges, articles),
                     "about page", args.quiet)

    text = rpath.read_text("utf-8")
    if BLOCK_RE.search(text):
        new_text = BLOCK_RE.sub(lambda _: block, text, count=1)
    else:
        if not args.quiet:
            print(f"update_readme_stats: no {START} … {END} markers in {rpath.name} — "
                  "add them around the stats sentence; leaving file unchanged.")
        return 0

    if new_text == text:
        if not args.quiet:
            print(f"update_readme_stats: already up to date "
                  f"({nodes:,} nodes / {edges:,} edges).")
        return 0

    rpath.write_text(new_text, "utf-8")
    if not args.quiet:
        print(f"update_readme_stats: updated {rpath.name} → {nodes:,} orgs, "
              f"{edges:,} relationships ({profiled:,} profiled / {mentions:,} mentions "
              f"/ {defunct:,} defunct), {articles:,} articles.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
