# 5_non_criminal_orgs.py
# Auto-generated by 5_review_non_criminal_orgs.py — DeepSeek judged every
# node; below are the ones it judged to be NON-CRIMINAL entities (state
# armed forces, national police, mainstream political parties, religious /
# civil bodies), NOT criminal or armed organizations.
#
# REVIEW, then paste the good entries into curated_corrections.py TO_BE_EXCLUDED.
# 7_apply_corrections.py auto-applies the confident ones and drops those nodes
# and every edge touching them (it unions this set with 4_umbrella_orgs.py).
#
# 5568 node(s) judged | 311 non-criminal (high/medium), 0 low-confidence | 5257 criminal org(s), 0 error(s)
#
# Cost: 5,568 API call(s) | 5,831,406 prompt + 329,649 completion tokens | ~$1.94 (at $0.27/M in + $1.1/M out)

TO_BE_EXCLUDED = {
    "Muslim Brotherhood",  # (high) [Islamist political and social organization] The Muslim Brotherhood is a transnational Islamist organization that engages in political activism and charity, not primarily a criminal or armed group.
    #     desc:  "Transnational Sunni Islamist organization founded in Egypt in 1928 by Hassan al-Banna. Combines political activism with …"
    #     deg:   63
    #     src:   https://en.wikipedia.org/w/index.php?title=Muslim_Brotherhood&oldid=1359583929

    "Organised crime in the Netherlands",  # (high) [general concept] It is a broad description of organized crime in a country, not a specific criminal organization.
    #     desc:  "Organised crime in the Netherlands, known as penose, refers to criminal organizations primarily of Dutch descent, with r…"
    #     deg:   15
    #     src:   https://en.wikipedia.org/w/index.php?title=Organised_crime_in_the_Netherlands&oldid=1354688558

    "Young Lords",  # (high) [political organization] The Young Lords were a far-left political organization, not a criminal or armed group, despite originating from a street gang.
    #     desc:  "The Young Lords were a far-left political organization that evolved from a Chicago street gang founded in 1959. Known fo…"
    #     deg:   14
    #     src:   https://en.wikipedia.org/w/index.php?title=Young_Lords&oldid=1344677583

    "Tatmadaw",  # (high) [national armed forces] The Tatmadaw is the official armed forces of Myanmar, a sovereign state's regular military.
    #     deg:   12
    #     src:   https://en.wikipedia.org/w/index.php?title=Myanmar_conflict&oldid=1350747295 | https://en.wikipedia.org/w/index.php?title=United_Wa_State_Army&oldid=1359014938

    "Fatah",  # (high) [political party] Fatah is a major Palestinian political party and former national liberation movement, not a criminal organization.
    #     deg:   10
    #     src:   https://en.wikipedia.org/w/index.php?title=Doghmush_clan&oldid=1345106664 | https://en.wikipedia.org/w/index.php?title=Hamas&oldid=1359500467 | https://en.wikipedia.org/w/index.php?title=Kurdistan_Workers%27_Party&oldid=1359472353 | https://en.wikipedia.org/w/index.php?title=Muslim_Brotherhood&oldid=1359583929 | https://en.wikipedia.org/w/index.php?title=Popular_Front_for_the_Liberation_of_Palestine&oldid=1358047725

    "Muttahida Qaumi Movement – London",  # (high) [political party] It is described as a secular political party, not an armed or criminal group.
    #     desc:  "A Muhajir nationalist and secular political party in Pakistan, founded by Altaf Hussain in 1984. It was the London-based…"
    #     deg:   10
    #     src:   https://en.wikipedia.org/w/index.php?title=Muttahida_Qaumi_Movement_%E2%80%93_London&oldid=1356364452

    "Stasi",  # (high) [secret police / state security agency] The Stasi was the official state security and secret police service of East Germany, a government agency, not a non-state criminal or armed group.
    #     deg:   9
    #     src:   https://en.wikipedia.org/w/index.php?title=Death_squad&oldid=1359525393

    "Los Angeles County Sheriff's Department",  # (high) [county sheriff's department] It is a government law enforcement agency, not a criminal organization.
    #     deg:   8
    #     src:   https://en.wikipedia.org/w/index.php?title=Lynwood_Vikings&oldid=1341169433

    "Palestine Liberation Organization",  # (high) [political coalition] The PLO is a recognized political coalition representing the Palestinian people, not a criminal or armed group.
    #     deg:   7
    #     src:   https://en.wikipedia.org/w/index.php?title=Hamas&oldid=1359500467 | https://en.wikipedia.org/w/index.php?title=Muslim_Brotherhood&oldid=1359583929 | https://en.wikipedia.org/w/index.php?title=Popular_Front_for_the_Liberation_of_Palestine&oldid=1358047725 | https://en.wikipedia.org/w/index.php?title=Provisional_Irish_Republican_Army&oldid=1359436308 | https://en.wikipedia.org/w/index.php?title=Red_Brigades&oldid=1357317958

    "Suey Sing Association",  # (high) [Chinese American community association] The description identifies it as a historical Chinese American association, not a criminal or armed group.
    #     desc:  "The Suey Sing Association is a historical Chinese American association established in 1867. Formerly known as the Suey S…"
    #     deg:   6
    #     src:   https://en.wikipedia.org/w/index.php?title=Suey_Sing_Association&oldid=1299041372

    "Alliance for Peace and Freedom",  # (high) [European political party] The passage describes it as a far-right and ultranationalist European political party, not a criminal or armed group.
    #     deg:   5
    #     src:   https://en.wikipedia.org/w/index.php?title=Noua_Dreapt%C4%83&oldid=1358270527

    "Batasuna",  # (high) [political party] Batasuna was a political party, not a criminal or armed group, though it was banned for ties to ETA.
    #     deg:   5
    #     src:   https://en.wikipedia.org/w/index.php?title=ETA_%28separatist_group%29&oldid=1358157538

    "Chinese Communist Party",  # (high) [political party] The Chinese Communist Party is the ruling political party of China, a legitimate state body, not a criminal or armed organization.
    #     deg:   5
    #     src:   https://en.wikipedia.org/w/index.php?title=Khmer_Rouge&oldid=1359110483

    "Hongmen",  # (high) [fraternal organization] Hongmen is historically a secret society but is now a secular fraternal organization, not primarily a criminal or armed group.
    #     desc:  "The Hongmen, formerly Tiandihui, is a Chinese fraternal organization and historically a secretive folk religious sect. F…"
    #     deg:   5
    #     src:   https://en.wikipedia.org/w/index.php?title=Hongmen&oldid=1359019068

    "Iran",  # (high) [sovereign state] Iran is a sovereign state, not a criminal or armed organization.
    #     deg:   5
    #     src:   https://en.wikipedia.org/w/index.php?title=Foxtrot_%28criminal_network%29&oldid=1337345535 | https://en.wikipedia.org/w/index.php?title=Funding_of_Hezbollah&oldid=1357172438 | https://en.wikipedia.org/w/index.php?title=Hamas&oldid=1359500467

    "Arab Nationalist Movement",  # (high) [political movement] The Arab Nationalist Movement is a political movement founded by George Habash, not a criminal or armed group.
    #     deg:   4
    #     src:   https://en.wikipedia.org/w/index.php?title=Popular_Front_for_the_Liberation_of_Palestine&oldid=1358047725

    "Drug Enforcement Administration",  # (high) [federal law enforcement agency] The Drug Enforcement Administration is a U.S. federal police agency, not a criminal or armed group.
    #     deg:   4
    #     src:   https://en.wikipedia.org/w/index.php?title=Revolutionary_Armed_Forces_of_Colombia&oldid=1357250189

    "Neo Black Movement of Africa",  # (high) [student confraternity / social movement] It is a university-based confraternity focused on Pan-Africanism and social justice, not a criminal or armed group.
    #     desc:  "The Neo Black Movement of Africa is an international confraternity founded in 1977 at the University of Benin in Nigeria…"
    #     deg:   4
    #     src:   https://en.wikipedia.org/w/index.php?title=Neo_Black_Movement_of_Africa&oldid=1359541679

    "Students for a Democratic Society",  # (high) [student activist organization] SDS was a national student activist organization, not a criminal or armed group; it is mentioned as the parent organization of the Weather Underground.
    #     deg:   4
    #     src:   https://en.wikipedia.org/w/index.php?title=Weather_Underground&oldid=1358913480 | https://en.wikipedia.org/w/index.php?title=Young_Lords&oldid=1344677583

    "Tammany Hall",  # (high) [political machine] Tammany Hall was a Democratic Party political machine in New York City, not a criminal organization itself.
    #     deg:   4
    #     src:   https://en.wikipedia.org/w/index.php?title=Bowery_Boys_%28gang%29&oldid=1345302951 | https://en.wikipedia.org/w/index.php?title=Chichesters&oldid=1339077208 | https://en.wikipedia.org/w/index.php?title=Five_Points_Gang&oldid=1353456215 | https://en.wikipedia.org/w/index.php?title=Forty_Thieves_%28New_York_gang%29&oldid=1358093557

    "Ba'athist Syria",  # (high) [state regime] Ba'athist Syria refers to the Syrian state under the Ba'athist government, a sovereign state, not a criminal or armed group.
    #     deg:   3
    #     src:   https://en.wikipedia.org/w/index.php?title=Funding_of_Hezbollah&oldid=1357172438

    "Colombian National Army",  # (high) [national army] The Colombian National Army is the regular military force of a sovereign state, not a criminal organization.
    #     deg:   3
    #     src:   https://en.wikipedia.org/w/index.php?title=Right-wing_paramilitarism_in_Colombia&oldid=1352768019

    "Ghee Kung Tong",  # (medium) [fraternal association] Described as a fraternal association in San Francisco, sometimes referred to as Chinese Freemasons, not a criminal organization.
    #     deg:   3
    #     src:   https://en.wikipedia.org/w/index.php?title=Raymond_%22Shrimp_Boy%22_Chow&oldid=1355459523

    "Islamic State of Afghanistan",  # (high) [former recognized government] The Islamic State of Afghanistan was the internationally recognized government of Afghanistan from 1992 to 1996, a legitimate state body.
    #     deg:   3
    #     src:   https://en.wikipedia.org/w/index.php?title=Taliban&oldid=1359460136

    "Libyan National Army",  # (high) [national army] The Libyan National Army is a state military force led by Field Marshal Khalifa Haftar, not a criminal or non-state armed group.
    #     deg:   3
    #     src:   https://en.wikipedia.org/w/index.php?title=Rapid_Support_Forces&oldid=1359312523 | https://en.wikipedia.org/w/index.php?title=Wagner_Group&oldid=1357099556

    "National Unity Government",  # (high) [civilian government in exile] The National Unity Government is a political body formed in opposition to the Myanmar junta, not a criminal or armed organization.
    #     deg:   3
    #     src:   https://en.wikipedia.org/w/index.php?title=Myanmar_conflict&oldid=1350747295

    "North Korea",  # (high) [sovereign state] North Korea is a sovereign state, not a criminal or armed organization.
    #     deg:   3
    #     src:   https://en.wikipedia.org/w/index.php?title=Hamas&oldid=1359500467 | https://en.wikipedia.org/w/index.php?title=Houthis&oldid=1358892022

    "People's Army of Vietnam",  # (high) [national army] The People's Army of Vietnam is the regular armed forces of a sovereign state, not a criminal organization.
    #     deg:   3
    #     src:   https://en.wikipedia.org/w/index.php?title=Khmer_Rouge&oldid=1359110483

    "Quds Force",  # (high) [Iranian military unit] Quds Force is a branch of Iran's Islamic Revolutionary Guard Corps, a state military entity, not a criminal organization.
    #     deg:   3
    #     src:   https://en.wikipedia.org/w/index.php?title=Hezbollah&oldid=1359125680 | https://en.wikipedia.org/w/index.php?title=Popular_Mobilization_Forces&oldid=1359397172

    "Russia",  # (high) [sovereign state] Russia is a sovereign state, not a criminal or armed organization.
    #     deg:   3
    #     src:   https://en.wikipedia.org/w/index.php?title=Houthis&oldid=1358892022

    "Sudanese Armed Forces",  # (high) [national army] The Sudanese Armed Forces (SAF) is the regular military of the sovereign state of Sudan, not a criminal or non-state armed group.
    #     deg:   3
    #     src:   https://en.wikipedia.org/w/index.php?title=Rapid_Support_Forces&oldid=1359312523

    "All Pakistan Muhajir Student Organization",  # (high) [student organization] It is a student organization that later evolved into a political party, not a criminal or armed group.
    #     deg:   2
    #     src:   https://en.wikipedia.org/w/index.php?title=Muttahida_Qaumi_Movement_%E2%80%93_London&oldid=1356364452

    "Angkatan Belia Islam Malaysia",  # (high) [youth movement] It is a Muslim youth movement in Malaysia, not a criminal or armed group.
    #     deg:   2
    #     src:   https://en.wikipedia.org/w/index.php?title=Muslim_Brotherhood&oldid=1359583929

    "Armed Forces of the Democratic Republic of the Congo",  # (high) [national military] The Armed Forces of the Democratic Republic of the Congo (FARDC) is the regular national military of a sovereign state, not a criminal or non-state armed group.
    #     deg:   2
    #     src:   https://en.wikipedia.org/w/index.php?title=March_23_Movement&oldid=1359617087

    "China",  # (high) [sovereign state] China is a sovereign country, not a criminal or armed organization.
    #     deg:   2
    #     src:   https://en.wikipedia.org/w/index.php?title=Houthis&oldid=1358892022

    "Elohim City",  # (high) [religious community] Elohim City is described as a private community of Christian Identity followers, not a criminal or armed organization.
    #     deg:   2
    #     src:   https://en.wikipedia.org/w/index.php?title=Aryan_Republican_Army&oldid=1357438725 | https://en.wikipedia.org/w/index.php?title=The_Covenant%2C_the_Sword%2C_and_the_Arm_of_the_Lord&oldid=1359245068

    "Esperanza, Paz y Libertad",  # (high) [political party] It is a political party formed by demobilized guerrillas, not an active criminal or armed group.
    #     deg:   2
    #     src:   https://en.wikipedia.org/w/index.php?title=Popular_Liberation_Army&oldid=1344078114

    "Federation of Islamic Organizations in Europe",  # (high) [religious umbrella organization] It is a pan-European umbrella organization of the Muslim Brotherhood, described as a religious/civil body, not a criminal or armed group.
    #     deg:   2
    #     src:   https://en.wikipedia.org/w/index.php?title=Muslim_Brotherhood&oldid=1359583929

    "FSB",  # (high) [national security service] FSB is Russia's Federal Security Service, a state intelligence and security agency, not a criminal organization.
    #     deg:   2
    #     src:   https://en.wikipedia.org/w/index.php?title=Kadyrovites&oldid=1357490420 | https://en.wikipedia.org/w/index.php?title=Wagner_Group&oldid=1357099556

    "Haitian Tèt Kale Party",  # (high) [political party] The name 'Haitian Tèt Kale Party' indicates it is a political party, and the passages show it is listed as an ally/rival of gangs, not itself a criminal group.
    #     deg:   2
    #     src:   https://en.wikipedia.org/w/index.php?title=400_Mawozo&oldid=1350731995 | https://en.wikipedia.org/w/index.php?title=Revolutionary_Forces_of_the_G9_Family_and_Allies&oldid=1358676887

    "Imperial Japanese Army",  # (high) [national army] The Imperial Japanese Army was the regular army of the Empire of Japan, a sovereign state, not a criminal or non-state armed group.
    #     deg:   2
    #     src:   https://en.wikipedia.org/w/index.php?title=Honghuzi&oldid=1330761088

    "Inter-Services Intelligence",  # (high) [national intelligence agency] Inter-Services Intelligence (ISI) is Pakistan's state intelligence agency, not a criminal or armed group.
    #     deg:   2
    #     src:   https://en.wikipedia.org/w/index.php?title=D-Company&oldid=1357374297

    "Islamic Community of Germany",  # (high) [religious community organization] It is described as a constituent organization of the Muslim Brotherhood, but it is a registered civil society association (e.V.) in Germany, not an armed or criminal group.
    #     deg:   2
    #     src:   https://en.wikipedia.org/w/index.php?title=Muslim_Brotherhood&oldid=1359583929

    "Justice and Construction Party",  # (high) [political party] The passage describes it as a political party formed by the Muslim Brotherhood to contest elections, not a criminal or armed group.
    #     deg:   2
    #     src:   https://en.wikipedia.org/w/index.php?title=Muslim_Brotherhood&oldid=1359583929

    "Kosovo Protection Corps",  # (high) [civilian emergency protection body] The passage describes it as a civilian emergency protection body that replaced the KLA, not a criminal or armed group.
    #     deg:   2
    #     src:   https://en.wikipedia.org/w/index.php?title=Kosovo_Liberation_Army&oldid=1358109367

    "Kuomintang",  # (high) [political party] Kuomintang is a major political party in Taiwan, historically the ruling party of the Republic of China, not a criminal organization.
    #     deg:   2
    #     src:   https://en.wikipedia.org/w/index.php?title=Green_Gang&oldid=1352003460 | https://en.wikipedia.org/w/index.php?title=Hip_Sing_Association&oldid=1334949434

    "Kurdistan Democratic Party",  # (high) [political party] The Kurdistan Democratic Party (KDP) is a mainstream political party in Iraqi Kurdistan, not a criminal or armed group.
    #     deg:   2
    #     src:   https://en.wikipedia.org/w/index.php?title=Kurdistan_Workers%27_Party&oldid=1359472353

    "Malaysian Islamic Party",  # (high) [mainstream Islamist political party] PAS is a mainstream political party in Malaysia that contests elections, not a criminal or armed group.
    #     deg:   2
    #     src:   https://en.wikipedia.org/w/index.php?title=Muslim_Brotherhood&oldid=1359583929

    "March 8 Alliance",  # (high) [political alliance] The March 8 Alliance is a political coalition in Lebanon, not a criminal or armed group.
    #     deg:   2
    #     src:   https://en.wikipedia.org/w/index.php?title=Hezbollah&oldid=1359125680

    "Milli Muslim League",  # (high) [political party] The passage explicitly describes the Milli Muslim League as a political party, not a criminal or armed group.
    #     deg:   2
    #     src:   https://en.wikipedia.org/w/index.php?title=Lashkar-e-Taiba&oldid=1359412852

    "Movimiento Esperanza, Paz y Libertad",  # (high) [political party] It was formed after the demobilization of a guerrilla group and participated in the 1991 Constituent Assembly, indicating it is a legitimate political party.
    #     deg:   2
    #     src:   https://es.wikipedia.org/w/index.php?title=Ej%C3%A9rcito_Popular_de_Liberaci%C3%B3n_%28Colombia%29&oldid=173268556

    "Muslim Association of Britain",  # (high) [religious/civil organization] The Muslim Association of Britain is described as a publicly visible organization established by the Muslim Brotherhood, focused on political activism and community dialogue, not as a criminal or armed group.
    #     deg:   2
    #     src:   https://en.wikipedia.org/w/index.php?title=Muslim_Brotherhood&oldid=1359583929

    "Nation of Islam",  # (high) [religious movement] The Nation of Islam is a religious and political organization, not a criminal or armed group.
    #     deg:   2
    #     src:   https://en.wikipedia.org/w/index.php?title=Aryan_Nations&oldid=1357123292 | https://en.wikipedia.org/w/index.php?title=Black_Mafia&oldid=1350792611 | https://en.wikipedia.org/w/index.php?title=Black_Spades&oldid=1359315351

    "National Islamic Front",  # (high) [political party] The passages describe the National Islamic Front as a political group and an offshoot of the Muslim Brotherhood that participated in elections and sought to Islamize society, not as a criminal or armed organization.
    #     deg:   2
    #     src:   https://en.wikipedia.org/w/index.php?title=Al-Qaeda&oldid=1358123339 | https://en.wikipedia.org/w/index.php?title=Muslim_Brotherhood&oldid=1359583929

    "National Islamic Unity Party",  # (high) [political party] The passage describes it as a Shia political party formed by a politician, not an armed or criminal group.
    #     deg:   2
    #     src:   https://en.wikipedia.org/w/index.php?title=Taliban&oldid=1359460136

    "Partido Socialista Puertorriqueño",  # (high) [political party] The passage describes it as a socialist political party, not a criminal or armed group.
    #     deg:   2
    #     src:   https://en.wikipedia.org/w/index.php?title=Young_Lords&oldid=1344677583

    "Patriotic Union",  # (high) [political party] The passage describes it as a political party formed by leftist groups including FARC, not an armed group itself.
    #     deg:   2
    #     src:   https://en.wikipedia.org/w/index.php?title=Revolutionary_Armed_Forces_of_Colombia&oldid=1357250189

    "Peshmerga",  # (high) [regional military force] Peshmerga are the official military forces of the Kurdistan Region, a legitimate regional government entity.
    #     deg:   2
    #     src:   https://en.wikipedia.org/w/index.php?title=Islamic_State&oldid=1359049369 | https://en.wikipedia.org/w/index.php?title=Popular_Mobilization_Forces&oldid=1359397172

    "Presidential Anti-Crime Commission",  # (high) [government anti-crime commission] It is a government commission, not a criminal organization.
    #     deg:   2
    #     src:   https://en.wikipedia.org/w/index.php?title=Kuratong_Baleleng&oldid=1347343020

    "Security Information Agency",  # (high) [state intelligence agency] The BIA is the Serbian state security service, a legitimate government agency, not a criminal organization.
    #     deg:   2
    #     src:   https://en.wikipedia.org/w/index.php?title=Zemun_Clan&oldid=1350364888

    "SS",  # (high) [paramilitary/police organization] The SS (Schutzstaffel) was a major paramilitary organization under Adolf Hitler and the Nazi Party, not a criminal organization in the sense of organized crime.
    #     deg:   2
    #     src:   https://en.wikipedia.org/w/index.php?title=Quebec_Biker_War&oldid=1358024089 | https://en.wikipedia.org/w/index.php?title=Rock_Machine_Motorcycle_Club&oldid=1351288223

    "UNBR Botomei",  # (high) [fake lawyers' association] The passages describe UNBR Botomei as a group of fake lawyers, not a criminal or armed organization.
    #     deg:   2
    #     src:   https://en.wikipedia.org/w/index.php?title=Romanian_Constitutional_Bar&oldid=1338577214

    "Volunteers",  # (medium) [local militia/volunteer force] The passage describes volunteers fighting alongside Spanish and Puerto Rican soldiers in the Spanish-American War, indicating a non-criminal military auxiliary.
    #     deg:   2
    #     src:   https://en.wikipedia.org/w/index.php?title=Boricua_Popular_Army&oldid=1358779721

    "AEK",  # (high) [Basque-language academy league] AEK is described as a league of Basque-language academies, a civil educational body, not a criminal organization.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=ETA_%28separatist_group%29&oldid=1358157538

    "Al Eslah",  # (high) [charity arm of Muslim Brotherhood] The passage describes Al Eslah as the charity arm of the Muslim Brotherhood in Kuwait, a religious/social organization, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Muslim_Brotherhood&oldid=1359583929

    "Al Menbar",  # (high) [political party] Al Menbar is described as a political party in Bahrain that won seats in parliamentary elections.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Muslim_Brotherhood&oldid=1359583929

    "Al-Ahed",  # (high) [media outlet (newspaper)] Al-Ahed is described as a weekly newspaper and online platform affiliated with Hezbollah, not a criminal or armed group itself.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Hezbollah&oldid=1359125680

    "Al-Islah",  # (high) [political party] Al-Islah is a Yemeni political party, not a criminal or armed group, as indicated by its listing among non-state opponents alongside other political entities.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Houthis&oldid=1358892022

    "Al-Islah (UAE)",  # (high) [Islamist political group] Al-Islah is a Muslim Brotherhood-affiliated political group in the UAE, not a criminal or armed organization.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Muslim_Brotherhood&oldid=1359583929

    "Al-Manar",  # (high) [satellite TV station] Al-Manar is a media outlet (satellite TV station) operated by Hezbollah, but it is not itself a criminal or armed organization.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Hezbollah&oldid=1359125680

    "Alkarama",  # (high) [non-governmental organization (NGO)] Alkarama is described as a Swiss-based NGO founded by a human-rights activist, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Al-Qaeda&oldid=1358123339

    "All-Japanese Conference of Patriotic Associations",  # (high) [right-wing umbrella organization] It is an umbrella group of right-wing and yakuza groups, but itself is a political advocacy organization, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Yoshio_Kodama&oldid=1336096693

    "American Muslim Council",  # (high) [Islamic advocacy organization] The American Muslim Council is described as an Islamic organization founded by Muslim Brotherhood activists, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Muslim_Brotherhood&oldid=1359583929

    "Amnistiaren Aldeko Komiteak",  # (high) [prisoner support movement] The passage describes it as a 'prisoner support movement', which is a civil advocacy group, not a criminal or armed organization.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=ETA_%28separatist_group%29&oldid=1358157538

    "Anti-Defamation League",  # (high) [civil rights organization] The ADL is a Jewish civil rights organization that opposed the Klan, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Ku_Klux_Klan&oldid=1359551836

    "Armed Forces of the Philippines",  # (high) [national military] The Armed Forces of the Philippines is the regular military of a sovereign state, not a criminal organization.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Kuratong_Baleleng&oldid=1347343020

    "Armed Forces of Ukraine",  # (high) [national military] The Armed Forces of Ukraine are the regular state military of a sovereign nation, not a criminal or non-state armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Wagner_Group&oldid=1357099556

    "ATİB – Union of Turkish-Islamic Cultural Associations in Europe",  # (high) [cultural association] The passages describe it as a cultural association with members, not as a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Grey_Wolves_%28organization%29&oldid=1357379852

    "Auxiliary Division",  # (high) [auxiliary police unit] The Auxiliary Division was a paramilitary police unit of the Royal Irish Constabulary, a state police force, not a criminal organization.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Death_squad&oldid=1359525393

    "Azerbaijan National Democrat Party",  # (high) [political party] The entry is a registered political party in Azerbaijan, as indicated by its registration with the Justice Ministry.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Grey_Wolves_%28organization%29&oldid=1357379852

    "Basque Nationalist Party",  # (high) [political party] The Basque Nationalist Party is a mainstream political party that contests elections, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=ETA_%28separatist_group%29&oldid=1358157538

    "Believing Youth",  # (high) [religious revival movement] The passages describe it as a moderate theological movement promoting Zaydi revival through school clubs and summer camps, not as a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Houthis&oldid=1358892022

    "Belçika Türk Federasyonu",  # (medium) [cultural federation] The BTF is described as a Turkish cultural federation aiming to foster loyalty to Turkish identity, not as a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Grey_Wolves_%28organization%29&oldid=1357379852

    "Benevolence International Foundation",  # (medium) [charitable foundation] The name suggests a charitable foundation, and the passage mentions it in the context of seized documents, not as a criminal group itself.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Al-Qaeda&oldid=1358123339

    "Bloque de Búsqueda",  # (high) [government special police unit] The passage describes the Bloque de Búsqueda as a unit of the Colombian government, working alongside intelligence agencies like DAS and US authorities like DEA, not a criminal organization.
    #     deg:   1
    #     src:   https://es.wikipedia.org/w/index.php?title=Los_Pepes&oldid=172096852

    "Botanical Youth Club",  # (high) [youth club / civil organization] The passage describes it as a youth club that originally formed to prevent the spread of Communist guerrillas, not as a criminal or armed group itself.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Kuratong_Baleleng&oldid=1347343020

    "British National Front",  # (high) [political party] The British National Front is a far-right political party in the UK, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=American_Front&oldid=1317253639

    "British National Party",  # (high) [political party] The British National Party is a far-right political party that contests elections, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Combat_18&oldid=1359357984

    "British Subjects' Mutual Protection Society",  # (high) [political advocacy group] It was a renamed chapter of the Ku Klux Klan that advocated for British annexation of Fiji, not a criminal or armed organization.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Ku_Klux_Klan&oldid=1359551836

    "Bureau 121",  # (high) [state cyberwarfare unit] Bureau 121 is a North Korean state cyberwarfare unit, part of the government's intelligence apparatus, not a criminal organization.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Lazarus_Group&oldid=1356174462

    "Cao Đài",  # (high) [religious sect] Cao Đài is a syncretic religious movement in Vietnam, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=B%C3%ACnh_Xuy%C3%AAn&oldid=1357674353

    "Carboneria",  # (high) [secret society] Carboneria was a 19th-century Italian secret society advocating for unification, not a criminal or armed group.
    #     deg:   1
    #     src:   https://it.wikipedia.org/w/index.php?title=Mafia_in_Italia&oldid=150962377

    "Cell 16",  # (high) [radical feminist group] Cell 16 is described as a 'radical women's liberation group' involved in recruitment, not a criminal or armed organization.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Weather_Underground&oldid=1358913480

    "CENTRAL",  # (high) [neighbourhood] The passage refers to 'Central' as a neighbourhood in Winnipeg, not a criminal organization.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Manitoba_Warriors&oldid=1358603972

    "Cercle Marxiste",  # (high) [secret Marxist study group] It is a secret ideological cell within a student association, not an armed or criminal group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Khmer_Rouge&oldid=1359110483

    "Charlottetown Harley Club",  # (medium) [motorcycle club (non-criminal)] Mentioned alongside other motorcycle clubs in a context about patches and relationships, with no indication of criminal activity.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Bacchus_Motorcycle_Club&oldid=1351073911

    "CIA",  # (high) [national intelligence agency] The CIA is a U.S. government intelligence agency, not a criminal or armed group.
    #     deg:   1
    #     src:   https://es.wikipedia.org/w/index.php?title=Los_Pepes&oldid=172096852

    "Coalition Government of Democratic Kampuchea",  # (high) [government in exile] It was a UN-recognized coalition government, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Khmer_Rouge&oldid=1359110483

    "Communist Party of Colombia",  # (high) [political party] The Communist Party of Colombia is a mainstream political party, not an armed group, as indicated by its mention alongside FARC as a separate entity.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Revolutionary_Armed_Forces_of_Colombia&oldid=1357250189

    "Communist Party of Colombia (Marxist–Leninist)",  # (high) [political party] It is a Marxist–Leninist political party that created a guerrilla group (EPL), but the party itself is a political organization, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Popular_Liberation_Army&oldid=1344078114

    "Communist Party of Thailand",  # (high) [political party] The Communist Party of Thailand is a political party, not a criminal or armed group, as indicated by its mention as an ally in a political context.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Khmer_Rouge&oldid=1359110483

    "Community of Sant'Egidio",  # (high) [Catholic organization] The passage describes it as a Catholic organisation that mediated peace talks, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=ETA_%28separatist_group%29&oldid=1358157538

    "COR",  # (high) [military unit] The passage describes COR as a unit involved in the Puerto Rican Campaign, indicating it is a military unit, not a criminal organization.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Boricua_Popular_Army&oldid=1358779721

    "Council on American–Islamic Relations",  # (high) [non-profit civil rights organization] The passage describes CAIR as a non-profit group, not a criminal or armed organization.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Muslim_Brotherhood&oldid=1359583929

    "Counter-Guerrilla",  # (high) [Turkish branch of NATO Operation Gladio (state-linked paramilitary)] The passage identifies Counter-Guerrilla as the Turkish branch of NATO's Operation Gladio, a state-sponsored stay-behind network, not a criminal organization.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Grey_Wolves_%28organization%29&oldid=1357379852

    "Democratic Autonomous Administration of North and East Syria",  # (high) [autonomous administration] It is a political and administrative entity, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Syrian_Democratic_Forces&oldid=1357129335

    "Democratic League of Kosovo",  # (high) [political party] The Democratic League of Kosovo is described as a peaceful political party that established a parallel state and pursued independence through non-violent means.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Kosovo_Liberation_Army&oldid=1358109367

    "Democrazia Cristiana",  # (high) [political party] Democrazia Cristiana is a mainstream Italian political party, not a criminal organization.
    #     deg:   1
    #     src:   https://it.wikipedia.org/w/index.php?title=Clan_dei_Casamonica&oldid=150463758

    "Detroit Federation of Motorcycle Clubs",  # (high) [motorcycle club federation] It is a federation created to resolve turf wars among motorcycle clubs, not itself a criminal organization.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Highwaymen_Motorcycle_Club&oldid=1351127102

    "Eight-Nation Alliance",  # (high) [military alliance of states] The Eight-Nation Alliance was a coalition of eight sovereign states (Austria-Hungary, France, Germany, Italy, Japan, Russia, the United Kingdom, and the United States) formed to suppress the Boxer Rebellion, not a criminal or non-state armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Honghuzi&oldid=1330761088

    "Emanuele",  # (high) [individual person] The passage refers to 'Emanuele Quattrone' as a person killed in a feud, not a criminal organization.
    #     deg:   1
    #     src:   https://it.wikipedia.org/w/index.php?title=%27Ndrangheta&oldid=151142432

    "Ennahda Movement",  # (high) [political party] The passage describes Ennahda Movement as a national organization sponsored by the Muslim Brotherhood in Tunisia, indicating it is a political party, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Muslim_Brotherhood&oldid=1359583929

    "European National Front",  # (high) [far-right political umbrella group] The European National Front is described as an umbrella group of far-right nationalist organizations, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Noua_Dreapt%C4%83&oldid=1358270527

    "Euskadiko Ezkerra",  # (high) [political party] The passage describes it as a political party that former ETA members integrated into.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=ETA_%28separatist_group%29&oldid=1358157538

    "FACA",  # (high) [national armed forces] FACA stands for Central African Armed Forces, the regular military of the Central African Republic, a sovereign state.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Wagner_Group&oldid=1357099556

    "FADM",  # (high) [national military] FADM is the Mozambique Defense Armed Forces, the regular state military of Mozambique.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Wagner_Group&oldid=1357099556

    "FAMa",  # (high) [national armed forces] FAMa is the Malian Armed Forces, a sovereign state's regular military, not a criminal organization.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Wagner_Group&oldid=1357099556

    "Fasci Siciliani",  # (high) [trade union movement] The passage describes Fasci Siciliani as a trade union movement, not a criminal organization.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Corleone_Mafia_family&oldid=1353000382

    "Fatah Alliance",  # (high) [political alliance] The Fatah Alliance is a political coalition representing the Popular Mobilization Forces, not a criminal or armed group itself.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Popular_Mobilization_Forces&oldid=1359397172

    "Federated Ship Painters and Dockers Union",  # (high) [trade union] The Federated Ship Painters and Dockers Union is a legitimate trade union, not a criminal organization, though it was allied with criminal groups.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Moran_family&oldid=1358416737

    "Forza Nuova",  # (high) [far-right political party] Listed among far-right nationalist organizations and described as a political party, not an armed or criminal group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Noua_Dreapt%C4%83&oldid=1358270527

    "Fourth Armoured Division",  # (high) [military division] The Fourth Armoured Division is a regular military unit of the Syrian Arab Army, a state armed force, not a criminal organization.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Illegal_drug_trade_in_Syria&oldid=1310135781

    "Free Legal Assistance Group",  # (high) [human rights law firm] The passage describes FLAG as a human rights law firm serving as prosecutor, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Kuratong_Baleleng&oldid=1347343020

    "Free Officers Movement",  # (high) [nationalist military officers' group] The Free Officers Movement was a group of Egyptian nationalist military officers that overthrew the monarchy, not a criminal or armed non-state group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Muslim_Brotherhood&oldid=1359583929

    "Free Patriotic Movement",  # (high) [political party] The Free Patriotic Movement is a Lebanese political party that contests elections and is not an armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Hezbollah&oldid=1359125680

    "Freedom and Justice Party",  # (high) [political party] The Freedom and Justice Party is a political party launched by the Muslim Brotherhood that contested and won elections in Egypt.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Muslim_Brotherhood&oldid=1359583929

    "French Communist Party",  # (high) [political party] The French Communist Party is a mainstream political party that contests elections, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Khmer_Rouge&oldid=1359110483

    "Fuerza Armada Nacional Bolivariana",  # (high) [national military] Fuerza Armada Nacional Bolivariana is the official name of Venezuela's national armed forces, a legitimate state military.
    #     deg:   1
    #     src:   https://es.wikipedia.org/w/index.php?title=C%C3%A1rtel_de_los_Soles&oldid=173742819

    "FUNCINPEC",  # (high) [political party] FUNCINPEC is a royalist political party in Cambodia, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Khmer_Rouge&oldid=1359110483

    "Funcinpec Party",  # (high) [political party] Funcinpec Party is a royalist political party in Cambodia, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Khmer_Rouge&oldid=1359110483

    "Future Movement",  # (high) [political party] The passage describes Future Movement as a political party with militiamen, but it is primarily a political party in Lebanon, not a criminal organization.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Hezbollah&oldid=1359125680

    "General Association of Korean Residents in Japan",  # (high) [civic organization] The passage describes it as a North Korea-associated civic group, not a criminal or armed organization.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Toa-kai&oldid=1352110359

    "General People's Congress",  # (high) [political party] The General People's Congress is a Yemeni political party, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Houthis&oldid=1358892022

    "Gerace",  # (high) [town or district] The passage refers to 'distretto di Gerace' as a geographical area, not a criminal organization.
    #     deg:   1
    #     src:   https://it.wikipedia.org/w/index.php?title=%27Ndrangheta&oldid=151142432

    "Gerindo",  # (high) [political movement] Gerindo is described as a nationalist political movement (Indonesian People's Movement), not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Preman_%28Indonesian_gangster%29&oldid=1345366816

    "German American Bund",  # (high) [pro-Nazi political organization] The German American Bund was a pro-Nazi political organization, not a criminal or armed group, as described in the passages.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Abner_Zwillman&oldid=1355230671 | https://en.wikipedia.org/w/index.php?title=Organized_crime&oldid=1359392344

    "Giugliano",  # (high) [town or locality] The passage refers to 'area di Giugliano' as a location where a criminal clan operated, not a criminal organization itself.
    #     deg:   1
    #     src:   https://it.wikipedia.org/w/index.php?title=Camorra&oldid=151000464

    "Goretz",  # (high) [FSB spetsnaz unit] The passage describes it as a spetsnaz unit of the FSB, a Russian state security service, not a criminal organization.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Kadyrovites&oldid=1357490420

    "Grand Alliance for Safeguarding Hong Kong",  # (medium) [pro-Beijing political group] It is a radical pro-Beijing group that organized a rally, not a criminal or armed organization.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Fujianese_organized_crime&oldid=1359356124

    "Great Union Party",  # (high) [political party] The Great Union Party (BBP) is described as a political party that split from MHP, with Islamist leanings, and is not itself an armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Grey_Wolves_%28organization%29&oldid=1357379852

    "GRU",  # (high) [Russian military intelligence agency] GRU is the Main Intelligence Directorate of the Russian military, a state intelligence agency, not a criminal organization.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Wagner_Group&oldid=1357099556

    "GRUNK",  # (high) [royal government in exile] GRUNK is the French acronym for the Royal Government of National Union of Kampuchea, a government in exile formed by Norodom Sihanouk, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Khmer_Rouge&oldid=1359110483

    "Health Revolutionary Unity Movement",  # (high) [health activist group] The passage describes HRUM as a community health advocacy group collaborating on hospital reform, not a criminal or armed organization.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Young_Lords&oldid=1344677583

    "Herriko Tabernak",  # (high) [network of taverns/meeting centres] Herriko Tabernak are described as 'people's taverns' acting as meeting centres, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=ETA_%28separatist_group%29&oldid=1358157538

    "Hòa Hảo",  # (high) [religious sect] Hòa Hảo is a Vietnamese religious sect, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=B%C3%ACnh_Xuy%C3%AAn&oldid=1357674353

    "Independent Union of Romanian Jurists",  # (high) [trade union] The passage describes it as a union of jurists, a civil organization, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Romanian_Constitutional_Bar&oldid=1338577214

    "Indochinese Communist Party",  # (high) [communist party] The Indochinese Communist Party was a political party, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Khmer_Rouge&oldid=1359110483

    "Indonesian Communist Party",  # (high) [political party] The Indonesian Communist Party (PKI) is a mainstream political party that contested elections and is not itself an armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Preman_%28Indonesian_gangster%29&oldid=1345366816

    "Inkatha Freedom Party",  # (high) [political party] Inkatha Freedom Party is a mainstream political party in South Africa that contests elections, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Khumalo_gang&oldid=1344343179

    "International Brotherhood of Teamsters",  # (high) [labor union] The International Brotherhood of Teamsters is a legitimate labor union, not a criminal organization, though it was infiltrated by organized crime.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Cleveland_crime_family&oldid=1359474318

    "International Institute of Islamic Thought",  # (high) [think tank / research institute] The International Institute of Islamic Thought is a scholarly research institute, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Muslim_Brotherhood&oldid=1359583929

    "International Islamic Relief Organization",  # (high) [charitable organization] The IIRO is a charity, not a criminal or armed group, though it was exploited by al-Qaeda for funding.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Al-Qaeda&oldid=1358123339

    "International Longshore and Warehouse Union",  # (high) [labor union] The ILWU is a legitimate labor union, not a criminal organization, though it may have been infiltrated by criminals.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Hells_Angels_MC_criminal_allegations_and_incidents_in_British_Columbia&oldid=1327107209

    "Iranian Call and Reform Organization",  # (high) [Sunni Islamist political group] Described as a Sunni Islamist group active in Iran, affiliated with the Muslim Brotherhood, which is a political movement, not a criminal or armed organization.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Muslim_Brotherhood&oldid=1359583929

    "Iranian secret service",  # (high) [state intelligence agency] The Iranian secret service is a government intelligence agency, not a criminal or armed non-state group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Moroccan_mafia&oldid=1358369254

    "Iraqi Islamic Party",  # (high) [political party] It is described as the Iraqi branch of the Muslim Brotherhood, a political party that participated in elections and is not primarily an armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Muslim_Brotherhood&oldid=1359583929

    "Islami Jamhoori Ittehad",  # (high) [political alliance] The passage describes IJI as a political alliance that formed a federal government, indicating it is a legitimate political entity.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Muttahida_Qaumi_Movement_%E2%80%93_London&oldid=1356364452

    "Islamic Action Front",  # (high) [political party] The Islamic Action Front is the political party of the Jordanian Muslim Brotherhood, a mainstream political party that contests elections.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Muslim_Brotherhood&oldid=1359583929

    "Islamic Constitutional Movement",  # (high) [political party] The passage describes ICM as a political arm of the Muslim Brotherhood in Kuwait, with members elected to parliament and serving in government, not as a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Muslim_Brotherhood&oldid=1359583929

    "Islamic Republic of Afghanistan",  # (high) [sovereign state] The Islamic Republic of Afghanistan was the internationally recognized government of Afghanistan, a sovereign state, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Taliban&oldid=1359460136

    "Islamic Society of Britain",  # (high) [religious/civil society organization] The Islamic Society of Britain is described as a publicly visible organization established by the Muslim Brotherhood, but it is a civil society group, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Muslim_Brotherhood&oldid=1359583929

    "Islamic Society of North America",  # (high) [religious/civil organization] ISNA is described as a Muslim Brotherhood entity in the U.S., but it is a non-profit religious and civil organization, not an armed or criminal group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Muslim_Brotherhood&oldid=1359583929

    "Islamic Unity Party",  # (high) [political party] The passage describes it as a Shia political party in Afghanistan, not an armed or criminal group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Taliban&oldid=1359460136

    "Italian Communist Party",  # (high) [political party] The Italian Communist Party is a mainstream political party that contested elections and is not an armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Red_Brigades&oldid=1357317958

    "Jama'at-e-Islami",  # (high) [Islamist political party] Jama'at-e-Islami is a mainstream Islamist political party in South Asia, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Muslim_Brotherhood&oldid=1359583929

    "Jamaica Labour Party",  # (high) [political party] The Jamaica Labour Party is a mainstream political party that contests elections, not a criminal organization.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Shower_Posse&oldid=1329338693

    "Jordanian Popular Democratic Unity Party",  # (high) [political party] The passage explicitly states it is a separate political party formed from the Jordan branch of the PFLP.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Popular_Front_for_the_Liberation_of_Palestine&oldid=1358047725

    "Justice and Charity Party",  # (high) [political party] The passage describes it as a national organization sponsored by the Muslim Brotherhood, a political movement, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Muslim_Brotherhood&oldid=1359583929

    "Justice and Development Party (Morocco)",  # (high) [political party] The Justice and Development Party is a mainstream political party that contested elections and held the office of Prime Minister in Morocco.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Muslim_Brotherhood&oldid=1359583929

    "Justice and Development Party (Turkey)",  # (high) [political party] The Justice and Development Party (AKP) is a mainstream political party in Turkey that contests elections, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Muslim_Brotherhood&oldid=1359583929

    "Kampuchean People's Revolutionary Party",  # (high) [political party] The Kampuchean People's Revolutionary Party is a communist political party, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Khmer_Rouge&oldid=1359110483

    "Khmer Students Association",  # (high) [student association] The Khmer Students Association is a student organization for Khmer students in Paris, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Khmer_Rouge&oldid=1359110483

    "Khmer Students Union",  # (high) [student union] The Khmer Students Union is a student organization, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Khmer_Rouge&oldid=1359110483

    "Knights of Columbus",  # (high) [Catholic fraternal organization] The Knights of Columbus is a Catholic fraternal service organization, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Ku_Klux_Klan&oldid=1359551836

    "Kotleba – People's Party Our Slovakia",  # (high) [political party] The passage describes it as a far-right European political party, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Noua_Dreapt%C4%83&oldid=1358270527

    "Kurdistan Islamic Union",  # (high) [political party] The passage describes it as a small political party holding seats in the Kurdish parliament, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Muslim_Brotherhood&oldid=1359583929

    "Latin American Defense Organization",  # (high) [civil rights advocacy organization] The passage describes LADO as an advocacy organization calling for structural change, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Young_Lords&oldid=1344677583

    "Libyan Arab Jamahiriya",  # (high) [sovereign state (Libyan Arab Jamahiriya was the official name of Libya under Gaddafi)] It is a state, not a criminal organization; mentioned as an ally in a gang article but itself is a country.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Almighty_Black_P._Stone_Nation&oldid=1358390136

    "Libyan Army",  # (high) [national army] The Libyan Army is the regular state military force of Libya, not a criminal or non-state armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Wagner_Group&oldid=1357099556

    "Lotta Continua",  # (high) [far-left political group] The passage describes Lotta Continua as a far-left group opposed to the Red Brigades, not as a criminal or armed organization.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Red_Brigades&oldid=1357317958

    "March 14 Alliance",  # (high) [political alliance] The March 14 Alliance is a political coalition in Lebanon, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Hezbollah&oldid=1359125680

    "MONUSCO",  # (high) [UN peacekeeping mission] MONUSCO is the United Nations Organization Stabilization Mission in the Democratic Republic of the Congo, a legitimate international peacekeeping force.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=March_23_Movement&oldid=1359617087

    "Motor City Nine",  # (high) [women's liberation group] The passage describes it as a women's group involved in recruitment efforts, not a criminal or armed organization.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Weather_Underground&oldid=1358913480

    "Mountain Church of Jesus Christ the Savior",  # (high) [religious organization] The passage describes it as a church founded by a right-wing leader, not as a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=The_Covenant%2C_the_Sword%2C_and_the_Arm_of_the_Lord&oldid=1359245068

    "Movement Pro Independence",  # (high) [political movement] The passage describes it as a nationalist group led by Juan Mari Brás, a political figure, and it is not depicted as a criminal or armed organization.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Young_Lords&oldid=1344677583

    "Movimento Sociale Italiano",  # (high) [political party] The passage describes MSI as an Italian neo-fascist party, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Red_Brigades&oldid=1357317958

    "MPLA",  # (high) [political party / former rebel movement] MPLA is a major political party in Angola, originally a liberation movement, now a legitimate governing party.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Death_squad&oldid=1359525393

    "MQM-Haqiqi",  # (high) [political party faction] The passage describes MQM-Haqiqi as a faction of a political party, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Muttahida_Qaumi_Movement_%E2%80%93_London&oldid=1356364452

    "MQM-Pakistan",  # (high) [political party] MQM-Pakistan is a faction of the Muttahida Qaumi Movement, a mainstream political party in Pakistan that contests elections.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Muttahida_Qaumi_Movement_%E2%80%93_London&oldid=1356364452

    "Muhajir Qaumi Movement",  # (high) [political party] The passage describes it as a nationalist and secular socio-liberalist political party in Pakistan, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Muttahida_Qaumi_Movement_%E2%80%93_London&oldid=1356364452

    "Muslim American Society",  # (high) [religious/civil organization] The passage describes it as an organization started by Muslim Brotherhood supporters, but it is a civil society group, not an armed or criminal group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Muslim_Brotherhood&oldid=1359583929

    "Muslim Council of Britain",  # (high) [religious/civil organization] The Muslim Council of Britain is a UK-based umbrella organization for Muslim communities, engaging in dialogue with the government, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Muslim_Brotherhood&oldid=1359583929

    "Muslim Students Association",  # (high) [student religious association] The Muslim Students Association is a campus religious organization, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Muslim_Brotherhood&oldid=1359583929

    "Muslim World League",  # (high) [religious charity] The Muslim World League is a charitable organization, not a criminal or armed group, though it was exploited by al-Qaeda for funding.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Al-Qaeda&oldid=1358123339

    "Muttahida Qaumi Movement",  # (high) [political party] MQM is a mainstream political party in Pakistan that contests elections, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=People%27s_Aman_Committee&oldid=1351570103

    "Muttahida Qaumi Movement – Haqiqi",  # (high) [political party faction] The passage describes it as a faction of a political party in Pakistan, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Muttahida_Qaumi_Movement_%E2%80%93_London&oldid=1356364452

    "Muttahida Qaumi Movement – Pakistan",  # (high) [political party] The passage describes it as a political party founded by Altaf Hussain, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Muttahida_Qaumi_Movement_%E2%80%93_London&oldid=1356364452

    "National Association for the Advancement of Colored People",  # (high) [civil rights organization] The NAACP is a well-known civil rights organization, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Ku_Klux_Klan&oldid=1359551836

    "National Association of Seadogs",  # (high) [student fraternity] The passage describes it as a university group similar to the Neo-Black Movement, which is a fraternity, not a criminal organization.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Neo_Black_Movement_of_Africa&oldid=1359541679

    "National Democracy",  # (high) [political party] The passage lists National Democracy as a member of the Alliance for Peace and Freedom, a European political party, indicating it is a political party, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Noua_Dreapt%C4%83&oldid=1358270527

    "National Democratic Party of Germany",  # (high) [political party] It is a far-right political party in Germany, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Noua_Dreapt%C4%83&oldid=1358270527

    "National Guard",  # (high) [national military/police force] The passage refers to the former National Guard of Nicaragua, a state military force, not a criminal organization.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Contras&oldid=1359478486

    "National Police of Colombia",  # (high) [national police force] The National Police of Colombia is a legitimate state law enforcement agency, not a criminal organization.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Los_Pepes&oldid=1328262979

    "National Popular Alliance",  # (high) [political party] The National Popular Alliance (ANAPO) was a left-wing populist political party in Colombia, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=19th_of_April_Movement&oldid=1356541922

    "National Rally for Reform and Development",  # (high) [political party] The passage describes it as a legalized political party associated with the Muslim Brotherhood, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Muslim_Brotherhood&oldid=1359583929

    "National Union of Romanian Bars",  # (high) [professional association of lawyers] The National Union of Romanian Bars is a professional association for lawyers, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Romanian_Constitutional_Bar&oldid=1338577214

    "Nationalist Movement Party",  # (high) [political party] The Nationalist Movement Party (MHP) is a mainstream Turkish political party that contests elections, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Grey_Wolves_%28organization%29&oldid=1357379852

    "NATO",  # (high) [international military alliance] NATO is a legitimate intergovernmental military alliance of sovereign states, not a criminal or non-state armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Kosovo_Liberation_Army&oldid=1358109367

    "Nicaraguan Democratic Union",  # (high) [political opposition group] The passage describes it as an opposition group of Nicaraguan exiles, not a criminal or armed organization.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Contras&oldid=1359478486

    "North American Islamic Trust",  # (high) [religious trust / non-profit] The passage identifies it as a Muslim Brotherhood entity in the U.S., but it is described as a trust, not an armed or criminal group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Muslim_Brotherhood&oldid=1359583929

    "Office of Policy Coordination",  # (high) [U.S. government intelligence agency] The Office of Policy Coordination (OPC) was a CIA covert action unit, not a criminal organization.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Hip_Sing_Association&oldid=1334949434

    "Pakistan Peoples Party",  # (high) [political party] The passage describes PPP as a political party that won seats in a general election and formed a coalition government.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Muttahida_Qaumi_Movement_%E2%80%93_London&oldid=1356364452

    "Palestinian People's Party",  # (high) [political party] The passage describes it as a leftist group formed within the Palestinian Authority, indicating it is a political party, not a criminal or armed organization.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Popular_Front_for_the_Liberation_of_Palestine&oldid=1358047725

    "Pembela Tanah Air",  # (high) [Japanese-sponsored militia] PETA was a Japanese-sponsored militia during WWII, not a criminal organization.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Preman_%28Indonesian_gangster%29&oldid=1345366816

    "People's Republic of Kampuchea",  # (high) [state government] The People's Republic of Kampuchea was the official name of the Cambodian state from 1979 to 1989, a legitimate government.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Khmer_Rouge&oldid=1359110483

    "Peoples' Democratic Party",  # (high) [political party] The passage describes it as a pro-Kurdish political party whose offices were attacked, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Grey_Wolves_%28organization%29&oldid=1357379852

    "Pillar of Fire Church",  # (high) [religious cult/church] The passage describes it as a small cult/church, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Ku_Klux_Klan&oldid=1359551836

    "Potere Operaio",  # (high) [far-left political group] The passage describes Potere Operaio as a far-left group opposed to the Red Brigades, not as a criminal or armed organization.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Red_Brigades&oldid=1357317958

    "Pracheachon",  # (high) [legal political party] The passage describes Pracheachon as a legal political party that participated in elections, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Khmer_Rouge&oldid=1359110483

    "Progressive Labor Party",  # (high) [political party] The Progressive Labor Party is a Marxist-Leninist political party that participated in the anti-war movement and SDS, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Weather_Underground&oldid=1358913480

    "Prosperous Justice Party",  # (high) [political party] The passage describes it as a political party that contests elections in Indonesia.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Muslim_Brotherhood&oldid=1359583929

    "Puerto Rican Socialist Party",  # (high) [political party] The Puerto Rican Socialist Party is a mainstream political party, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Ghetto_Brothers&oldid=1318584761

    "Puntland",  # (high) [regional state/autonomous region] Puntland is a semi-autonomous region of Somalia, a legitimate state entity, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Rapid_Support_Forces&oldid=1359312523

    "Qatar",  # (high) [sovereign state] Qatar is a sovereign country, not a criminal or armed organization.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Funding_of_Hezbollah&oldid=1357172438

    "Qatar Charity",  # (high) [NGO] Qatar Charity is described as the country's largest NGO, a civil organization, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Al-Qaeda&oldid=1358123339

    "Reconnaissance General Bureau",  # (high) [military intelligence agency] The passage identifies it as a North Korean military intelligence agency, a state body, not a criminal organization.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Lazarus_Group&oldid=1356174462

    "Revolutionary Committees",  # (high) [grassroots political organization] The passage describes them as nominally grass-roots organizations that helped keep the people engaged under Gaddafi's regime, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=History_of_Libya_under_Muammar_Gaddafi&oldid=1357494341

    "Russian Armed Forces",  # (high) [national military] The Russian Armed Forces are the regular state military of Russia, not a criminal or non-state armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Wagner_Group&oldid=1357099556

    "Rwandan Defence Force",  # (high) [national military] The Rwandan Defence Force is the regular national military of Rwanda, a sovereign state, not a criminal or armed non-state group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=March_23_Movement&oldid=1359617087

    "Sangkum",  # (high) [political organization] Sangkum is described as Sihanouk's political organization, a legitimate political party in Cambodia.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Khmer_Rouge&oldid=1359110483

    "Sarekat Islam",  # (high) [nationalist political organization] Sarekat Islam was a legal Indonesian nationalist movement, not a criminal or armed group, though it involved underworld elements.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Preman_%28Indonesian_gangster%29&oldid=1345366816

    "Search Bloc",  # (high) [police unit] The passage identifies Search Bloc as part of the Colombian National Police, a legitimate state law enforcement agency.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Los_Pepes&oldid=1328262979

    "Serbian State Security Directorate",  # (high) [state security agency] It is a government intelligence/security service, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Serb_Volunteer_Guard&oldid=1347823204

    "So Solid Crew",  # (high) [music group] The passage describes So Solid Crew as a music group and record label, not a criminal organization.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Tottenham_Mandem&oldid=1343929340

    "Sons of Malta",  # (high) [fraternal social club] The passage describes Sons of Malta as a fraternal social club that inspired the Klan's initiation ceremonies, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Ku_Klux_Klan&oldid=1359551836

    "Spanish People in Command",  # (high) [community organization] The passage describes it as a local organization that merged with the Young Lords to run a free breakfast program and a rent strike, indicating a civil/social activist group, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Young_Lords&oldid=1344677583

    "State of Cambodia",  # (high) [state entity] The State of Cambodia was the official name of Cambodia from 1989 to 1992, a sovereign state, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Khmer_Rouge&oldid=1359110483

    "StB",  # (high) [state security service] StB is the Czechoslovak state security service, a government intelligence agency, not a criminal organization.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Red_Brigades&oldid=1357317958

    "Street Transvestite Action Revolutionaries",  # (high) [LGBTQ activist organization] STAR is a civil rights and advocacy group for transgender and homeless youth, not a criminal or armed organization.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Young_Lords&oldid=1344677583

    "Strong Arm Squad",  # (high) [police squad] The passage describes it as a group of handpicked police officers formed by a police captain to combat gangs.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Honeymoon_Gang&oldid=1343449453

    "Syrian Arab Armed Forces",  # (high) [national military] The Syrian Arab Armed Forces are the regular state military of Syria, not a criminal or non-state armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Wagner_Group&oldid=1357099556

    "Syrian Arab Army",  # (high) [national army] The Syrian Arab Army is the regular armed forces of the Syrian state, not a criminal or non-state armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Syrian_Democratic_Forces&oldid=1357129335

    "Syrian Armed Forces",  # (high) [national military] The Syrian Armed Forces are the regular state military of Syria, not a criminal or non-state armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Ahrar_al-Sham&oldid=1351639659

    "Syrian Army",  # (high) [national army] The Syrian Army is the regular armed forces of a sovereign state, not a criminal or non-state armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Syrian_Democratic_Forces&oldid=1357129335

    "Syrian Ba'athist regime",  # (high) [state government] The Syrian Ba'athist regime is the ruling government of Syria, a sovereign state, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Hezbollah&oldid=1359125680

    "Syrian Democratic Council",  # (high) [political council] The Syrian Democratic Council is a political body established to represent various ethnic and political groups, not a criminal or armed organization.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Syrian_Democratic_Forces&oldid=1357129335

    "Syrian transitional government",  # (high) [transitional government] It is a state government body, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Syrian_Democratic_Forces&oldid=1357129335

    "Udalbiltza",  # (high) [association of municipalities] The passage describes Udalbiltza as an association of Basque municipalities, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=ETA_%28separatist_group%29&oldid=1358157538

    "UDBA",  # (high) [state intelligence service] UDBA is described as the intelligence service of Yugoslavia, a state security agency, not a criminal organization.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Red_Brigades&oldid=1357317958 | https://es.wikipedia.org/w/index.php?title=Clan_de_Zemun&oldid=154986976

    "Union des organisations islamiques en France",  # (high) [Islamic religious organization] It is a Muslim religious federation, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Muslim_Brotherhood&oldid=1359583929

    "United Malays National Organisation",  # (high) [political party] The passage describes UMNO as a mainstream political party that dominated Malaysian politics, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Muslim_Brotherhood&oldid=1359583929

    "United Motorcycle Council of NSW",  # (high) [civil council of motorcycle clubs] The United Motorcycle Council of NSW is a coalition of motorcycle clubs that convened a conference to address legislation and public image, not a criminal organization itself.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Comanchero_Motorcycle_Club&oldid=1352140687

    "United Nicaraguan Opposition",  # (high) [political coalition] The United Nicaraguan Opposition (UNO) was a political coalition of Contra groups, not a criminal organization.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Contras&oldid=1359478486

    "Universal Zulu Nation",  # (high) [hip hop awareness group] Founded by Afrika Bambaataa as a hip hop cultural organization, not a criminal gang.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Black_Spades&oldid=1359315351

    "Vak S",  # (high) [football hooligan group] Vak S is a football hooligan group associated with Feyenoord, not a criminal or armed organization.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=F-side&oldid=1348233369

    "Vietnam",  # (high) [sovereign state] Vietnam is a country, not a criminal or armed organization.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Khmer_Rouge&oldid=1359110483

    "Vietnam Workers' Party",  # (high) [political party] The Vietnam Workers' Party was a communist political party, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Khmer_Rouge&oldid=1359110483

    "White Lotus",  # (high) [religious secret society] The passage describes White Lotus as a 14th-century secret society that influenced triads, not a criminal organization itself.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Triad_%28organised_crime%29&oldid=1356267438

    "White Lotus Society",  # (high) [folk religious sect] The passage describes it as a secretive folk religious sect, not a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Hongmen&oldid=1359019068

    "Yemeni Congregation for Reform",  # (high) [political party] The passage identifies it as the political arm of the Muslim Brotherhood, a mainstream political party in Yemen.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Muslim_Brotherhood&oldid=1359583929

    "Young Patriots Organization",  # (medium) [political activist group] The passage describes it as a group participating in a peaceful occupation alongside the Black Panthers and SDS, suggesting a political/social activist organization rather than a criminal or armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Young_Lords&oldid=1344677583

    "Young Revolutionaries for Independence",  # (medium) [political activist group] The passage describes it as a precursor to the Young Lords, a Puerto Rican activist group, with no mention of criminal or armed activity.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Young_Lords&oldid=1344677583

    "Yugoslav Army",  # (high) [national army] The Yugoslav Army is the regular armed forces of a sovereign state, not a criminal or non-state armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Kosovo_Liberation_Army&oldid=1358109367

    "Yugoslav People's Army",  # (high) [national army] The Yugoslav People's Army was the regular military of the socialist Yugoslav state, not a criminal or non-state armed group.
    #     deg:   1
    #     src:   https://en.wikipedia.org/w/index.php?title=Serb_Volunteer_Guard&oldid=1347823204

    "AKP",  # (high) [political party] AKP is the ruling political party of Turkey, not a criminal or armed group.
    #     deg:   0
    #     src:   https://en.wikipedia.org/w/index.php?title=Osmanen_Germania&oldid=1329355763

    "Al-Islah (Somalia)",  # (high) [political party] Al-Islah is a Yemeni political party, the Yemeni Congregation for Reform, not a criminal or armed group.
    #     deg:   0
    #     src:   https://en.wikipedia.org/w/index.php?title=Muslim_Brotherhood&oldid=1359583929

    "BIA",  # (high) [state intelligence agency] The passages refer to BIA as the Serbian state security intelligence service (Agencia de Información de Seguridad serbia), not a criminal organization.
    #     deg:   0
    #     src:   https://es.wikipedia.org/w/index.php?title=Clan_de_Zemun&oldid=154986976

    "Bulgarian National Alliance",  # (high) [political party] Listed among political parties in a passage about Noua Dreaptă's ties, indicating it is a political group, not a criminal organization.
    #     deg:   0
    #     src:   https://en.wikipedia.org/w/index.php?title=Noua_Dreapt%C4%83&oldid=1358270527

    "C10",  # (high) [state police counter-insurgency unit] C10 was a South African Police counter-insurgency unit, a state security force, not a criminal organization.
    #     deg:   0
    #     src:   https://en.wikipedia.org/w/index.php?title=Death_squad&oldid=1359525393

    "Communist Party of Indonesia",  # (high) [political party] The Communist Party of Indonesia (PKI) was a mainstream political party that contested elections, not a criminal or armed group.
    #     deg:   0
    #     src:   https://en.wikipedia.org/w/index.php?title=Death_squad&oldid=1359525393

    "Danskernes Parti",  # (high) [political party] Listed among far-right nationalist organizations, but described as a political party, not an armed or criminal group.
    #     deg:   0
    #     src:   https://en.wikipedia.org/w/index.php?title=Noua_Dreapt%C4%83&oldid=1358270527

    "DEA",  # (high) [US federal law enforcement agency] The DEA is a US government agency, not a criminal organization.
    #     deg:   0
    #     src:   https://es.wikipedia.org/w/index.php?title=Los_Pepes&oldid=172096852

    "Dirección Federal de Seguridad",  # (high) [federal security agency] The Dirección Federal de Seguridad was a Mexican federal law enforcement and intelligence agency, a state body, not a criminal organization.
    #     deg:   0
    #     src:   https://en.wikipedia.org/w/index.php?title=Death_squad&oldid=1359525393

    "England First",  # (medium) [far-right political group] Listed among political groups with ties to a European political party, not described as a criminal or armed organization.
    #     deg:   0
    #     src:   https://en.wikipedia.org/w/index.php?title=Noua_Dreapt%C4%83&oldid=1358270527

    "Eurasian Youth Union",  # (medium) [political youth group] Listed among far-right political groups, not described as a criminal or armed organization.
    #     deg:   0
    #     src:   https://en.wikipedia.org/w/index.php?title=Noua_Dreapt%C4%83&oldid=1358270527

    "FE-La Falange",  # (high) [political party] Listed among far-right nationalist political parties, not a criminal or armed group.
    #     deg:   0
    #     src:   https://en.wikipedia.org/w/index.php?title=Noua_Dreapt%C4%83&oldid=1358270527

    "Federal Political Negotiation and Consultative Committee",  # (high) [political coalition for peace talks] The FPNCC is a coalition of ethnic armed organizations formed to participate in peace talks with the Burmese government, not a criminal or armed group itself.
    #     deg:   0
    #     src:   https://en.wikipedia.org/w/index.php?title=Three_Brotherhood_Alliance&oldid=1358168913

    "Fiamma Tricolore",  # (high) [political party] Listed among far-right political parties in Europe, not a criminal or armed group.
    #     deg:   0
    #     src:   https://en.wikipedia.org/w/index.php?title=Noua_Dreapt%C4%83&oldid=1358270527

    "Five-Percent Nation",  # (high) [religious movement] The Five-Percent Nation is a religious and cultural movement, not a criminal or armed organization.
    #     deg:   0
    #     src:   https://en.wikipedia.org/w/index.php?title=Black_Spades&oldid=1359315351

    "Fontana",  # (high) [individual person (mafia associate)] The passage refers to Giovanni Fontana as a person (compare of a mafioso), not a criminal organization.
    #     deg:   0
    #     src:   https://it.wikipedia.org/w/index.php?title=Pasquale_Condello&oldid=150918985

    "Herri Batasuna",  # (high) [political party] Herri Batasuna (also known as Batasuna) was a Basque political party, not a criminal or armed group, though it was banned for ties to ETA.
    #     deg:   0
    #     src:   https://en.wikipedia.org/w/index.php?title=ETA_%28separatist_group%29&oldid=1358157538

    "Homeland Party",  # (high) [political party] The passage describes it as a political party with a head and ties to the Muslim Brotherhood, not a criminal or armed group.
    #     deg:   0
    #     src:   https://en.wikipedia.org/w/index.php?title=Muslim_Brotherhood&oldid=1359583929

    "Ijaw Youth Council",  # (high) [civil political organization] The Ijaw Youth Council is described as a civil political organization fighting for the rights and interests of the Ijaw people, not a criminal or armed group.
    #     deg:   0
    #     src:   https://es.wikipedia.org/w/index.php?title=Conflicto_del_delta_del_N%C3%ADger&oldid=172696870

    "Iron Guard of Egypt",  # (high) [pro-palace political movement] The passage describes it as a pro-palace political movement or secret palace organization of the Kingdom of Egypt, not a criminal or armed group.
    #     deg:   0
    #     src:   https://en.wikipedia.org/w/index.php?title=Death_squad&oldid=1359525393

    "Jednota Slovenskej Mládeže",  # (medium) [political youth group] Listed among political groups tied to a far-right European political party, not a criminal or armed organization.
    #     deg:   0
    #     src:   https://en.wikipedia.org/w/index.php?title=Noua_Dreapt%C4%83&oldid=1358270527

    "KGB",  # (high) [state security agency] The KGB was the main security agency for the Soviet Union, a state intelligence and police body, not a criminal organization.
    #     deg:   0
    #     src:   https://en.wikipedia.org/w/index.php?title=Death_squad&oldid=1359525393

    "Mișcarea Național Creștină Moldova",  # (high) [political party] Listed among far-right political parties, not a criminal or armed group.
    #     deg:   0
    #     src:   https://en.wikipedia.org/w/index.php?title=Noua_Dreapt%C4%83&oldid=1358270527

    "Movement for the Survival of the Ogoni People",  # (high) [civil rights and environmental advocacy group] MOSOP is a non-violent civil society organization founded to advocate for the rights of the Ogoni people, not a criminal or armed group.
    #     deg:   0
    #     src:   https://es.wikipedia.org/w/index.php?title=Conflicto_del_delta_del_N%C3%ADger&oldid=172696870

    "Movement of Society for Peace",  # (high) [political party] The passage describes it as a political party formed by the Muslim Brotherhood in Algeria, not a criminal or armed group.
    #     deg:   0
    #     src:   https://en.wikipedia.org/w/index.php?title=Muslim_Brotherhood&oldid=1359583929

    "Nacionālā Spēka Savienība",  # (high) [far-right political group] Listed as a political group with ties to a European political party, not a criminal or armed organization.
    #     deg:   0
    #     src:   https://en.wikipedia.org/w/index.php?title=Noua_Dreapt%C4%83&oldid=1358270527

    "Nation",  # (high) [political party] The passage describes Noua Dreaptă as a far-right political party, not a criminal or armed group.
    #     deg:   0
    #     src:   https://en.wikipedia.org/w/index.php?title=Noua_Dreapt%C4%83&oldid=1358270527

    "National Foundation Society",  # (high) [right-wing nationalist group] The passage describes it as a right-wing nationalist group, not a criminal or armed organization.
    #     deg:   0
    #     src:   https://en.wikipedia.org/w/index.php?title=Yoshio_Kodama&oldid=1336096693

    "National Renovator Party",  # (high) [political party] Listed among extreme nationalist political parties, not a criminal or armed group.
    #     deg:   0
    #     src:   https://en.wikipedia.org/w/index.php?title=Noua_Dreapt%C4%83&oldid=1358270527

    "National Revival of Poland",  # (high) [political party] Listed among political parties and groups, not criminal organizations.
    #     deg:   0
    #     src:   https://en.wikipedia.org/w/index.php?title=Noua_Dreapt%C4%83&oldid=1358270527

    "Nationale Alliantie",  # (high) [political party] Listed among extreme nationalist political parties in Europe, not a criminal or armed group.
    #     deg:   0
    #     src:   https://en.wikipedia.org/w/index.php?title=Noua_Dreapt%C4%83&oldid=1358270527

    "NKVD",  # (high) [Soviet state security agency] The NKVD was the Soviet Union's secret police and intelligence agency, a legitimate state body, not a criminal organization.
    #     deg:   0
    #     src:   https://en.wikipedia.org/w/index.php?title=Death_squad&oldid=1359525393

    "North Star",  # (high) [record label and music group] The passage explicitly states that North Star was a record label and music group formed by gang members, not a criminal organization itself.
    #     deg:   0
    #     src:   https://en.wikipedia.org/w/index.php?title=Tottenham_Mandem&oldid=1343929340

    "Party of Reform and Development",  # (high) [political party] The passage describes it as a political party contesting elections and having a candidate for Prime Minister.
    #     deg:   0
    #     src:   https://en.wikipedia.org/w/index.php?title=Muslim_Brotherhood&oldid=1359583929

    "Patriotic Alliance",  # (high) [political party] Listed among extreme nationalist political parties in Europe, not described as a criminal or armed group.
    #     deg:   0
    #     src:   https://en.wikipedia.org/w/index.php?title=Noua_Dreapt%C4%83&oldid=1358270527

    "Propaganda Due",  # (high) [Freemasonic lodge] Propaganda Due (P2) is described as a Freemasonic lodge, a civil/religious body, not a criminal or armed group.
    #     deg:   0
    #     src:   https://en.wikipedia.org/w/index.php?title=Banda_della_Magliana&oldid=1350800034

    "Radical Patriotic Party",  # (high) [political party] The Radical Patriotic Party is described as a political party in the passage, not a criminal or armed group.
    #     deg:   0
    #     src:   https://en.wikipedia.org/w/index.php?title=Yoshio_Kodama&oldid=1336096693

    "Renouveau Français",  # (high) [extreme nationalist political party] Listed among political parties and described as an extreme nationalist organization, not a criminal or armed group.
    #     deg:   0
    #     src:   https://en.wikipedia.org/w/index.php?title=Noua_Dreapt%C4%83&oldid=1358270527

    "Rescue Ink",  # (high) [animal welfare organization] The passage describes Rescue Ink as an animal welfare organization where outlaw biker gang members volunteer, not a criminal group itself.
    #     deg:   0
    #     src:   https://en.wikipedia.org/w/index.php?title=Organized_crime&oldid=1359392344

    "Russkii Obraz",  # (high) [far-right political group] Listed alongside political parties and groups in a passage about far-right political alliances, not described as a criminal or armed organization.
    #     deg:   0
    #     src:   https://en.wikipedia.org/w/index.php?title=Noua_Dreapt%C4%83&oldid=1358270527

    "Slovenská Pospolitosť",  # (high) [political party] Listed among political parties in a list of far-right groups, and 'Slovenská Pospolitosť' is a known Slovak nationalist political party.
    #     deg:   0
    #     src:   https://en.wikipedia.org/w/index.php?title=Noua_Dreapt%C4%83&oldid=1358270527

    "Srpski Obraz",  # (high) [extreme nationalist political organization] Listed among political parties and movements in a column of extreme nationalist organizations, not described as a criminal or armed group.
    #     deg:   0
    #     src:   https://en.wikipedia.org/w/index.php?title=Noua_Dreapt%C4%83&oldid=1358270527

    "Suarino",  # (high) [individual person] The passage refers to Natale Suarino as a person arrested for camorra association and drug trafficking, not an organization.
    #     deg:   0
    #     src:   https://it.wikipedia.org/w/index.php?title=Clan_Ascione&oldid=150454254

    "Syria",  # (high) [sovereign state] Syria is a country, not a criminal or armed organization.
    #     deg:   0
    #     src:   https://en.wikipedia.org/w/index.php?title=Hamas&oldid=1359500467

    "Tarantino",  # (high) [geographic area] The passage uses 'tarantino' as a geographic reference to the area around Taranto, not a criminal organization.
    #     deg:   0
    #     src:   https://it.wikipedia.org/w/index.php?title=Societ%C3%A0_foggiana&oldid=150962432

    "Unión Patriótica",  # (high) [political party] The passage describes Unión Patriótica as a political party, considered an extension of a guerrilla group but not itself an armed organization.
    #     deg:   0
    #     src:   https://es.wikipedia.org/w/index.php?title=Cartel_de_Medell%C3%ADn&oldid=173971882

    "Yazidis clan",  # (high) [religious/ethnic community] Yazidis are a religious and ethnic minority, not a criminal or armed organization.
    #     deg:   0
    #     src:   https://en.wikipedia.org/w/index.php?title=Russian_mafia&oldid=1354221339

}
