# netlify.toml
[build]
  command = "hugo --gc --minify" # Comando para construir o seu site Hugo
  publish = "docs"             # Pasta onde o Hugo gera o site construído
  functions = "netlify/functions"  # Onde o Netlify encontra as suas funções
[build.environment]
  HUGO_VERSION = "0.84.4"  # <--- ESSENCIAL
  NODE_VERSION = "18"    # <--- BOM PARA AS FUNÇÕES