# 0_node_blocklist.py
# Auto-generated by 0_review_wrong_merges.py — REVIEW before pasting into
# curated_corrections.py. Each entry is a merge the LLM judged to be WRONG
# (two different orgs sharing a name). Format: {canonical: {wrong_name}}.
# 87 canonical(s), 105 wrong merge(s), 0 flagged for review.

BLOCKLIST = {

    # American Mafia: https://en.wikipedia.org/w/index.php?title=American_Mafia&oldid=1356595172 | https://es.wikipedia.org/w/index.php?title=Mafia_estadounidense&oldid=172604697
    "American Mafia": {
        "Italian mafia",  # (high) Record B describes a generic 'Italian mafia' allied with Armenian mafia, not the specific American Mafia.
        #     ↳ Italian mafia: https://en.wikipedia.org/w/index.php?title=Armenian_mafia&oldid=1339076581
        "Italian Mob",  # (high) Record B describes a specific early 20th-century London gang led by Charles Sabini, not the American Mafia.
        #     ↳ Italian Mob: https://en.wikipedia.org/w/index.php?title=Hoxton_Gang&oldid=1345129106
    },

    # Los Zetas: https://en.wikipedia.org/w/index.php?title=Los_Zetas&oldid=1359457252 | https://es.wikipedia.org/w/index.php?title=Los_Zetas&oldid=173894205
    "Los Zetas": {
        "Grupo Bravo",  # (high) Grupo Bravo is a faction that allied with Gulf Cartel against Cártel del Noreste, which is a splinter of Los Zetas, not the same as the original Los Zetas.
        #     ↳ Grupo Bravo: https://en.wikipedia.org/w/index.php?title=Los_Zetas&oldid=1359457252
        "Talibans",  # (high) Record A is a Mexican cartel, while Record B is a Haitian gang, with no evidence of connection.
        #     ↳ Talibans: https://en.wikipedia.org/w/index.php?title=Timeline_of_gang-related_events_in_Haiti&oldid=1348653135
    },

    # Genovese crime family: https://en.wikipedia.org/w/index.php?title=Genovese_crime_family&oldid=1358995069
    "Genovese crime family": {
        "Westside Mob",  # (high) Record A is the Genovese crime family, a New York Mafia family, while Record B is a 1920s Detroit faction with a different name and location.
        #     ↳ Westside Mob: https://en.wikipedia.org/w/index.php?title=Detroit_Partnership&oldid=1355077764
    },

    # Islamic State: https://en.wikipedia.org/w/index.php?title=Islamic_State&oldid=1359049369
    "Islamic State": {
        "Islamic State in Somalia",  # (high) Record A is the global Islamic State, while Record B is a specific local affiliate in Somalia, which is a distinct entity.
        #     ↳ Islamic State in Somalia: https://en.wikipedia.org/w/index.php?title=Al-Shabaab_%28militant_group%29&oldid=1359299745
        "Islamic State of Iraq and Syria",  # (high) Record A describes the global Islamic State, while Record B describes an affiliate in Yemen, which is a different entity.
        #     ↳ Islamic State of Iraq and Syria: https://en.wikipedia.org/w/index.php?title=Al-Qaeda_in_the_Arabian_Peninsula&oldid=1343113841
    },

    # La Familia Michoacana: https://en.wikipedia.org/w/index.php?title=La_Familia_Michoacana&oldid=1356650201 | https://es.wikipedia.org/w/index.php?title=La_Familia_Michoacana&oldid=173825530
    "La Familia Michoacana": {
        "La Familia",  # (high) Record A is a Mexican drug cartel, while Record B is a motorcycle gang involved with Al-Zein families, indicating different types of organizations.
        #     ↳ La Familia: https://en.wikipedia.org/w/index.php?title=Al-Zein_crime_family&oldid=1359554126
    },

    # Juárez Cartel: https://en.wikipedia.org/w/index.php?title=Ju%C3%A1rez_Cartel&oldid=1359568158 | https://es.wikipedia.org/w/index.php?title=C%C3%A1rtel_de_Ju%C3%A1rez&oldid=173820393
    "Juárez Cartel": {
        "Nuevo Cartel de Juárez",  # (high) Record B is a splinter group that broke away from the original Juárez Cartel, making them distinct entities.
        #     ↳ Nuevo Cartel de Juárez: https://en.wikipedia.org/w/index.php?title=Ju%C3%A1rez_Cartel&oldid=1359568158
        "Nuevo Cártel de Juárez",  # (high) Record B is a splinter group formed in 2011, distinct from the original Juárez Cartel described in Record A.
        #     ↳ Nuevo Cártel de Juárez: https://es.wikipedia.org/w/index.php?title=La_L%C3%ADnea&oldid=172511186
        "Nuevo Cártel De Juárez",  # (high) Record B is a distinct splinter group 'Nuevo Cártel De Juárez' that is an enemy of Los Ciclones, not the original Juárez Cartel.
        #     ↳ Nuevo Cártel De Juárez: https://es.wikipedia.org/w/index.php?title=Los_Ciclones&oldid=173904912
    },

    # Taliban: https://en.wikipedia.org/w/index.php?title=Taliban&oldid=1359460136
    "Taliban": {
        "Taliban (Kenyan gang)",  # (high) Record A is an Afghan political/military group, while Record B is a Kenyan criminal gang; they are unrelated despite sharing the name 'Taliban'.
        #     ↳ Taliban (Kenyan gang): https://en.wikipedia.org/w/index.php?title=Taliban_%28gang%29&oldid=1338833033
    },

    # Primeiro Comando da Capital: https://en.wikipedia.org/w/index.php?title=Primeiro_Comando_da_Capital&oldid=1358436972 | https://pt.wikipedia.org/w/index.php?title=Primeiro_Comando_da_Capital&oldid=72382164
    "Primeiro Comando da Capital": {
        "Colombian Communist Party",  # (high) Record A is a Brazilian drug cartel founded in 1993, while Record B is a Colombian communist party from 1930, with no overlap in type, country, or era.
        #     ↳ Colombian Communist Party: https://en.wikipedia.org/w/index.php?title=Revolutionary_Armed_Forces_of_Colombia&oldid=1357250189
    },

    # Philadelphia crime family: https://en.wikipedia.org/w/index.php?title=Philadelphia_crime_family&oldid=1356672020
    "Philadelphia crime family": {
        "'Ndrina Bruno",  # (high) Record A is an Italian-American Mafia family in Philadelphia, while Record B is a 'Ndrina (Calabrian Mafia group) in Italy, with no connection.
        #     ↳ 'Ndrina Bruno: https://it.wikipedia.org/w/index.php?title=%27Ndrina_Vallelunga&oldid=149663894
    },

    # Albanian mafia: https://en.wikipedia.org/w/index.php?title=Albanian_mafia&oldid=1357542477 | https://es.wikipedia.org/w/index.php?title=Mafia_albanesa&oldid=173535231
    "Albanian mafia": {
        "Albanian Mob (GTA IV)",  # (high) Record A describes real-world Albanian mafia, while Record B describes a fictional organization from a video game.
        #     ↳ Albanian Mob (GTA IV): https://en.wikipedia.org/w/index.php?title=Albanian_mafia&oldid=1357542477
    },

    # Knights Templar Cartel: https://en.wikipedia.org/w/index.php?title=Knights_Templar_Cartel&oldid=1353017438 | https://es.wikipedia.org/w/index.php?title=C%C3%A1rtel_de_los_Caballeros_Templarios&oldid=172510554
    "Knights Templar Cartel": {
        "Guardia Michoacana",  # (high) Record A is the Knights Templar Cartel, while Record B is Guardia Michoacana, a different group allied with Los Viagras.
        #     ↳ Guardia Michoacana: https://en.wikipedia.org/w/index.php?title=Los_Viagras&oldid=1356484458
    },

    # Mongols MC: https://en.wikipedia.org/w/index.php?title=Mongols_MC_criminal_allegations_and_incidents&oldid=1336330137
    "Mongols MC": {
        "Mongols MC (Quebec)",  # (high) Record B describes a Quebec-based club unrelated to the U.S.-based Mongols MC, absorbed by a different club in 1974.
        #     ↳ Mongols MC (Quebec): https://en.wikipedia.org/w/index.php?title=Popeye_Moto_Club&oldid=1339935529
    },

    # FARC dissidents: https://en.wikipedia.org/w/index.php?title=FARC_dissidents&oldid=1356641545
    "FARC dissidents": {
        "Fuerzas Armadas Revolucionarias de Colombia",  # (high) Record A refers to post-2016 dissident factions, while Record B describes the original FARC guerrilla group from an earlier era.
        #     ↳ Fuerzas Armadas Revolucionarias de Colombia: https://es.wikipedia.org/w/index.php?title=Cartel_de_Medell%C3%ADn&oldid=173971882
    },

    # Oficina de Envigado: https://en.wikipedia.org/w/index.php?title=Oficina_de_Envigado&oldid=1339085917 | https://es.wikipedia.org/w/index.php?title=Oficina_de_Envigado&oldid=171967973
    "Oficina de Envigado": {
        "La Oficina",  # (high) Record A is the Oficina de Envigado in Colombia, while Record B is a splinter group in Mexico run by Chapo Isidro, indicating different organizations.
        #     ↳ La Oficina: https://en.wikipedia.org/w/index.php?title=Beltr%C3%A1n-Leyva_Organization&oldid=1352425846
    },

    # Los Viagras: https://en.wikipedia.org/w/index.php?title=Los_Viagras&oldid=1356484458 | https://es.wikipedia.org/w/index.php?title=Los_Viagras&oldid=172526054
    "Los Viagras": {
        "Los Sierra",  # (high) Los Viagras is an armed wing of LNFM Cartel in Michoacán, while Los Sierra is a separate group created by the Cártel del Golfo.
        #     ↳ Los Sierra: https://es.wikipedia.org/w/index.php?title=C%C3%A1rtel_del_Golfo&oldid=173930064
    },

    # Five Families: https://en.wikipedia.org/w/index.php?title=Five_Families&oldid=1349444039
    "Five Families": {
        "Gambino family",  # (high) Record A refers to the collective Five Families, while Record B is one specific family within that group.
        #     ↳ Gambino family: https://en.wikipedia.org/w/index.php?title=%27Ndrangheta&oldid=1358567061
    },

    # Cleveland crime family: https://en.wikipedia.org/w/index.php?title=Cleveland_crime_family&oldid=1359474318
    "Cleveland crime family": {
        "Cleveland Syndicate",  # (high) Record A is an Italian American Mafia family, while Record B is a Prohibition-era syndicate of Irish and Jewish gangsters.
        #     ↳ Cleveland Syndicate: https://en.wikipedia.org/w/index.php?title=Irish_mob&oldid=1358001296
    },

    # Los Lobos: https://en.wikipedia.org/w/index.php?title=Los_Lobos_%28gang%29&oldid=1357091438 | https://es.wikipedia.org/w/index.php?title=Los_Lobos_%28pandilla%29&oldid=173798444 | https://pt.wikipedia.org/w/index.php?title=Los_Lobos_%28quadrilha%29&oldid=70002102
    "Los Lobos": {
        "Nueva Generación",  # (high) Record A is an Ecuadorian splinter group of Los Choneros formed in 2020, while Record B is a Colombian organization active since 2006.
        #     ↳ Nueva Generación: https://en.wikipedia.org/w/index.php?title=Illegal_drug_trade_in_Colombia&oldid=1332728464
    },

    # Hamas: https://en.wikipedia.org/w/index.php?title=Hamas&oldid=1359500467
    "Hamas": {
        "Movement of Society for Peace",  # (high) Hamas is a Palestinian Islamist organization, while Movement of Society for Peace is an Algerian political party; they are unrelated.
        #     ↳ Movement of Society for Peace: https://en.wikipedia.org/w/index.php?title=Muslim_Brotherhood&oldid=1359583929
    },

    # Houthis: https://en.wikipedia.org/w/index.php?title=Houthis&oldid=1358892022
    "Houthis": {
        "Ansar Allah",  # (high) Record A describes the Yemeni Houthi movement (Ansar Allah), while Record B describes a Palestinian group associated with Hezbollah, which are different entities.
        #     ↳ Ansar Allah: https://en.wikipedia.org/w/index.php?title=Hezbollah&oldid=1359125680
    },

    # Gangster Disciples: https://en.wikipedia.org/w/index.php?title=Gangster_Disciples&oldid=1357887827
    "Gangster Disciples": {
        "6th Rotterdam Gangster Disciples",  # (high) Record A is a large US-based gang, while Record B is a Dutch street gang with a different name and location.
        #     ↳ 6th Rotterdam Gangster Disciples: https://en.wikipedia.org/w/index.php?title=List_of_gangs_in_the_Netherlands&oldid=1355175034
        "Amsterdam Insane Gangster Disciples",  # (high) Record A is a large US-based gang, while Record B is a Dutch street gang with a different name and location.
        #     ↳ Amsterdam Insane Gangster Disciples: https://en.wikipedia.org/w/index.php?title=List_of_gangs_in_the_Netherlands&oldid=1355175034
    },

    # West End Gang: https://en.wikipedia.org/w/index.php?title=West_End_Gang&oldid=1338935800 | https://it.wikipedia.org/w/index.php?title=West_End_Gang&oldid=137645819
    "West End Gang": {
        "Irish gang",  # (high) Record B describes a rival gang wiped out by the Dubois Brothers, while Record A is the West End Gang, which was not wiped out and is still active.
        #     ↳ Irish gang: https://en.wikipedia.org/w/index.php?title=Dubois_brothers&oldid=1319483457
    },

    # Terceiro Comando Puro: https://en.wikipedia.org/w/index.php?title=Terceiro_Comando_Puro&oldid=1359161571 | https://pt.wikipedia.org/w/index.php?title=Terceiro_Comando_Puro&oldid=72353240
    "Terceiro Comando Puro": {
        "Terceiro Comando da Capital",  # (high) Terceiro Comando Puro is a distinct Brazilian faction that split from Terceiro Comando, while Terceiro Comando da Capital is a different group allied with a separate organization.
        #     ↳ Terceiro Comando da Capital: https://pt.wikipedia.org/w/index.php?title=Fam%C3%ADlia_Terror_de_Amap%C3%A1&oldid=71673930
    },

    # Al-Shabaab: https://en.wikipedia.org/w/index.php?title=Al-Shabaab_%28militant_group%29&oldid=1359299745
    "Al-Shabaab": {
        "Al-Shabaab (Mozambique)",  # (high) Record A is the Somali al-Shabaab allied with al-Qaeda, while Record B is a Mozambican group that spawned ISMP, distinct entities.
        #     ↳ Al-Shabaab (Mozambique): https://en.wikipedia.org/w/index.php?title=Islamic_State&oldid=1359049369
    },

    # Almighty Black P. Stone Nation: https://en.wikipedia.org/w/index.php?title=Almighty_Black_P._Stone_Nation&oldid=1358390136
    "Almighty Black P. Stone Nation": {
        "Black P. Stone Nation",  # (high) Record A describes a specific Chicago street gang, while Record B describes a gang alliance that included the Cobras, which is a different entity.
        #     ↳ Black P. Stone Nation: https://en.wikipedia.org/w/index.php?title=Mickey_Cobras&oldid=1358450994
    },

    # Spanish Gangster Disciples: https://en.wikipedia.org/w/index.php?title=Spanish_Gangster_Disciples&oldid=1358451001
    "Spanish Gangster Disciples": {
        "Black Gangster Disciples",  # (high) Record A is a Latino offshoot of the Gangster Disciples, while Record B is the original Black Gangster Disciples, which are distinct gangs.
        #     ↳ Black Gangster Disciples: https://en.wikipedia.org/w/index.php?title=Latin_Eagles&oldid=1358450991
    },

    # 'Ndrina Gallico: https://it.wikipedia.org/w/index.php?title=%27Ndrina_Gallico&oldid=149189587
    "'Ndrina Gallico": {
        "Clan Gallico",  # (low) Record B's description is too vague to confirm it is the same 'Ndrina Gallico; it could be a different group with a similar name.
        #     ↳ Clan Gallico: https://it.wikipedia.org/w/index.php?title=Clan_Licciardi&oldid=149575539
    },

    # Artistas Asesinos: https://en.wikipedia.org/w/index.php?title=Artistas_Asesinos&oldid=1339076599 | https://es.wikipedia.org/w/index.php?title=Artistas_Asesinos&oldid=170233205
    "Artistas Asesinos": {
        "Arakan Army",  # (high) Artistas Asesinos is a Mexican street gang, while Arakan Army is a Myanmar-based ethnic armed group; they are unrelated organizations.
        #     ↳ Arakan Army: https://en.wikipedia.org/w/index.php?title=Myanmar_conflict&oldid=1350747295
    },

    # Provisional Irish Republican Army: https://en.wikipedia.org/w/index.php?title=Provisional_Irish_Republican_Army&oldid=1359436308
    "Provisional Irish Republican Army": {
        "Óglaigh na hÉireann",  # (high) Record A is the Provisional IRA (1969-2005), while Record B is a dissident splinter group formed in 2005/6 that uses the same Irish name but is a different organization.
        #     ↳ Óglaigh na hÉireann: https://en.wikipedia.org/w/index.php?title=Provisional_Irish_Republican_Army&oldid=1359436308
    },

    # Armenian Power: https://en.wikipedia.org/w/index.php?title=Armenian_Power&oldid=1340540308 | https://es.wikipedia.org/w/index.php?title=Armenian_Power&oldid=170919763
    "Armenian Power": {
        "AP-13",  # (low) Record B is described only as an enemy of Barrio 18, which is a Central American gang, while Record A is a specific Armenian-American gang in the US; the name overlap is weak and the descriptions do not clearly align.
        #     ↳ AP-13: https://es.wikipedia.org/w/index.php?title=Mara_Barrio_18&oldid=173857246
    },

    # 'Ndrina Romeo: https://it.wikipedia.org/w/index.php?title=%27Ndrina_Romeo&oldid=149618103
    "'Ndrina Romeo": {
        "Romeo 'ndrina",  # (medium) Record A describes the Romeo 'ndrina in San Luca, while Record B describes a different clan in Platì associated with the Barbaro.
        #     ↳ Romeo 'ndrina: https://en.wikipedia.org/w/index.php?title=Francesco_Barbaro_%28Castanu%29&oldid=1354937428
    },

    # Al-Qaeda in the Islamic Maghreb: https://en.wikipedia.org/w/index.php?title=Al-Qaeda_in_the_Islamic_Maghreb&oldid=1357733988
    "Al-Qaeda in the Islamic Maghreb": {
        "AQIM",  # (low) Record B describes an insurgent group with ties to Al-Shabaab, which is not characteristic of AQIM, which operates in North Africa and the Sahel.
        #     ↳ AQIM: https://en.wikipedia.org/w/index.php?title=Al-Shabaab_%28militant_group%29&oldid=1359299745
    },

    # Yakuza: https://en.wikipedia.org/w/index.php?title=Yakuza&oldid=1359552014 | https://es.wikipedia.org/w/index.php?title=Yakuza&oldid=173238368
    "Yakuza": {
        "Imperial Japanese Army",  # (high) Record A describes the Yakuza criminal syndicate, while Record B refers to the Imperial Japanese Army, a military force.
        #     ↳ Imperial Japanese Army: https://en.wikipedia.org/w/index.php?title=Honghuzi&oldid=1330761088
    },

    # Irish mob: https://en.wikipedia.org/w/index.php?title=Irish_mob&oldid=1358001296
    "Irish mob": {
        "Oklahoma Irish Mob",  # (high) Record A describes a historical ethnic organized crime network in the US, while Record B is a specific prison gang in Oklahoma, distinct in structure and scope.
        #     ↳ Oklahoma Irish Mob: https://en.wikipedia.org/w/index.php?title=Irish_mob&oldid=1358001296
    },

    # Diablos Motorcycle Club: https://en.wikipedia.org/w/index.php?title=Diablos_Motorcycle_Club&oldid=1354073110 | https://en.wikipedia.org/w/index.php?title=Diablos_Motorcycle_Club_%28founded_1999%29&oldid=1350095302
    "Diablos Motorcycle Club": {
        "Diablos",  # (high) Record A is a US-based outlaw motorcycle club founded in 1961, while Record B is a Swedish affiliate of Bandidos, a different organization.
        #     ↳ Diablos: https://en.wikipedia.org/w/index.php?title=Bandidos_MC_criminal_allegations_and_incidents&oldid=1358972384
        "Diablos MC",  # (high) Different countries and affiliations: A is a US-based club, B is an Australian/Finish club allied with Bandidos.
        #     ↳ Diablos MC: https://en.wikipedia.org/w/index.php?title=Bandidos_MC_criminal_allegations_and_incidents&oldid=1358972384
    },

    # Peckham Boys: https://en.wikipedia.org/w/index.php?title=Peckham_Boys&oldid=1354494846
    "Peckham Boys": {
        "Chestnut Estate",  # (high) Record A describes a South London gang based in Peckham, while Record B describes a splinter group from Tottenham Mandem, which is a North London gang.
        #     ↳ Chestnut Estate: https://en.wikipedia.org/w/index.php?title=Tottenham_Mandem&oldid=1343929340
    },

    # Rockers Motor Club: https://en.wikipedia.org/w/index.php?title=Rockers_Motor_Club&oldid=1347361915
    "Rockers Motor Club": {
        "Montreal Rockers Motorcycle Club",  # (high) Record A is a Hells Angels support club founded in 1992, while Record B is an earlier independent club that became an Outlaws chapter in 1978.
        #     ↳ Montreal Rockers Motorcycle Club: https://en.wikipedia.org/w/index.php?title=Rockers_Motor_Club&oldid=1347361915
    },

    # Bonde do Maluco: https://en.wikipedia.org/w/index.php?title=Bonde_do_Maluco&oldid=1356722368 | https://pt.wikipedia.org/w/index.php?title=Bonde_do_Maluco&oldid=71938521
    "Bonde do Maluco": {
        "Bonde dos Malucos",  # (medium) Different states (Bahia vs. Rio Grande do Norte) and different alliances (PCC vs. Sindicato do Crime) suggest distinct organizations despite similar names.
        #     ↳ Bonde dos Malucos: https://pt.wikipedia.org/w/index.php?title=Sindicato_do_Crime_do_Rio_Grande_do_Norte&oldid=71950677
    },

    # Muerte a Secuestradores: https://en.wikipedia.org/w/index.php?title=Muerte_a_Secuestradores&oldid=1359253744
    "Muerte a Secuestradores": {
        "Movement for Socialism",  # (high) Record A is a Colombian paramilitary group, while Record B is a Bolivian political party; they are entirely different entities.
        #     ↳ Movement for Socialism: https://en.wikipedia.org/w/index.php?title=Chapare_Cartel&oldid=1331343995
    },

    # Rebels Motorcycle Club: https://en.wikipedia.org/w/index.php?title=Rebels_Motorcycle_Club&oldid=1351250697
    "Rebels Motorcycle Club": {
        "Confederates Motorcycle Club",  # (high) Different countries (Australia vs. Netherlands) and no evidence linking the two clubs.
        #     ↳ Confederates Motorcycle Club: https://en.wikipedia.org/w/index.php?title=List_of_gangs_in_the_Netherlands&oldid=1355175034
    },

    # 'Ndrina Albanese: https://it.wikipedia.org/w/index.php?title=%27Ndrina_Albanese&oldid=149610970
    "'Ndrina Albanese": {
        "Mafia albanese",  # (high) Record A is a specific 'Ndrangheta clan in Calabria, while Record B refers to Albanian criminal groups, which are different entities.
        #     ↳ Mafia albanese: https://it.wikipedia.org/w/index.php?title=Cosa_nostra&oldid=150966666
    },

    # Greco Mafia clan: https://en.wikipedia.org/w/index.php?title=Greco_Mafia_clan&oldid=1358300462
    "Greco Mafia clan": {
        "Greco",  # (high) Record A is a Sicilian Mafia clan, while Record B is a 'ndrina (Calabrian 'Ndrangheta) led by a different person.
        #     ↳ Greco: https://it.wikipedia.org/w/index.php?title=%27Ndrina_Grande_Aracri&oldid=151052671
    },

    # Popular Liberation Army: https://en.wikipedia.org/w/index.php?title=Popular_Liberation_Army&oldid=1344078114
    "Popular Liberation Army": {
        "Disidencia del EPL",  # (high) Record A describes the original EPL guerrilla group, while Record B describes a dissident criminal group formed from EPL dissidents, which is a different entity.
        #     ↳ Disidencia del EPL: https://es.wikipedia.org/w/index.php?title=Bandas_y_grupos_emergentes_en_Colombia&oldid=173696645
        "People's Liberation Army",  # (high) Record A is a Colombian guerrilla group (EPL), while Record B is a paramilitary wing of a different faction in Peru.
        #     ↳ People's Liberation Army: https://en.wikipedia.org/w/index.php?title=Shining_Path&oldid=1359085067
    },

    # Real Irish Republican Army: https://en.wikipedia.org/w/index.php?title=Real_Irish_Republican_Army&oldid=1347283468
    "Real Irish Republican Army": {
        "Real IRA",  # (high) Record A describes the Real Irish Republican Army, a dissident republican paramilitary in Northern Ireland, while Record B describes a group linked to Liverpool crime groups, indicating a different organization.
        #     ↳ Real IRA: https://en.wikipedia.org/w/index.php?title=British_firms_%28organised_crime%29&oldid=1345977944
    },

    # Clan Russo dei Quartieri Spagnoli: https://it.wikipedia.org/w/index.php?title=Clan_Russo_dei_Quartieri_Spagnoli&oldid=149861225
    "Clan Russo dei Quartieri Spagnoli": {
        "Clan Russo",  # (high) Record A is a Camorra clan from Quartieri Spagnoli, Naples, while Record B is a different Camorra clan from Nola, allied with Clan Alfieri.
        #     ↳ Clan Russo: https://it.wikipedia.org/w/index.php?title=Clan_Alfieri&oldid=150454082
    },

    # Organised crime in Nigeria: https://en.wikipedia.org/w/index.php?title=Organised_crime_in_Nigeria&oldid=1339973705
    "Organised crime in Nigeria": {
        "Nigerian mafia",  # (high) Record A describes organized crime in Nigeria broadly, while Record B refers specifically to Nigerian groups operating in Italy, which are distinct subsets.
        #     ↳ Nigerian mafia: https://en.wikipedia.org/w/index.php?title=Camorra&oldid=1359667351
    },

    # Família do Norte: https://en.wikipedia.org/w/index.php?title=Fam%C3%ADlia_do_Norte&oldid=1356843015 | https://pt.wikipedia.org/w/index.php?title=Fam%C3%ADlia_do_Norte&oldid=71585855
    "Família do Norte": {
        "Cartel do Norte",  # (high) Record B is a splinter faction of Record A, not the same organization.
        #     ↳ Cartel do Norte: https://pt.wikipedia.org/w/index.php?title=Fam%C3%ADlia_do_Norte&oldid=71585855
    },

    # New Zealand Nomads: https://en.wikipedia.org/w/index.php?title=New_Zealand_Nomads&oldid=1353856653
    "New Zealand Nomads": {
        "Nomads",  # (high) Record A is a New Zealand gang formed in 1977, while Record B is a Scottish motorcycle club formed in 1966, with different locations, origins, and activities.
        #     ↳ Nomads: https://en.wikipedia.org/w/index.php?title=Blue_Angels_Motorcycle_Club&oldid=1359552773
        "Nomads MC",  # (high) Record A describes a New Zealand street gang, while Record B is an outlaw motorcycle club, which are typically different types of organizations.
        #     ↳ Nomads MC: https://en.wikipedia.org/w/index.php?title=Lebanese_mafia&oldid=1349835272
        "Nomads Motorcycle Club",  # (high) Record A is a New Zealand street gang, while Record B is a motorcycle club with different affiliations and location.
        #     ↳ Nomads Motorcycle Club: https://en.wikipedia.org/w/index.php?title=Bandidos_MC_criminal_allegations_and_incidents_in_Australia&oldid=1348186117
    },

    # The Firm: https://en.wikipedia.org/w/index.php?title=Kray_twins&oldid=1359378280
    "The Firm": {
        "Edmonton Firm",  # (high) The Firm is a specific East London gang led by the Kray twins, while Edmonton Firm is a different North London gang allied with TMD.
        #     ↳ Edmonton Firm: https://en.wikipedia.org/w/index.php?title=Tottenham_Mandem&oldid=1343929340
        "The British",  # (high) Record A is a historical London gang led by the Kray twins, while Record B is a modern Cape Town street gang with a different location and context.
        #     ↳ The British: https://en.wikipedia.org/w/index.php?title=The_Americans_%28gang%29&oldid=1339506060
    },

    # Bloque Metro de las AUC: https://es.wikipedia.org/w/index.php?title=Bloque_Metro_de_las_AUC&oldid=173052292
    "Bloque Metro de las AUC": {
        "Bloque Metro",  # (high) Record B is described as a dissident group of AUC and enemy of AUC, while Record A is a front of AUC, indicating they are different entities.
        #     ↳ Bloque Metro: https://es.wikipedia.org/w/index.php?title=Autodefensas_Unidas_de_Colombia&oldid=173610368
    },

    # Devil's Disciples Motorcycle Club (Canada): https://en.wikipedia.org/w/index.php?title=Devil%27s_Disciples_Motorcycle_Club_%28Canada%29&oldid=1341248245
    "Devil's Disciples Motorcycle Club (Canada)": {
        "Devil's Disciples",  # (high) Record A is a Canadian motorcycle club from the 1960s-70s, while Record B is a US street gang from the 1950s-60s that became the Black Disciples.
        #     ↳ Devil's Disciples: https://en.wikipedia.org/w/index.php?title=Black_Disciples&oldid=1353106894
        "Devils Disciples",  # (high) Record A is a Canadian MC active in the 1960s-70s, while Record B refers to a group active in 1994, likely a different entity.
        #     ↳ Devils Disciples: https://en.wikipedia.org/w/index.php?title=Quebec_Biker_War&oldid=1358024089
    },

    # Islamic State – Somalia Province: https://en.wikipedia.org/w/index.php?title=Islamic_State_%E2%80%93_Somalia_Province&oldid=1357459264
    "Islamic State – Somalia Province": {
        "Islamic State – Sahel Province",  # (high) Different geographic regions: Somalia vs. Sahel (Mali, Niger, Burkina Faso).
        #     ↳ Islamic State – Sahel Province: https://en.wikipedia.org/w/index.php?title=Islamic_State&oldid=1359049369
    },

    # New Irish Republican Army: https://en.wikipedia.org/w/index.php?title=New_Irish_Republican_Army&oldid=1352677234
    "New Irish Republican Army": {
        "Irish Republican Army",  # (high) Record A describes the New IRA formed in 2012, while Record B describes the original IRA from 1919-1921, which are distinct organizations.
        #     ↳ Irish Republican Army: https://en.wikipedia.org/w/index.php?title=Death_squad&oldid=1359525393
        "New IRA",  # (high) Record B describes a group allied with the Hutch gang, which is a criminal faction, not the dissident republican paramilitary group in Record A.
        #     ↳ New IRA: https://en.wikipedia.org/w/index.php?title=Hutch_Organised_Crime_Gang&oldid=1347826836
    },

    # Almighty Saints: https://en.wikipedia.org/w/index.php?title=Almighty_Saints&oldid=1339076539
    "Almighty Saints": {
        "Saints Motorcycle Club",  # (high) Record A is a street gang in Chicago, while Record B is a motorcycle club involved in a different incident.
        #     ↳ Saints Motorcycle Club: https://en.wikipedia.org/w/index.php?title=Outlaws_MC_criminal_allegations_and_incidents&oldid=1344644148
    },

    # Forty Thieves: https://en.wikipedia.org/w/index.php?title=Forty_Thieves_%28New_York_gang%29&oldid=1358093557
    "Forty Thieves": {
        "Forty Thieves (London gang)",  # (high) Different cities (New York vs. London) and no criminal ties between the two gangs.
        #     ↳ Forty Thieves (London gang): https://en.wikipedia.org/w/index.php?title=Forty_Thieves_%28New_York_gang%29&oldid=1358093557
        "Forty Thieves (Philadelphia gang)",  # (high) Record A is a specific 19th-century New York gang, while Record B is a different Philadelphia gang sharing only the name.
        #     ↳ Forty Thieves (Philadelphia gang): https://en.wikipedia.org/w/index.php?title=Forty_Thieves_%28New_York_gang%29&oldid=1358093557
    },

    # La Empresa: https://en.wikipedia.org/w/index.php?title=La_Empresa&oldid=1332164490
    "La Empresa": {
        "The Enterprise",  # (high) Record A is a Colombian drug cartel from the late 1990s, while Record B is a US secret organization from the 1980s supporting the Contras.
        #     ↳ The Enterprise: https://en.wikipedia.org/w/index.php?title=Contras&oldid=1359478486
    },

    # Native Mob: https://en.wikipedia.org/w/index.php?title=Native_Mob&oldid=1351606524
    "Native Mob": {
        "Native Syndicate",  # (high) Record A is a US-based Native American street gang, while Record B is a Canadian First Nations gang with different name and description.
        #     ↳ Native Syndicate: https://en.wikipedia.org/w/index.php?title=Hells_Angels_MC_criminal_allegations_and_incidents_in_Manitoba&oldid=1339178810
    },

    # Tambovskaya Bratva: https://en.wikipedia.org/w/index.php?title=Tambovskaya_Bratva&oldid=1339086896 | https://en.wikipedia.org/w/index.php?title=Vladimir_Kumarin&oldid=1308049550
    "Tambovskaya Bratva": {
        "Tambov gang",  # (high) Record A is a specific Russian criminal organization based in Saint Petersburg, while Record B is a Russian-speaking crime group active in Düsseldorf, likely a different group or chapter.
        #     ↳ Tambov gang: https://en.wikipedia.org/w/index.php?title=Crime_in_Germany&oldid=1353030176
    },

    # Tribesmen Motorcycle Club: https://en.wikipedia.org/w/index.php?title=Tribesmen_Motorcycle_Club&oldid=1351413837
    "Tribesmen Motorcycle Club": {
        "Tribesmen",  # (high) Record A is a New Zealand outlaw motorcycle club founded in 1980, while Record B is a Canadian biker gang that became a Hells Angels chapter in 1983.
        #     ↳ Tribesmen: https://en.wikipedia.org/w/index.php?title=Hells_Angels_MC_criminal_allegations_and_incidents_in_British_Columbia&oldid=1327107209
    },

    # Barriox13: https://en.wikipedia.org/w/index.php?title=Barriox13&oldid=1325437151
    "Barriox13": {
        "B13",  # (high) Record A is a Sureños gang in Los Angeles, while Record B is a gang in Brazil used by PCC, indicating different organizations.
        #     ↳ B13: https://en.wikipedia.org/w/index.php?title=Primeiro_Comando_da_Capital&oldid=1358436972
    },

    # Coffin Cheaters: https://en.wikipedia.org/w/index.php?title=Coffin_Cheaters&oldid=1351116258
    "Coffin Cheaters": {
        "Coffin Cheaters MC (US)",  # (high) Different countries, founding eras, and no connection between the Australian and US clubs.
        #     ↳ Coffin Cheaters MC (US): https://en.wikipedia.org/w/index.php?title=Coffin_Cheaters&oldid=1351116258
    },

    # Serb mafia in Scandinavia: https://en.wikipedia.org/w/index.php?title=Serb_mafia_in_Scandinavia&oldid=1356212054
    "Serb mafia in Scandinavia": {
        "Brotherhood",  # (high) Record A is a Serbian mafia group in Scandinavia, while Record B is a club in Birmingham that became a branch of the Black Pistons motorcycle club.
        #     ↳ Brotherhood: https://en.wikipedia.org/w/index.php?title=Black_Pistons_Motorcycle_Club&oldid=1351074542
    },

    # Dirty Dozen Motorcycle Club: https://en.wikipedia.org/w/index.php?title=Dirty_Dozen_Motorcycle_Club&oldid=1345368766
    "Dirty Dozen Motorcycle Club": {
        "Dirty Dozen",  # (low) Record B is described as a rival gang to the Savage Nomads, but no connection to the Arizona-based Dirty Dozen Motorcycle Club is established.
        #     ↳ Dirty Dozen: https://en.wikipedia.org/w/index.php?title=Savage_Nomads&oldid=1298518382
    },

    # Matsuba-kai: https://en.wikipedia.org/w/index.php?title=Matsuba-kai&oldid=1359015166
    "Matsuba-kai": {
        "Sekine-gumi",  # (high) Sekine-gumi is a precursor that disbanded in 1947, while Matsuba-kai was founded in 1953 from its remnants, making them distinct organizations.
        #     ↳ Sekine-gumi: https://en.wikipedia.org/w/index.php?title=Matsuba-kai&oldid=1359015166
    },

    # North Side Gang: https://en.wikipedia.org/w/index.php?title=North_Side_Gang&oldid=1346761976
    "North Side Gang": {
        "North Side",  # (high) Record A is a Prohibition-era Chicago criminal gang, while Record B is a Dutch football hooligan group.
        #     ↳ North Side: https://en.wikipedia.org/w/index.php?title=F-side&oldid=1348233369
    },

    # 'Ndrina Crea: https://it.wikipedia.org/w/index.php?title=%27Ndrina_Crea&oldid=149923187
    "'Ndrina Crea": {
        "Crea di Siderno",  # (high) Record A is the 'Ndrina Crea based in Rizziconi, while Record B is a different 'ndrina from Siderno, known as Crea di Siderno.
        #     ↳ Crea di Siderno: https://it.wikipedia.org/w/index.php?title=%27Ndrina_Gallace&oldid=149631004
    },

    # Camera di controllo: https://it.wikipedia.org/w/index.php?title=Camera_di_controllo&oldid=149861239
    "Camera di controllo": {
        "Sicilian Mafia Commission",  # (high) Record A describes the 'Ndrangheta's Camera di controllo, while Record B describes the Sicilian Mafia Commission, which are distinct governing bodies of different criminal organizations.
        #     ↳ Sicilian Mafia Commission: https://en.wikipedia.org/w/index.php?title=Angelo_La_Barbera&oldid=1341535754
    },

    # Clan Parisi: https://it.wikipedia.org/w/index.php?title=Clan_Parisi&oldid=149844960
    "Clan Parisi": {
        "Camorra clan Parisi",  # (high) Record A is a Bari-based clan from Apulia, while Record B is a Camorra clan from Campania, distinct regions and criminal structures.
        #     ↳ Camorra clan Parisi: https://it.wikipedia.org/w/index.php?title=%27Ndrina_Piromalli&oldid=151052791
    },

    # Gitans Moto Club: https://en.wikipedia.org/w/index.php?title=Gitans_Moto_Club&oldid=1322245000
    "Gitans Moto Club": {
        "Hells Angels Vikings",  # (high) Record A describes a French-Canadian gang that became Hells Angels Sherbrooke charter, while Record B describes an unsanctioned gang in Surrey, Canada, that renamed to Vikings, unrelated to the Sherbrooke group.
        #     ↳ Hells Angels Vikings: https://en.wikipedia.org/w/index.php?title=Hells_Angels_MC_criminal_allegations_and_incidents_in_the_United_Kingdom&oldid=1323829541
        "Vikings",  # (high) Record A's Vikings was a 1960s Canadian street gang that became Gitans MC, while Record B's Vikings is an Australian OMCG aligned with Hells Angels, distinct in country and timeline.
        #     ↳ Vikings: https://en.wikipedia.org/w/index.php?title=Hells_Angels_MC_criminal_allegations_and_incidents_in_Australia&oldid=1346691638
        "Vikings MC",  # (high) Record A's Vikings were a 1960s street gang in Quebec that became Gitans MC, while Record B's Vikings MC is a different club feuding with Bandidos in Victoria in the 1990s.
        #     ↳ Vikings MC: https://en.wikipedia.org/w/index.php?title=Bandidos_MC_criminal_allegations_and_incidents_in_Australia&oldid=1348186117
        "Vikings Motorcycle Club",  # (high) Record A's Vikings were a 1960s Sherbrooke street gang that became Gitans MC, while Record B's Vikings MC was a separate Quebec City biker gang active in the 1980s.
        #     ↳ Vikings Motorcycle Club: https://en.wikipedia.org/w/index.php?title=Satan%27s_Choice_Motorcycle_Club&oldid=1355761080
    },

    # Original Red Devils Motorcycle Club: https://en.wikipedia.org/w/index.php?title=Original_Red_Devils_Motorcycle_Club&oldid=1339086020
    "Original Red Devils Motorcycle Club": {
        "Red Devils",  # (high) Different countries (Canada vs. Belgium) and distinct histories; the Canadian club patched over in 2014, while the Belgian club is a separate entity.
        #     ↳ Red Devils: https://en.wikipedia.org/w/index.php?title=Hells_Angels_MC_criminal_allegations_and_incidents&oldid=1355885822
    },

    # Al-Zein crime family: https://en.wikipedia.org/w/index.php?title=Al-Zein_crime_family&oldid=1359554126
    "Al-Zein crime family": {
        "Al-Zein clan",  # (high) Record B describes a rival crime family to the Miri clan, while Record A is a large Mhallami mafia organization; they are distinct entities despite similar names.
        #     ↳ Al-Zein clan: https://en.wikipedia.org/w/index.php?title=Miri-Clan&oldid=1359554542
    },

    # Clerkenwell crime syndicate: https://en.wikipedia.org/w/index.php?title=Clerkenwell_crime_syndicate&oldid=1339077238
    "Clerkenwell crime syndicate": {
        "A-team",  # (high) Record A is the Clerkenwell crime syndicate (Adams Family) with alias 'A-team', while Record B describes a rival organization to Hellbanianz, which is a different group.
        #     ↳ A-team: https://en.wikipedia.org/w/index.php?title=Hellbanianz_%28gang%29&oldid=1349337073
    },

    # Israeli mafia: https://en.wikipedia.org/w/index.php?title=Israeli_mafia&oldid=1357126041
    "Israeli mafia": {
        "Israeli mafia (New York)",  # (high) Record A describes the entire Israeli mafia across Israel, while Record B is a specific New York-based syndicate from the 1980s.
        #     ↳ Israeli mafia (New York): https://en.wikipedia.org/w/index.php?title=Israeli_mafia&oldid=1357126041
    },

    # Mau Maus: https://en.wikipedia.org/w/index.php?title=Mau_Maus&oldid=1339085537
    "Mau Maus": {
        "The Mau Maus",  # (high) Record A describes a 1950s Puerto Rican gang in Brooklyn, while Record B describes an African American gang that was an enemy of the South Brooklyn Boys, indicating different organizations.
        #     ↳ The Mau Maus: https://en.wikipedia.org/w/index.php?title=South_Brooklyn_Boys&oldid=1339086777
    },

    # Chosen Few Motorcycle Club: https://en.wikipedia.org/w/index.php?title=Chosen_Few_Motorcycle_Club&oldid=1351115793
    "Chosen Few Motorcycle Club": {
        "36",  # (high) Record A is a motorcycle club, while Record B is a triad group; they are different types of organizations.
        #     ↳ 36: https://en.wikipedia.org/w/index.php?title=Wah_Kee&oldid=1339087596
    },

    # Green Gang: https://en.wikipedia.org/w/index.php?title=Green_Gang&oldid=1352003460
    "Green Gang": {
        "Green Street boys",  # (high) Record A is a historical Chinese triad, while Record B is a modern Dutch street gang with no connection.
        #     ↳ Green Street boys: https://en.wikipedia.org/w/index.php?title=List_of_gangs_in_the_Netherlands&oldid=1355175034
    },

    # Highwaymen Motorcycle Club: https://en.wikipedia.org/w/index.php?title=Highwaymen_Motorcycle_Club&oldid=1351127102
    "Highwaymen Motorcycle Club": {
        "Highwaymen",  # (high) Record A is a large US-based MC founded in 1954, while Record B is a small Canadian puppet club of Hells Angels that ended in 1983.
        #     ↳ Highwaymen: https://en.wikipedia.org/w/index.php?title=Hells_Angels_MC_criminal_allegations_and_incidents_in_British_Columbia&oldid=1327107209
    },

    # Organised crime in India: https://en.wikipedia.org/w/index.php?title=Organised_crime_in_India&oldid=1357628292
    "Organised crime in India": {
        "Indian Mafia",  # (high) Record A describes organized crime in India, while Record B is a specific street gang in Canada, despite the name overlap.
        #     ↳ Indian Mafia: https://en.wikipedia.org/w/index.php?title=Indigenous-based_organized_crime&oldid=1318019845
    },

    # Santa Cruz Cartel: https://en.wikipedia.org/w/index.php?title=Santa_Cruz_Cartel&oldid=1339086515
    "Santa Cruz Cartel": {
        "La Conexión",  # (high) Record A describes a Bolivian drug cartel, while Record B is described as a rival to La Corporación, indicating a different organization.
        #     ↳ La Conexión: https://en.wikipedia.org/w/index.php?title=La_Corporaci%C3%B3n&oldid=1313356057
    },

    # Hidden Valley Kings: https://en.wikipedia.org/w/index.php?title=Hidden_Valley_Kings&oldid=1353411890
    "Hidden Valley Kings": {
        "Queen City Kings",  # (high) Record A describes a neighborhood-based gang that is a branch of Queen City Kings, while Record B describes the parent gang itself, formed earlier by different members.
        #     ↳ Queen City Kings: https://en.wikipedia.org/w/index.php?title=Hidden_Valley_Kings&oldid=1353411890
    },

    # People's Aman Committee: https://en.wikipedia.org/w/index.php?title=People%27s_Aman_Committee&oldid=1351570103
    "People's Aman Committee": {
        "Palestinian Action Command",  # (high) Different countries, time periods, and descriptions: one is a Pakistani militant group from 2008, the other is a Palestinian military organization from 1963.
        #     ↳ Palestinian Action Command: https://en.wikipedia.org/w/index.php?title=Popular_Front_for_the_Liberation_of_Palestine&oldid=1358047725
    },

    # ROD Gang: https://en.wikipedia.org/w/index.php?title=ROD_Gang&oldid=1339086313
    "ROD Gang": {
        "Ride or Die gang",  # (high) Record A describes a drug ring in St. Roch, while Record B describes a rival gang from the 8th Ward, indicating different organizations.
        #     ↳ Ride or Die gang: https://en.wikipedia.org/w/index.php?title=39ers_gang&oldid=1357085379
    },

    # Salakau: https://en.wikipedia.org/w/index.php?title=Salakau&oldid=1348802754
    "Salakau": {
        "Sio Kun Tong",  # (low) Salakau is a Singaporean gang, while Sio Kun Tong is a Chinese secret society with no clear connection.
        #     ↳ Sio Kun Tong: https://en.wikipedia.org/w/index.php?title=Omega_%28prison_gang%29&oldid=1349647144
    },

    # Friends Stand United: https://en.wikipedia.org/w/index.php?title=Friends_Stand_United&oldid=1339077746
    "Friends Stand United": {
        "FSU",  # (high) Record A is an anti-fascist hardcore crew from Boston, while Record B is a straight edge street gang chapter in Huntington Beach, indicating different organizations.
        #     ↳ FSU: https://en.wikipedia.org/w/index.php?title=Peckerwood&oldid=1358450993
    },

    # Green Street Counts: https://en.wikipedia.org/w/index.php?title=Green_Street_Counts&oldid=1323757336
    "Green Street Counts": {
        "Green Street Counts (West)",  # (high) Record A describes the original Green Street Counts in Philadelphia, while Record B explicitly states it is a separate, unaffiliated group using the same name.
        #     ↳ Green Street Counts (West): https://en.wikipedia.org/w/index.php?title=Green_Street_Counts&oldid=1323757336
    },

    # Puccio family: https://en.wikipedia.org/w/index.php?title=Puccio_family&oldid=1351523384
    "Puccio family": {
        "'Ndrina Puccio",  # (high) Record A is an Argentine criminal family, while Record B is an Italian 'Ndrina affiliated with a different family.
        #     ↳ 'Ndrina Puccio: https://it.wikipedia.org/w/index.php?title=%27Ndrina_Maesano&oldid=149624562
    },

    # Real Calton Tongs: https://en.wikipedia.org/w/index.php?title=Tongland_%28gang_area%29&oldid=1280147052
    "Real Calton Tongs": {
        "The Tongs",  # (high) Different time periods (1960s vs early 20th century) and different specific gangs despite name overlap.
        #     ↳ The Tongs: https://en.wikipedia.org/w/index.php?title=Penny_Mobs&oldid=1320090313
        "Tongs",  # (high) Record A is a Scottish teenage gang from the 1960s, while Record B refers to Chinese criminal organizations from the late 19th century.
        #     ↳ Tongs: https://en.wikipedia.org/w/index.php?title=Gangs_in_the_United_States&oldid=1359038503
    },

}
