# 4_umbrella_orgs.py
# Auto-generated by 4_review_umbrella_orgs.py — DeepSeek judged every node
# in the graph; below are the ones it judged to be UMBRELLA TERMS or
# COLLECTIVE CATEGORIES, not real single criminal organizations.
#
# REVIEW, then paste the good entries into curated_corrections.py TO_BE_EXCLUDED.
# 7_apply_corrections.py drops those nodes and every edge touching them.
#
# 5568 node(s) judged | 365 umbrella(s) (high/medium), 0 low-confidence | 5203 real org(s), 0 error(s)
#
# Cost: 5,568 API call(s) | 4,478,552 prompt + 273,234 completion tokens | ~$1.51 (at $0.27/M in + $1.1/M out)

TO_BE_EXCLUDED = {
    "Sureños",  # (high) The description explicitly states it is an 'alliance' and 'umbrella' for hundreds of individual gangs, not a single structured organization.
    #     desc:  "The Sureños are a Mexican-American street gang alliance originating in Southern California, founded in 1967. They are lo…"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=Sure%C3%B1os&oldid=1338828425 | https://es.wikipedia.org/w/index.php?title=Sure%C3%B1os_%28pandilla%29&oldid=166655990

    "Albanian mafia",  # (high) The description explicitly states it is a 'general term for various criminal organizations' and refers to multiple groups based on ethnicity and region.
    #     desc:  "The Albanian mafia is a general term for various criminal organizations based in Albania, Kosovo, and other Albanian-maj…"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=Albanian_mafia&oldid=1357542477 | https://es.wikipedia.org/w/index.php?title=Mafia_albanesa&oldid=173535231

    "Syrian Democratic Forces",  # (high) The SDF is a coalition of multiple distinct militias and rebel groups, not a single criminal organization.
    #     desc:  "The Syrian Democratic Forces (SDF) is a Kurdish-led coalition of left-wing ethnic militias and rebel groups founded on 1…"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=Syrian_Democratic_Forces&oldid=1357129335

    "Popular Mobilization Forces",  # (high) The description explicitly calls it an 'umbrella group' comprising about 67 primarily Shia armed factions, indicating it is a collective category rather than a single organization.
    #     desc:  "Iranian-backed paramilitary umbrella group operating within Iraq, formally part of the Iraqi Armed Forces but de facto u…"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=Popular_Mobilization_Forces&oldid=1359397172

    "Triad",  # (high) The description refers to 'Chinese transnational organized crime syndicates' and 'modern triads' as a category of multiple groups, not a single organization.
    #     desc:  "Chinese transnational organized crime syndicates based in Greater China with global outposts. Originated from 18th-centu…"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=Triad_%28organised_crime%29&oldid=1356267438

    "FARC dissidents",  # (high) The description explicitly states it consists of multiple factions and is a collective term for former FARC members who refused to demobilize.
    #     desc:  "FARC dissidents are former members of the Revolutionary Armed Forces of Colombia (FARC) who refused to demobilize after …"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=FARC_dissidents&oldid=1356641545

    "Five Families",  # (high) The Five Families is a collective term for five distinct crime families, not a single organization.
    #     desc:  "The Five Families are the five major Italian American Mafia crime families operating in New York City, organized in 1931…"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=Five_Families&oldid=1349444039

    "Russian mafia",  # (high) The description explicitly calls it 'a collective of organized crime groups' and uses the term 'Russian mafia' as a general label for various distinct organizations.
    #     desc:  "The Russian mafia is a collective of organized crime groups originating and operating in Russia, emerging prominently af…"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=Russian_mafia&oldid=1354221339

    "Folk Nation",  # (high) The description explicitly states it is an alliance of street gangs, not a single organization.
    #     desc:  "The Folk Nation is an alliance of street gangs originating in Chicago, established in 1978 by Larry Hoover. It has sprea…"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=Folk_Nation&oldid=1358450946

    "Serbian mafia",  # (high) The description refers to 'various criminal organizations' and lists multiple distinct groups like 'Group America' and 'Pink Panthers', indicating it is a collective category.
    #     desc:  "The Serbian mafia comprises various criminal organizations based in Serbia or composed of ethnic Serbs, involved in smug…"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=Serbian_mafia&oldid=1356211942

    "Moroccan mafia",  # (high) The description explicitly states it is 'a collection of criminal organizations' and refers to 'these networks' as multiple distinct groups.
    #     desc:  "The Moroccan mafia is a collection of criminal organizations primarily composed of people of Moroccan descent, specializ…"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=Moroccan_mafia&oldid=1358369254

    "Turkish mafia",  # (high) The description defines it as 'a general term for criminal organizations' in Turkey, not a single group.
    #     desc:  "The Turkish mafia is a general term for criminal organizations based in Turkey or composed of Turkish citizens. They are…"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=Turkish_mafia&oldid=1357459317

    "Irish mob",  # (high) The description defines it as a collection of organized crime groups, not a single organization.
    #     desc:  "The Irish mob is a collection of organized crime groups composed of largely ethnic Irish members operating primarily in …"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=Irish_mob&oldid=1358001296

    "Cartel de los Soles",  # (high) The description explicitly states it is a term for disconnected cells within the military, not a single structured organization.
    #     desc:  "The Cartel de los Soles is a term used to describe criminal networks of drug trafficking and corruption within the Boliv…"
    #     tag:   all-nodes
    #     own:   https://es.wikipedia.org/w/index.php?title=C%C3%A1rtel_de_los_Soles&oldid=173742819

    "Corsican mafia",  # (high) The description explicitly states it is 'a collective of criminal groups' and 'consists of multiple families and gangs', indicating an umbrella term.
    #     desc:  "The Corsican mafia is a collective of criminal groups originating from Corsica, tied to both the French underworld and I…"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=Corsican_mafia&oldid=1359510277 | https://it.wikipedia.org/w/index.php?title=Mafia_corsa&oldid=149586642

    "Lebanese mafia",  # (high) The description defines it as a colloquial term for various organized crime groups from Lebanon, not a single organization.
    #     desc:  "The Lebanese mafia is a colloquial term for organized crime groups originating from Lebanon. Active globally due to the …"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=Lebanese_mafia&oldid=1349835272

    "Greek mafia",  # (high) The description explicitly calls it a 'colloquial term for various large-scale organized crime elements' and describes multiple independent groups.
    #     desc:  "Colloquial term for various large-scale organized crime elements originating in Greece or operated by Greeks. Indigenous…"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=Greek_mafia&oldid=1359175981

    "Armenian mafia",  # (high) The description explicitly calls it 'a general term for organized criminal gangs' structured in clans, indicating it is a collective category, not a single organization.
    #     desc:  "The Armenian mafia is a general term for organized criminal gangs consisting of ethnic Armenians, structured in clans ca…"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=Armenian_mafia&oldid=1339076581

    "Brazilian militias",  # (high) The description refers to 'Brazilian militias' as a general category of paramilitary groups in Rio de Janeiro, not a single organization with unified leadership.
    #     desc:  "Brazilian militias are illegal paramilitary groups primarily in Rio de Janeiro, composed of current and former police of…"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=Brazilian_militias&oldid=1357196323

    "Juggalo gangs",  # (high) The description refers to 'criminal groups that adopt the name and imagery of Juggalo culture' with 'documented sets in at least 21 U.S. states', indicating a collective category of multiple distinct gangs rather than a single organization.
    #     desc:  "Juggalo gangs are criminal groups that adopt the name and imagery of Juggalo culture, the fanbase of Insane Clown Posse.…"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=Juggalo_gangs&oldid=1356516825

    "Jamaican posses",  # (high) The article describes 'Jamaican posses' as a general term referring to various Jamaican organized crime gangs, not a single organization.
    #     tag:   all-nodes

    "Cartel of the Suns",  # (high) The description explicitly states it is an umbrella term for a network of corrupt officials, not a single organization.
    #     desc:  "An umbrella term for an alleged drug trafficking network involving members of the Venezuelan Armed Forces and political …"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=Cartel_of_the_Suns&oldid=1346188919

    "Organised crime in Nigeria",  # (high) The description discusses organized crime in Nigeria as a general phenomenon encompassing various groups and activities, not a single organization.
    #     desc:  "Organised crime in Nigeria encompasses fraud, banditry, drug trafficking, and racketeering, with groups operating across…"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=Organised_crime_in_Nigeria&oldid=1339973705

    "Organised crime in the Netherlands",  # (high) The description refers to a general phenomenon of organized crime in the Netherlands, not a specific group.
    #     desc:  "Organised crime in the Netherlands, known as penose, refers to criminal organizations primarily of Dutch descent, with r…"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=Organised_crime_in_the_Netherlands&oldid=1354688558

    "Disidencias de las FARC-EP",  # (high) The article describes 'Disidencias de las FARC-EP' as multiple groups that emerged from the FARC-EP, often rival, and not a single organization.
    #     tag:   all-nodes

    "Free Syrian Army",  # (high) The Free Syrian Army is a broad coalition of various rebel groups fighting in the Syrian Civil War, not a single unified organization.
    #     tag:   all-nodes

    "Three Brotherhood Alliance",  # (high) The description explicitly states it is an alliance of three distinct ethnic armed groups, not a single organization.
    #     desc:  "An alliance of three ethnic armed groups in Myanmar: the Arakan Army, Myanmar National Democratic Alliance Army, and Ta'…"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=Three_Brotherhood_Alliance&oldid=1358168913

    "British firms",  # (high) The description refers to 'organised crime groups originating in the United Kingdom' as a general category, not a specific organization.
    #     desc:  "British firms are organised crime groups originating in the United Kingdom, traditionally homegrown and involved in vari…"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=British_firms_%28organised_crime%29&oldid=1345977944

    "Galician Mafia",  # (high) The description refers to multiple drug smuggling groups in Galicia, not a single organization.
    #     desc:  "Drug smuggling groups based in the Spanish region of Galicia, known as a main European entry point for Colombian cocaine…"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=Galician_Mafia&oldid=1343927177

    "Kurdish mafia",  # (high) The description refers to 'organized crime groups run by ethnic Kurds' as a collective, not a single organization.
    #     desc:  "The Kurdish mafia comprises organized crime groups run by ethnic Kurds, operating primarily in Western Asia, Europe, and…"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=Kurdish_mafia&oldid=1359552669

    "National Crime Syndicate",  # (high) The National Crime Syndicate is described as a network of powerful criminals, not a single organization with its own structure.
    #     tag:   all-nodes

    "Northern Alliance",  # (high) The Northern Alliance is described as a coalition of multiple insurgent groups, not a single organization.
    #     tag:   all-nodes

    "Chinese Triads",  # (high) The term 'Chinese Triads' refers to various independent Chinese criminal organizations, not a single unified group.
    #     tag:   all-nodes

    "Colombian cartels",  # (high) The term 'Colombian cartels' is used as a general label for multiple distinct drug trafficking organizations from Colombia, not a single entity.
    #     tag:   all-nodes

    "Dixie Mafia",  # (high) The description states it is a 'general term for independent White Southern criminal networks' and describes it as 'loosely connected' with no single structure.
    #     desc:  "The Dixie Mafia is a loosely connected criminal organization originally based in Biloxi, Mississippi, operating primaril…"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=Dixie_Mafia&oldid=1351873303 | https://it.wikipedia.org/w/index.php?title=Dixie_Mafia&oldid=138655634

    "Fujianese organized crime",  # (high) The description refers to 'crime syndicates composed of Fujianese people' and 'covers Fujianese immigrant gangs' as a general category, not a single organization.
    #     desc:  "Fujianese organized crime refers to crime syndicates composed of Fujianese people, similar to triad gangs. The term prim…"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=Fujianese_organized_crime&oldid=1359356124

    "Jewish-American organized crime",  # (high) The description refers to a phenomenon within a community, not a single structured organization.
    #     desc:  "Jewish-American organized crime emerged within the American Jewish community in the late 19th and early 20th centuries, …"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=Jewish-American_organized_crime&oldid=1348451174

    "Montenegrin mafia",  # (high) The description refers to 'criminal organizations' and specifically names the Kavač and Škaljari clans as distinct groups, indicating it is a collective term.
    #     desc:  "The Montenegrin mafia refers to criminal organizations based in Montenegro or composed of Montenegrins, active since 199…"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=Montenegrin_mafia&oldid=1356211982

    "Piru gang alliance",  # (high) The Piru gang alliance is described as a collective of multiple distinct 'sets' (e.g., Cedar Block Piru, Elm Street Piru) within the larger Bloods alliance, not a single organization.
    #     tag:   all-nodes

    "Unione Corse",  # (high) The description explicitly states it is 'a term for Corsican organized crime as a whole' and describes it as a network of clans, not a single organization.
    #     desc:  "The Unione Corse is a term for Corsican organized crime as a whole during the 1930s–1970s, primarily involved in the Fre…"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=Unione_Corse&oldid=1344024427

    "Contras",  # (high) The description refers to 'anti-communist rebel groups' and 'dissidents and former National Guard members', indicating a collective of multiple groups rather than a single organization.
    #     desc:  "The Contras were anti-communist rebel groups that waged a guerrilla war against the Sandinista government in Nicaragua f…"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=Contras&oldid=1359478486

    "Gosha-kai",  # (high) The Gosha-kai is described as an anti-Yamaguchi federation composed of multiple distinct yakuza groups, not a single organization.
    #     tag:   all-nodes

    "Mexican drug cartels",  # (high) The term refers to multiple distinct criminal organizations in Mexico, not a single group.
    #     tag:   all-nodes

    "Romanian mafia",  # (high) The description defines it as a category of organized crime groups, not a single organization.
    #     desc:  "The Romanian mafia is the category of organized crime groups composed of Romanian citizens or diaspora members. Active p…"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=Romanian_mafia&oldid=1348228634

    "Thuggee",  # (high) The description defines Thuggee as a phenomenon of highway robbery by various gangs, not a single organization.
    #     desc:  "Thuggee was a phenomenon of highway robbery in the Indian subcontinent, where gangs of thugs murdered and robbed travele…"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=Thuggee&oldid=1359506425

    "Ukrainian mafia",  # (high) The description refers to 'loosely connected criminal organizations' and 'decentralized alliances', indicating it is a collective category rather than a single group.
    #     desc:  "Loosely connected criminal organizations originating in Ukraine, involved in drug trafficking, arms smuggling, money lau…"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=Ukrainian_mafia&oldid=1356204828

    "Azerbaijani mafia",  # (high) The description explicitly calls it 'a general term for organized criminal gangs consisting of ethnic Azerbaijanis', indicating it is a collective category, not a single organization.
    #     desc:  "The Azerbaijani mafia is a general term for organized criminal gangs consisting of ethnic Azerbaijanis. Based primarily …"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=Azerbaijani_mafia&oldid=1349646638

    "Brothers' Circle",  # (high) The description explicitly states it is a term used to refer to Russian organized crime, a loose translation of 'Bratva', and its existence is debated as a label for disparate gangs rather than a specific organization.
    #     desc:  "The Brothers' Circle is a term used to refer to Russian organized crime, commonly the Russian mafia. It is a loose trans…"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=Brothers%27_Circle&oldid=1310049073

    "Colombian drug cartels",  # (high) The term refers to multiple distinct drug trafficking organizations based in Colombia, not a single entity.
    #     tag:   all-nodes

    "Israeli mafia",  # (high) The description explicitly refers to 'organized crime groups operating in Israel' and lists multiple distinct crime families, indicating it is a collective term.
    #     desc:  "The Israeli mafia refers to organized crime groups operating in Israel or consisting of Israeli members. There are 16 cr…"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=Israeli_mafia&oldid=1357126041

    "Preman",  # (high) The description defines 'Preman' as a general term for Indonesian organized crime groups, not a specific organization.
    #     desc:  "Preman is a term for Indonesian organized crime groups, encompassing street-level criminals to crime bosses. The word or…"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=Preman_%28Indonesian_gangster%29&oldid=1345366816

    "South American drug cartels",  # (high) The term refers to various drug trafficking organizations across South America, not a single group.
    #     tag:   all-nodes

    "Congo River Alliance",  # (high) The description explicitly calls it a 'coalition of rebel groups', indicating it is an umbrella term for multiple distinct groups.
    #     tag:   all-nodes

    "G-Pèp",  # (high) The passages describe G-Pèp as an armed group aligned with other gangs, but it is referred to as a coalition or alliance, not a single organization with its own structure.
    #     tag:   all-nodes

    "Kanto-Hatsukakai",  # (high) The passages describe it as a 'federation of Tokyo-based yakuza groups' and a 'fraternal federation' of multiple distinct syndicates.
    #     tag:   all-nodes

    "Macedonian criminal organizations",  # (high) The article describes organized crime in North Macedonia as a general phenomenon involving multiple groups, not a single organization.
    #     tag:   all-nodes

    "Palestine Liberation Organization",  # (high) The PLO is a coalition of multiple Palestinian factions, not a single criminal organization.
    #     tag:   all-nodes

    "Ringvereine",  # (high) The description refers to 'criminal gangs' and 'convicts associations' as a category, not a single organization.
    #     desc:  "Criminal gangs operating in late 19th- and early 20th-century Germany, notably the Weimar period. Ostensibly convicts as…"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=Ringvereine&oldid=1334170336

    "Bulgarian mafia",  # (high) The description refers to 'criminal organizations' in Bulgaria, not a single group, and uses the term as a general label for various groups.
    #     desc:  "The Bulgarian mafia refers to criminal organizations based in Bulgaria, composed primarily of ethnic Bulgarians. Emergin…"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=Bulgarian_mafia&oldid=1357459835

    "Grupos de Autodefensa Comunitaria",  # (high) The description refers to multiple vigilante groups that arose independently, not a single organization with unified leadership.
    #     desc:  "Vigilante self-defense groups that arose in the Gulf of Mexico and South Mexico regions between 2012 and 2013. They form…"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=Grupos_de_autodefensa_comunitaria&oldid=1346688871 | https://es.wikipedia.org/w/index.php?title=Grupos_de_Autodefensa_Comunitaria&oldid=173169316

    "Pakistani mafia",  # (high) The description explicitly calls it 'a collection of ethnically based organized crime groups', indicating it is an umbrella term for multiple distinct organizations.
    #     desc:  "The Pakistani mafia is a collection of ethnically based organized crime groups operating in Pakistan and internationally…"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=Organised_crime_in_Pakistan&oldid=1352385637

    "Shabiha",  # (high) The article describes Shabiha as 'loosely-organized Assad loyalist Alawite mercenaries known collectively as Shabiha', indicating it is a collective term for various pro-government paramilitary units, not a single organization.
    #     tag:   all-nodes

    "Slovak mafia",  # (high) The description explicitly states it 'comprises various organized crime groups' and refers to a general phenomenon, not a single organization.
    #     desc:  "The Slovak mafia comprises various organized crime groups in Slovakia, primarily controlled by Slovak interests. It emer…"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=Slovak_mafia&oldid=1359154525

    "Snakehead (gang)",  # (high) The description refers to 'Chinese gangs' in general, not a single organization, and uses the term as a category for various smuggling groups.
    #     desc:  "Chinese gangs based in Fujian province that smuggle people to wealthier Western countries and regions. They use stolen p…"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=Snakehead_%28gang%29&oldid=1339086712

    "Alliance for Peace and Freedom",  # (high) The description identifies it as a European political party that includes multiple distinct far-right groups, not a single criminal organization.
    #     tag:   all-nodes

    "Army of Conquest",  # (high) The article describes it as an 'umbrella rebel group' and a 'joint command center' for multiple Syrian Islamist groups, not a single organization.
    #     tag:   all-nodes

    "Brooklyn Camorra",  # (high) The description explicitly calls it a 'loose grouping' of gangs, not a single organization.
    #     desc:  "A loose grouping of early-20th-century organized crime gangs formed among Italian immigrants from Naples and Campania in…"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=Camorra_in_New_York_City&oldid=1339077091

    "Cape Verdean organized crime",  # (high) The description refers to 'criminal organizations' and 'street gangs' collectively, not a single structured group.
    #     desc:  "Cape Verdean organized crime refers to criminal organizations active in Cape Verde and its diaspora, primarily involved …"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=Cape_Verdean_organized_crime&oldid=1356608201

    "Cartelli colombiani",  # (high) The term 'cartelli colombiani' is used in the passages as a general reference to Colombian drug cartels, not a specific organization.
    #     tag:   all-nodes

    "Honghuzi",  # (high) The description refers to 'armed Chinese robbers and bandits' as a general category, not a specific organization with a unified structure.
    #     desc:  "Armed Chinese robbers and bandits operating in the eastern Russia-China borderland from the second half of the 19th cent…"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=Honghuzi&oldid=1330761088

    "Iran",  # (high) Iran is a country, not a criminal organization; it is mentioned as a state actor supporting other groups.
    #     tag:   all-nodes

    "Islamic Resistance in Iraq",  # (high) The article describes it as a name used by multiple Iranian-backed PMF groups to claim attacks, not a single organization.
    #     tag:   all-nodes

    "Organised crime in India",  # (high) The description refers to 'various criminal groups' and 'the Mumbai underworld' as a general phenomenon, not a single organization.
    #     desc:  "Organised crime in India encompasses various criminal groups operating across the country and internationally, involved …"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=Organised_crime_in_India&oldid=1357628292

    "Polish-American organized crime",  # (high) The description refers to 'criminal groups composed of Polish immigrants' and lists multiple distinct factions, indicating it is a collective category rather than a single organization.
    #     desc:  "Polish-American organized crime refers to criminal groups composed of Polish immigrants and Polish Americans operating p…"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=Polish-American_organized_crime&oldid=1359176040

    "Yonsha-kai",  # (high) The Yonsha-kai is described as a fraternal federation of independent yakuza syndicates, not a single organization.
    #     tag:   all-nodes

    "Balkan Mafia",  # (high) The term 'Balkan Mafia' is used as a general label for various criminal organizations from the Balkan region, not a single structured group.
    #     tag:   all-nodes

    "Islamic Front",  # (high) The article describes the Islamic Front as an umbrella coalition of multiple rebel groups, not a single organization.
    #     tag:   all-nodes

    "Liverpool mafia",  # (high) The article describes it as an 'informal category of drug trafficking cartels' and a 'group of white, middle-aged former armed robbers', indicating it is a collective term rather than a single organization.
    #     tag:   all-nodes

    "Milieu",  # (high) The article describes 'Milieu' as a general term for organized crime in France, not a specific group.
    #     tag:   all-nodes

    "Obshchak",  # (high) The description explicitly calls it an 'umbrella organization' that settles conflicts among multiple distinct groups like the Russian mafia and Estonian organized crime.
    #     desc:  "The Obshchak is a traditional umbrella organization of criminal groups in Estonia, functioning as a trade union that set…"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=Obshchak&oldid=1350796198

    "Syrian National Army",  # (high) The Syrian National Army is a coalition of multiple Syrian opposition factions, not a single criminal organization.
    #     tag:   all-nodes

    "Alliance of Palestinian Forces",  # (high) The Alliance of Palestinian Forces is a political alliance of multiple Palestinian factions, not a single criminal organization.
    #     tag:   all-nodes

    "Alliance to Fight the Angels",  # (high) The description refers to a coalition of multiple distinct groups formed to resist the Hells Angels, not a single organization.
    #     tag:   all-nodes

    "Ba'athist Syria",  # (high) Ba'athist Syria refers to the Syrian state under Ba'athist rule, not a specific criminal organization.
    #     tag:   all-nodes

    "Black Panthers",  # (high) The passages refer to 'Black Panthers' as a gang in Berlin and also mention a 'Black Panther' in a different context, indicating it is a generic name used by multiple unrelated groups.
    #     tag:   all-nodes

    "Farm Mandem",  # (high) The article describes 'Farm Mandem' as a collective term for everyone from the Broadwater Farm estate, not a single organization.
    #     tag:   all-nodes

    "Jamaican posse",  # (high) The description refers to 'Jamaican organized crime gangs' as a category, not a single group, and notes the term 'posse' is a general label for various gangs.
    #     desc:  "Jamaican organized crime gangs originating in Kingston, Jamaica in the 1970s, initially as political enforcers for the J…"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=Jamaican_posse&oldid=1353350692

    "Joint Revolutionary Council",  # (high) The description states it was formed to group various guerrilla factions (MEND, RNDPVF, MB) into a common action committee.
    #     tag:   all-nodes

    "Katcha dacoits",  # (high) The description refers to 'criminal gangs' operating in a region, not a single organization with unified leadership.
    #     desc:  "Criminal gangs operating in the riverine areas of Sindh and Punjab, Pakistan, known for kidnapping, extortion, dacoity, …"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=Katcha_dacoits&oldid=1359606513

    "Manbij Military Council",  # (high) The description states the council was established to secure Manbij and included multiple previously unknown groups, indicating it is a coalition rather than a single organization.
    #     tag:   all-nodes

    "Mexican cartels",  # (high) The term 'Mexican cartels' is a collective category referring to multiple distinct drug trafficking organizations, not a single entity.
    #     tag:   all-nodes

    "Mujahideen Shura Council",  # (high) The Mujahideen Shura Council was a coalition of multiple Sunni insurgent groups formed in 2006, not a single organization.
    #     tag:   all-nodes

    "National Unity Government",  # (high) The National Unity Government is a political coalition formed by various ethnic armed groups and pro-democracy forces, not a single criminal organization.
    #     tag:   all-nodes

    "North Korea",  # (high) North Korea is a sovereign state, not a criminal organization; the article discusses state involvement in arms deals, not a specific criminal group.
    #     tag:   all-nodes

    "Northern Sun Battalion",  # (high) The Northern Sun Battalion is described as a coalition of multiple distinct Arab tribal and militia groups joining the SDF, not a single organization.
    #     tag:   all-nodes

    "Pathet Lao",  # (high) Pathet Lao is a political movement and army, not a criminal organization, and the description refers to it as a heterogeneous group of communist-led dissidents.
    #     tag:   all-nodes

    "Punjabi mafia",  # (high) The passages refer to 'Punjabi mafia' as a collective term for various Indo-Canadian crime groups, not a single organization.
    #     tag:   all-nodes

    "Russia",  # (high) The entry 'Russia' is a country, not a criminal organization; it appears as a mention-only node in a passage about international communications.
    #     tag:   all-nodes

    "Simón Bolívar Guerrilla Coordinating Board",  # (high) The description and passages indicate it was a coordinating board for multiple guerrilla groups, not a single organization.
    #     tag:   all-nodes

    "Syrian Islamic Front",  # (high) The article describes it as an umbrella under which Ahrar al-Sham operated, indicating it is a collective category rather than a single organization.
    #     tag:   all-nodes

    "Army of Revolutionaries",  # (high) The article describes it as 'originally an alliance within the FSA of several groups of diverse ethnic and political backgrounds', indicating it is a collective category.
    #     tag:   all-nodes

    "Axis of Resistance",  # (high) The passages describe it as an 'informal Iranian-led political and military coalition,' indicating it is a collective category, not a single organization.
    #     tag:   all-nodes

    "Bandas y grupos emergentes en Colombia",  # (high) The description refers to 'Mafia organizations operating in Colombia' as a category, not a single group.
    #     desc:  "Mafia organizations operating in Colombia, active in the internal armed conflict. They engage in homicide, extortion, ki…"
    #     tag:   all-nodes
    #     own:   https://es.wikipedia.org/w/index.php?title=Bandas_y_grupos_emergentes_en_Colombia&oldid=173696645

    "China",  # (high) The entry refers to a country, not a specific criminal organization.
    #     tag:   all-nodes

    "Chinese organized criminal groups",  # (high) The term refers to multiple distinct groups from China, not a single organization.
    #     tag:   all-nodes

    "Cobras",  # (high) The passages mention 'Cobras' as one of several neighborhood gangs consolidated into the Vice Lord Nation, and also as a level within Los Zetas, indicating it is a generic label for multiple distinct groups.
    #     tag:   all-nodes

    "Ergenekon",  # (high) Ergenekon is a controversial term from Turkish trials referring to an alleged clandestine network, not a single criminal organization.
    #     tag:   all-nodes

    "Fatah Halab",  # (high) Fatah Halab is described as a joint operations room, a coalition of multiple rebel groups, not a single organization.
    #     tag:   all-nodes

    "Federation of Islamic Organizations in Europe",  # (high) The article describes it as a 'pan-European umbrella organization' for the Muslim Brotherhood, indicating it is a collective category.
    #     tag:   all-nodes

    "International Freedom Battalion",  # (high) The International Freedom Battalion is a coalition of foreign fighters supporting the Syrian Democratic Forces, not a single criminal organization.
    #     tag:   all-nodes

    "Janjaweed",  # (high) The Janjaweed is described as a collective term for various Arab militias in Darfur, not a single structured organization.
    #     tag:   all-nodes

    "Kurdistan Communities Union",  # (high) The article explicitly states it is 'an umbrella organisation of Kurdish organisations' across multiple regions.
    #     tag:   all-nodes

    "Macanese organized crime groups",  # (high) The term refers to multiple criminal groups from Macau, not a single organization.
    #     tag:   all-nodes

    "Mafie russofone",  # (high) The term 'mafie russofone' is used as a collective category for various Russian-speaking criminal organizations, not a single group.
    #     tag:   all-nodes

    "Mara",  # (high) The description states 'the term is generalized from Mara Salvatrucha (MS-13) and also refers to the 18th Street Gang', indicating it is a collective label for multiple distinct gangs.
    #     desc:  "A form of gang originating in Los Angeles, California, that spread to Central American countries including El Salvador, …"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=Mara_%28gang%29&oldid=1338943612

    "March 8 Alliance",  # (high) The March 8 Alliance is a political coalition of multiple Lebanese parties and groups, not a single criminal organization.
    #     tag:   all-nodes

    "Nuvoletta-Gallo-Gionta",  # (high) The passage describes 'Nuvoletta-Gallo-Gionta' as a confederation of distinct groups (Nuvoletta, Gallo, Gionta, and others), not a single organization.
    #     tag:   all-nodes

    "Peshmerga",  # (high) Peshmerga refers to the military forces of the Kurdistan Region, not a single criminal organization.
    #     tag:   all-nodes

    "Red Shirts",  # (high) The passages describe 'Red Shirts' as a paramilitary group in Mexico and a separate insurgent group in the US, indicating it is a generic term for multiple distinct groups.
    #     tag:   all-nodes

    "Revolutionary Internationalist Movement",  # (high) The Revolutionary Internationalist Movement is a collective of Maoist groups, not a single organization.
    #     tag:   all-nodes

    "Somali pirates",  # (high) The term 'Somali pirates' is a general label for various independent pirate groups operating off the coast of Somalia, not a single organization.
    #     tag:   all-nodes

    "South American cartels",  # (high) The term 'South American cartels' is a general label for various drug trafficking organizations from South America, not a single group.
    #     tag:   all-nodes

    "Special Groups",  # (high) The article describes 'Special Groups' as Iranian-sponsored Shia groups that fought in the Iraqi insurgency, referring to multiple distinct organizations.
    #     tag:   all-nodes

    "Viv Ansanm",  # (high) The article describes Viv Ansanm as a coalition formed by G9 and G-Pèp, two distinct armed groups, making it an umbrella term for a collective alliance.
    #     tag:   all-nodes

    "Việt Minh",  # (high) Việt Minh is a broad political and military coalition, not a single criminal organization.
    #     tag:   all-nodes

    "Volunteers",  # (high) The term 'Volunteers' in the provided context refers to a general category of soldiers and volunteers, not a specific criminal organization.
    #     tag:   all-nodes

    "Wazalendo",  # (high) The article describes 'wazalendo' as a Swahili term meaning 'patriots' used as a banner for numerous local militias, not a single organization.
    #     tag:   all-nodes

    "Wo Group",  # (high) The article describes the Wo Group as one of four main groups of triads, a collective category that includes multiple distinct societies like Wo Shing Wo.
    #     tag:   all-nodes

    "'Ndrina di Cosenza",  # (high) The article refers to 'le 'ndrine di Cosenza' (the 'ndrine of Cosenza) as a collective of families, not a single organization.
    #     tag:   all-nodes

    "'Ndrine dell'alto Ionio",  # (high) The term refers to multiple 'ndrine from the Alto Ionio area, not a single organization.
    #     tag:   all-nodes

    "'Ndrine sanlucote",  # (high) The term 'ndrine sanlucote' refers to 'ndrine (plural) from San Luca, a collective category for multiple distinct 'Ndrangheta clans from that locality, not a single organization.
    #     tag:   all-nodes

    "28 prison number gang",  # (high) The article describes the 28 prison number gang as a corporate body or camp that aligns with multiple smaller gangs, not a single organization.
    #     tag:   all-nodes

    "Aast",  # (high) The article describes 'Aast' as a 'Russian accelerationist network', which is a loose ideological movement, not a specific criminal organization.
    #     tag:   all-nodes

    "Active Club Network",  # (high) The article describes it as a 'loose association of various neo-Nazi and white supremacist groups', indicating it is a collective category, not a single organization.
    #     tag:   all-nodes

    "African-American mob",  # (high) The term 'African-American mob' is a general label for various African-American organized crime groups, not a single organization.
    #     tag:   all-nodes

    "All-Japanese Conference of Patriotic Associations",  # (high) The article explicitly describes it as an umbrella organization of 80 right-wing groups and yakuza groups.
    #     tag:   all-nodes

    "American Camorra",  # (high) The passage refers to 'members of the American Camorra' as a group absorbed into the Italian-American Mafia, suggesting it is a collective term for various Italian-American criminal groups of non-Sicilian origin.
    #     tag:   all-nodes

    "Arab Tribal and Clan Forces",  # (high) The name refers to a collective of various Arab tribal and clan militias, not a single organization.
    #     tag:   all-nodes

    "Area boys",  # (high) The description refers to 'loosely organized gangs' and a general phenomenon, not a single structured organization.
    #     desc:  "Loosely organized gangs of street children, teenagers, and youths, mostly male, operating in major Nigerian cities. They…"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=Area_boys&oldid=1356299136

    "Armed Forces of Ukraine",  # (high) The Armed Forces of Ukraine is the official military of a sovereign state, not a criminal organization.
    #     tag:   all-nodes

    "Asian street gangs",  # (high) The term 'Asian street gangs' is a general category for various distinct gangs, not a single organization.
    #     tag:   all-nodes

    "Australian syndicates",  # (high) The term 'Australian syndicates' is used as a general label for various criminal groups from Australia, not a specific organization.
    #     tag:   all-nodes

    "Autonomists",  # (high) The passage refers to 'Autonomists' as a group that the 36 Boys joined, but the term is widely used for a political movement, not a specific criminal organization.
    #     tag:   all-nodes

    "Balkans criminal organizations",  # (high) The entry is a mention-only node referring to a broad geographic grouping of various criminal organizations from the Balkans, not a specific group.
    #     tag:   all-nodes

    "Baltimore Irish gangs",  # (high) The passage refers to 'Baltimore Irish gangs' as a rival group, implying it is a collective category for multiple Irish gangs in Baltimore, not a single organization.
    #     tag:   all-nodes

    "Bardellino-Alfieri-Galasso",  # (high) The passage describes 'Bardellino-Alfieri-Galasso' as a confederation of distinct groups, not a single organization.
    #     tag:   all-nodes

    "Bicheiros",  # (medium) The term 'Bicheiros' is mentioned as an ally in a list of groups, but no description is provided, and it likely refers to a category of Brazilian criminal groups involved in illegal gambling (jogo do bicho), not a single organization.
    #     tag:   all-nodes

    "Big Seven",  # (high) The article refers to 'Big Seven' as a group of bootleggers aligned with the Philadelphia faction, not a single organization.
    #     tag:   all-nodes

    "Black Caucus",  # (high) The passage describes 'Black Caucus' as a strategic alliance of several Toxteth-based gangs, not a single organization.
    #     tag:   all-nodes

    "Black Hand gangs",  # (high) The article refers to 'Black Hand gangs' as a general term for Sicilian extortion groups, not a single organization.
    #     tag:   all-nodes

    "Black Muslims",  # (high) The article refers to 'Black Muslims' as a group in a prison context, but it is a religious movement, not a specific criminal organization.
    #     tag:   all-nodes

    "Bloods-affiliated Somalian street gangs",  # (high) The name describes a category of multiple street gangs with Somali ethnicity and Bloods affiliation, not a single organization.
    #     tag:   all-nodes

    "Bosnian mafia",  # (high) The description refers to 'illegal gangs and criminal organizations' collectively, not a single structured group.
    #     desc:  "The Bosnian mafia comprises illegal gangs and criminal organizations operating in Bosnia and Herzegovina and its diaspor…"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=Organised_crime_in_Bosnia_and_Herzegovina&oldid=1357635785

    "Boxers",  # (high) The article refers to the Boxers as a broad movement or rebellion, not a single criminal organization.
    #     tag:   all-nodes

    "Bwa kale vigilantes",  # (high) The term 'Bwa kale vigilantes' refers to a collective of vigilante groups in Haiti, not a single organization.
    #     tag:   all-nodes

    "Bōsōzoku",  # (high) Bōsōzoku is a Japanese youth subculture and general term for biker gangs, not a single organization with unified leadership.
    #     desc:  "Japanese youth subculture and biker gangs known for customized motorcycles and distinctive uniforms. Originated in the 1…"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=B%C5%8Ds%C5%8Dzoku&oldid=1358527484

    "Camorra barese",  # (high) The description defines it as an 'informal name' and a 'confederation of clans' listing multiple distinct groups, not a single organization.
    #     desc:  "The Camorra barese is the informal name for organized crime operating in Bari and its province, distinct from the Neapol…"
    #     tag:   all-nodes
    #     own:   https://it.wikipedia.org/w/index.php?title=Camorra_barese&oldid=150934009

    "Canadian Mafia",  # (high) The entry is a mention-only node with no description, and the passage groups it with other 'mafia' terms as allies, suggesting it is a general label for organized crime in Canada rather than a specific group.
    #     tag:   all-nodes

    "Cape Verdean mafia",  # (high) The term 'Cape Verdean mafia' is used as a general label for various criminal groups from Cape Verde, not a specific organization.
    #     tag:   all-nodes

    "Carteles mexicanos",  # (high) The term 'Carteles mexicanos' is a general label for various Mexican drug cartels, not a single organization.
    #     tag:   all-nodes

    "Cartello colombiano",  # (high) The term 'cartello colombiano' is used generically to refer to Colombian drug cartels, not a specific organization.
    #     tag:   all-nodes

    "Cartéis colombianos",  # (high) The term 'Cartéis colombianos' is a Portuguese phrase meaning 'Colombian cartels', used as a general label for multiple distinct Colombian drug cartels, not a single organization.
    #     tag:   all-nodes

    "Caucasian Front",  # (high) The term 'Caucasian Front' appears in a list of militant groups and likely refers to a coalition or umbrella of insurgent factions in the Caucasus region, not a single organization.
    #     tag:   all-nodes

    "CENTRAL",  # (high) The passage refers to 'Central' as a neighborhood in Winnipeg, not a criminal organization.
    #     tag:   all-nodes

    "Chaozhou syndicates",  # (high) The passage refers to 'small syndicates of ethnic Chaozhou' as multiple groups, not a single organization.
    #     tag:   all-nodes

    "Chinese mafia",  # (high) The article lists 'Chinese mafia' as a general term for various criminal organizations, not a specific group.
    #     tag:   all-nodes

    "Chinese Tongs",  # (high) The term 'Chinese Tongs' refers to a category of Chinese secret societies or fraternal organizations, not a single criminal group.
    #     tag:   all-nodes

    "Chinese Triad",  # (high) The term 'Chinese Triad' refers to a category of various Chinese organized crime groups, not a single organization.
    #     tag:   all-nodes

    "Chiu Chow Group",  # (high) The passage describes the Chiu Chow Group as one of four main groups of triads, including Sun Yee On, indicating it is a collective category for multiple distinct triad societies.
    #     tag:   all-nodes

    "Chuen Group",  # (high) The article lists 'Chuen Group' as a category containing multiple subgroups (Chuen Chi Wo, Chuen Yat Chi), indicating it is an umbrella term for related triads.
    #     tag:   all-nodes

    "Clan del Crotonese",  # (medium) The passage refers to 'clan del Crotonese' as a collective of clans from the Crotonese area, not a single organization.
    #     tag:   all-nodes

    "Clan Giostrai",  # (high) The passage describes 'Clan Giostrai' as 'various affiliated groups of nomad criminals', indicating it is a collective category rather than a single organization.
    #     tag:   all-nodes

    "Colectivos",  # (high) The passage refers to 'Colectivos paramilitaries' as a general category of pro-government armed groups in Venezuela, not a single organization.
    #     tag:   all-nodes

    "Colombian crime cartel",  # (high) The term 'Colombian crime cartel' is a generic label for various Colombian drug trafficking organizations, not a specific group.
    #     tag:   all-nodes

    "Compton Crips",  # (high) The passage refers to 'Most Compton Crips' as rivals, indicating it is a collective term for multiple Crip sets in Compton, not a single organization.
    #     tag:   all-nodes

    "Confederation of Mountain Peoples of the Caucasus",  # (high) The name and context indicate it is a confederation of various groups, not a single criminal organization.
    #     tag:   all-nodes

    "Coordinadora Guerrillera Simón Bolívar",  # (high) The article describes it as a coalition of multiple distinct guerrilla groups including FARC-EP, UC-ELN, M-19, Quintín Lame, and PRT.
    #     tag:   all-nodes

    "Corsican gangs",  # (high) The article refers to 'Corsican gangs' as a general category of criminal groups from Corsica, not a single organization.
    #     tag:   all-nodes

    "Cosche dell'area catanzarese",  # (high) The phrase 'cosche dell'area catanzarese' translates to 'clans of the Catanzaro area', referring to multiple distinct mafia groups in that region, not a single organization.
    #     tag:   all-nodes

    "Criminalità pugliese",  # (high) The term 'criminalità pugliese' refers to organized crime in the Apulia region of Italy, not a single specific group.
    #     tag:   all-nodes

    "Criminalità salentina",  # (high) The term 'criminalità salentina' refers to organized crime in the Salento area of Puglia, Italy, not a specific group.
    #     tag:   all-nodes

    "Criminalità sarda",  # (high) The term 'Criminalità sarda' refers to organized crime in Sardinia as a general phenomenon, not a specific group.
    #     tag:   all-nodes

    "Cần Vương resistance movement",  # (high) The passage describes it as a resistance movement that provided cover for banditry, not a single criminal organization.
    #     tag:   all-nodes

    "Dacoits",  # (high) The article refers to 'Dacoits' as a criminal category alongside Thugs, not a specific organization.
    #     tag:   all-nodes

    "Democratic Autonomous Administration of North and East Syria",  # (high) It is a political administration and military coalition, not a single criminal organization.
    #     tag:   all-nodes

    "Detroit Federation of Motorcycle Clubs",  # (high) The description indicates it is a federation created to resolve turf wars among motorcycle gangs, implying it is a collective of multiple clubs rather than a single organization.
    #     tag:   all-nodes

    "Diehard Duterte Supporters",  # (high) The name refers to a political support base, not a structured criminal organization.
    #     tag:   all-nodes

    "Dominican criminal groups",  # (high) The phrase 'Dominican criminal groups' is a general label for various unrelated criminal organizations from the Dominican Republic, not a specific group.
    #     tag:   all-nodes

    "Dubai mafia",  # (high) The passage refers to 'Dubai mafia' as an ally of a specific group, suggesting it is a general label for organized crime in Dubai rather than a single organization.
    #     tag:   all-nodes

    "Dutch Antillean criminal organizations",  # (high) The phrase refers to multiple distinct criminal groups from the Dutch Antilles, not a single organization.
    #     tag:   all-nodes

    "Dutch organized crime",  # (high) The entry is a mention-only node referring to organized crime in the Netherlands, not a specific criminal organization.
    #     tag:   all-nodes

    "Eight-Nation Alliance",  # (high) The Eight-Nation Alliance was a military coalition of eight countries, not a criminal organization.
    #     tag:   all-nodes

    "Esquadrão da Morte",  # (high) The article describes 'Esquadrão da Morte' as a term used for various death squads in different countries and time periods, not a single organization.
    #     tag:   all-nodes

    "Estonian organized crime",  # (high) The article describes 'Estonian organized crime' as a general phenomenon, not a specific group, and refers to it alongside 'Russian mafia' as part of an umbrella organization.
    #     tag:   all-nodes

    "Euphrates Volcano",  # (high) The article describes Euphrates Volcano as a joint operations room of multiple Syrian rebel factions, not a single organization.
    #     tag:   all-nodes

    "European National Front",  # (high) The passage explicitly describes it as 'an umbrella group of far-right nationalist organizations'.
    #     tag:   all-nodes

    "Fasci Siciliani",  # (high) The Fasci Siciliani were a popular movement of peasants and workers, not a single criminal organization.
    #     tag:   all-nodes

    "Fatah Alliance",  # (high) The Fatah Alliance is a political coalition representing the Popular Mobilization Forces, not a single criminal organization.
    #     tag:   all-nodes

    "Federation of Turkish Democratic Idealist Associations in Germany",  # (high) The description explicitly states it is an umbrella association grouping around 200 local clubs, not a single criminal organization.
    #     tag:   all-nodes

    "Freikorps",  # (high) The article describes Freikorps as militias recruited from WWI veterans, not a single criminal organization.
    #     tag:   all-nodes

    "French Milieu",  # (high) The term 'French Milieu' is a general label for organized crime in France, not a specific group.
    #     tag:   all-nodes

    "Gerace",  # (high) The passage refers to 'distretto di Gerace' as a geographic area where criminal activities occur, not a specific organization.
    #     tag:   all-nodes

    "Giugliano",  # (high) Giugliano is a geographic area, not a specific criminal organization; the passage refers to clans operating in that area.
    #     tag:   all-nodes

    "Gran Familia Mexicana",  # (high) Described as a federation of Mexican gangs, not a single organization.
    #     tag:   all-nodes

    "Herriko Tabernak",  # (high) The article describes Herriko Tabernak as a network of meeting centres, not a single criminal organization.
    #     tag:   all-nodes

    "Hong Kong mafia",  # (high) The term 'Hong Kong mafia' is a generic label for organized crime in Hong Kong, not a specific group.
    #     tag:   all-nodes

    "Hong Kong Triads",  # (high) The passage refers to 'Hong Kong triads' as a category alongside other general terms like 'Chinese triads' and 'Japanese yakuza', indicating it is a collective label for multiple groups.
    #     tag:   all-nodes

    "Hoover factions",  # (high) The term 'Hoover factions' is used as a collective label for multiple distinct Crip subsets, not a single organization.
    #     tag:   all-nodes

    "Hunan Gang",  # (medium) The name 'Hunan Gang' appears in a list of triad groups, but without description it likely refers to a collective of gangs from Hunan rather than a single organization.
    #     tag:   all-nodes

    "Igbo drug sellers",  # (high) The term refers to a collective of drug sellers from the Igbo ethnic group, not a single organization.
    #     tag:   all-nodes

    "Indonesian Mujahedeen Council",  # (high) The description states it was created to connect Islamist groups, indicating it is a collective umbrella organization.
    #     tag:   all-nodes

    "International Communist League",  # (high) The International Communist League is a political international, not a single criminal organization.
    #     tag:   all-nodes

    "Iranian mafia",  # (high) The term 'Iranian mafia' is used as a general label for various criminal organizations of Iranian origin, not a specific group.
    #     tag:   all-nodes

    "Irish Alliance",  # (medium) The passage refers to 'the biker clubs of Irish Alliance', suggesting it is a collective of multiple clubs rather than a single organization.
    #     tag:   all-nodes

    "Iron Order",  # (high) The passage describes Iron Order as 'a coalition of accelerationist groups', indicating it is an umbrella term for multiple distinct organizations.
    #     tag:   all-nodes

    "Islami Jamhoori Ittehad",  # (high) Islami Jamhoori Ittehad is a political alliance, not a criminal organization.
    #     tag:   all-nodes

    "Italian crime groups",  # (high) The name 'Italian crime groups' is a generic category referring to multiple distinct organizations, not a single entity.
    #     tag:   all-nodes

    "Italian gangsters",  # (high) The term 'Italian gangsters' is a general label for various Italian criminal groups, not a specific organization.
    #     tag:   all-nodes

    "Italian organized crime",  # (high) The entry 'Italian organized crime' is a general term for various criminal groups in Italy, not a specific organization.
    #     tag:   all-nodes

    "Italian-Canadian mafia families",  # (high) The term refers to multiple distinct Italian-Canadian mafia families collectively, not a single organization.
    #     tag:   all-nodes

    "Jaish Al-Fatah",  # (high) The article describes it as a joint command center formed by multiple Syrian Islamist groups, not a single organization.
    #     tag:   all-nodes

    "Jarrai-Haika-Segi",  # (high) The article describes Jarrai-Haika-Segi as a 'youths' movement' accused of contributing to street violence, not a single structured criminal organization.
    #     tag:   all-nodes

    "Jewish-American mob",  # (high) The term 'Jewish-American mob' is a general label for various Jewish-American organized crime groups, not a single organization.
    #     tag:   all-nodes

    "Johannesburg bouncer mafia",  # (medium) The name suggests a collective term for bouncers involved in organized crime in Johannesburg, not a specific group.
    #     tag:   all-nodes

    "Jund al Malahim",  # (high) The article describes Jund al Malahim as an 'operations room' created as an alliance of multiple distinct groups, not a single organization.
    #     tag:   all-nodes

    "Kansai Hatsuka-kai",  # (high) The passage describes it as an 'anti-Yamaguchi federation', indicating it is a coalition of multiple yakuza groups, not a single organization.
    #     tag:   all-nodes

    "Khmer Issarak",  # (high) The article describes 'Khmer Issarak' as multiple armed left-wing bands, not a single organization.
    #     tag:   all-nodes

    "Kyiv Clan",  # (high) The article describes the Kyiv Clan as an 'oligarch group', a loose collective of oligarchs from Kyiv, not a single structured criminal organization.
    #     tag:   all-nodes

    "Latin American drug cartels",  # (high) The term 'Latin American drug cartels' is a collective category referring to multiple distinct drug trafficking organizations from Latin America, not a single group.
    #     tag:   all-nodes

    "Libyan Arab Jamahiriya",  # (high) The entry refers to the Libyan government under Gaddafi, not a criminal organization.
    #     tag:   all-nodes

    "Libyan Army",  # (high) The term 'Libyan Army' refers to the national military of Libya, not a specific criminal organization.
    #     tag:   all-nodes

    "Local Defense Forces",  # (high) The article mentions 'Local Defense Forces' as one of several state-backed groups in Syria, suggesting it is a collective category rather than a single organization.
    #     tag:   all-nodes

    "London Bloods",  # (high) The passage refers to 'London Bloods' as a collective name used by various splinter groups, not a single organization.
    #     tag:   all-nodes

    "Los Cascos",  # (high) The passage describes 'Los Cascos' as a term for Chapitos-affiliated elements, not a specific organization.
    #     tag:   all-nodes

    "Luen Group",  # (high) The passage lists 'Luen Group' as one of four main groups of triads, alongside other collective categories like 'Chiu Chow Group' and 'Wo Group', indicating it is a grouping of multiple distinct triad societies.
    #     tag:   all-nodes

    "Macedonian mafia",  # (high) The entry is listed alongside other national mafias as an ally, suggesting it is a general label for organized crime from Macedonia rather than a specific group.
    #     tag:   all-nodes

    "Mafia China",  # (high) The term 'Mafia China' is used as a generic label for Chinese organized crime groups, not a specific organization.
    #     tag:   all-nodes

    "Mafia Garganica",  # (medium) The passage refers to 'Mafia Garganica' as a collective of criminal groups from specific towns, not a single organization.
    #     tag:   all-nodes

    "Mafia serbia",  # (high) The article describes 'Mafia serbia' as a general term for Serbian organized crime, not a specific group.
    #     tag:   all-nodes

    "Mafía Coreana",  # (high) The term 'Mafía Coreana' is used as a general label for Korean criminal organizations, not a specific group.
    #     tag:   all-nodes

    "Maghrebian gangs",  # (high) The term 'Maghrebian gangs' is used as a general label for various criminal groups of North African origin, not a single organization.
    #     tag:   all-nodes

    "Mai-Mai",  # (high) The article describes Mai-Mai as an umbrella term for any community-based militia group in the DRC, not a single organization.
    #     tag:   all-nodes

    "Mandamento of Alcamo",  # (high) A mandamento is a district or grouping of Mafia families, not a single organization.
    #     tag:   all-nodes

    "March 14 Alliance",  # (high) The March 14 Alliance is a political coalition in Lebanon, not a criminal organization.
    #     tag:   all-nodes

    "Mare' Operations Room",  # (high) The name 'Mare' Operations Room' appears in a list of groups, and 'Operations Room' typically denotes a coordination body or coalition of multiple factions, not a single organization.
    #     tag:   all-nodes

    "Megpunna Thugs",  # (high) Described as a 'loose association of thieves' including itinerant groups like Banjara and Naik, indicating a collective category rather than a single organization.
    #     tag:   all-nodes

    "Militias",  # (high) The entry 'Militias' is listed among rivals and opponents without a specific description, and in context it likely refers to a general category of militia groups rather than a single organization.
    #     tag:   all-nodes

    "Moss Side Gangs",  # (high) The passage refers to 'Moss Side gangs' as a plural category of multiple distinct groups, not a single organization.
    #     tag:   all-nodes

    "Motorcycle gang",  # (high) The term 'motorcycle gang' is a general category for various outlaw motorcycle clubs, not a specific organization.
    #     tag:   all-nodes

    "Motorcycle Gangs",  # (high) The term 'Motorcycle Gangs' is a general category for various outlaw motorcycle clubs, not a single organization.
    #     tag:   all-nodes

    "National Defence Forces",  # (high) The term 'National Defence Forces' appears in a list of opponents alongside other groups, but it is a generic name used by multiple militias in different countries, not a single organization.
    #     tag:   all-nodes

    "National Democracy",  # (high) The article mentions 'National Democracy' as a member of a political party alliance, not as a specific criminal organization.
    #     tag:   all-nodes

    "National Liberation Front of Kurdistan",  # (high) The article describes ERNK as a popular front wing and umbrella organization for PKK organizations in different segments of the Kurdish population.
    #     tag:   all-nodes

    "NATO",  # (high) NATO is an international military alliance, not a criminal organization.
    #     tag:   all-nodes

    "Nazis",  # (high) The term 'Nazis' in this context refers to a broad category of individuals with far-right ideology, not a specific criminal organization.
    #     tag:   all-nodes

    "Neo-integralist groups",  # (high) The name 'Neo-integralist groups' is a plural collective term for various groups, not a single organization.
    #     tag:   all-nodes

    "New York Mafia",  # (high) The term 'New York Mafia' is used as a general reference to organized crime in New York, not a specific group.
    #     tag:   all-nodes

    "New York mafia families",  # (high) The term refers to multiple distinct Mafia families in New York, not a single organization.
    #     tag:   all-nodes

    "Nishinippon Hatsuka-kai",  # (high) The article describes it as an anti-Yamaguchi federation formed by multiple organizations, not a single group.
    #     tag:   all-nodes

    "Organised Crime",  # (high) The term 'Organised Crime' is a generic label for a category of criminal activity, not a specific group.
    #     tag:   all-nodes

    "Outlaw motorcycle gangs",  # (high) The article describes 'outlaw motorcycle gangs' as a category encompassing multiple distinct clubs like Bandidos, Hells Angels, and Gypsy Jokers, not a single organization.
    #     tag:   all-nodes

    "Paisas",  # (high) The passage describes 'Paisas' as a nickname used for paramilitaries from the Antioquia region, not a specific organization.
    #     tag:   all-nodes

    "Palermo Mafia families",  # (high) The term refers to multiple distinct Mafia families in Palermo, not a single organization.
    #     tag:   all-nodes

    "Palestinian Joint Operations Room",  # (high) The Palestinian Joint Operations Room is a coordination framework for multiple Palestinian militant groups, not a single organization.
    #     tag:   all-nodes

    "Peckerwoods",  # (high) The term 'Peckerwoods' is a general label for various white supremacist prison and street gangs, not a single structured organization.
    #     tag:   all-nodes

    "Pindaris",  # (high) The passage refers to Pindaris as a group whose livelihoods were disrupted, suggesting they are a historical community or category, not a single criminal organization.
    #     tag:   all-nodes

    "Pink Panthers",  # (high) The article explicitly states 'The Pink Panthers is an umbrella term for all high profile jewelry heist specialists from Balkans region' and notes there is not sufficient integration to consider it a criminal group.
    #     tag:   all-nodes

    "Police Death squad",  # (high) The term 'Police Death squad' is a generic label for rogue police units, not a specific organization.
    #     tag:   all-nodes

    "Post-Soviet Organized crime groups",  # (high) The term refers to various criminal groups from post-Soviet states, not a single organization.
    #     tag:   all-nodes

    "Punjabi Taliban",  # (high) The term 'Punjabi Taliban' is used as a collective label for various militant groups from Punjab, not a single organization.
    #     tag:   all-nodes

    "Puntland",  # (high) Puntland is a regional state in Somalia, not a criminal organization.
    #     tag:   all-nodes

    "Qatar",  # (high) Qatar is a country, not a criminal organization; the article discusses state sponsorship of Hezbollah.
    #     tag:   all-nodes

    "Quebec Mafia",  # (high) The passage refers to 'the Quebec Mafia' as a general term for organized crime in Quebec, not a specific group.
    #     tag:   all-nodes

    "Raskol gangs",  # (high) The description refers to 'Raskol gangs' as a general category of criminal groups in Papua New Guinea, not a single organization with unified leadership.
    #     desc:  "Raskol gangs are criminal groups in Papua New Guinea, primarily in urban areas like Port Moresby and Lae. They emerged i…"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=Raskol_gangs&oldid=1359062824

    "Ring Berlin",  # (high) The article describes 'Ring Berlin' as a holding organization for several clubs, not a single criminal group.
    #     tag:   all-nodes

    "Russian Armed Forces",  # (high) The Russian Armed Forces are the official military of Russia, not a criminal organization.
    #     tag:   all-nodes

    "Russian Bratva",  # (high) The term 'Russian Bratva' is used as a general label for various Russian organized crime groups, not a single specific organization.
    #     tag:   all-nodes

    "Russian crime groups",  # (high) The term 'Russian crime groups' is a general label for various criminal organizations from Russia, not a single entity.
    #     tag:   all-nodes

    "Russian separatist forces in Donbas",  # (high) The term refers to various separatist groups in the Donbas region, not a single organization.
    #     tag:   all-nodes

    "Salford Gang",  # (medium) The passage refers to 'Salford gangs' as a collective, not a single organization.
    #     tag:   all-nodes

    "Scorpions",  # (high) The name 'Scorpions' refers to at least two distinct groups: a Serbian paramilitary unit and a Hells Angels puppet gang, indicating it is a reused label rather than a single organization.
    #     tag:   all-nodes

    "Serbian paramilitaries in Kosovo",  # (high) The entry refers to a collective category of various Serbian paramilitary groups operating in Kosovo, not a single organization.
    #     tag:   all-nodes

    "Shing Group",  # (high) The entry appears in a list of triad groups, but 'Shing Group' is a generic category name for multiple triads sharing 'Shing' in their names, not a specific organization.
    #     tag:   all-nodes

    "Skinheads",  # (high) The term 'Skinheads' refers to a subculture and is used as a general label for various groups, not a single criminal organization.
    #     tag:   all-nodes

    "Southside",  # (high) The article describes Southside as a geographic area in Belize City with multiple gangs, not a single organization.
    #     tag:   all-nodes

    "Surinamese cartels",  # (high) The term 'Surinamese cartels' is used as a general label for multiple criminal groups from Suriname, not a single organization.
    #     tag:   all-nodes

    "Syrian Army",  # (high) The Syrian Army is the official military of Syria, not a criminal organization, and the passage refers to the Free Syrian Army as a faction, not a single criminal group.
    #     tag:   all-nodes

    "Syrian Ba'athist regime",  # (high) The Syrian Ba'athist regime is a political regime, not a specific criminal organization.
    #     tag:   all-nodes

    "Syrian Turkmen Brigades",  # (high) The term refers to a collective of various Syrian Turkmen rebel groups, not a single organization.
    #     tag:   all-nodes

    "Sze Tai",  # (high) The passage describes Sze Tai as one of four main groups of triads, listing multiple sub-groups (Luen Group, Tan Yee, Macau Chai, Tung Group) under it, indicating it is a collective category.
    #     tag:   all-nodes

    "Taiping Rebellion",  # (high) The Taiping Rebellion was a large-scale civil war and political movement, not a single criminal organization.
    #     tag:   all-nodes

    "Telingana Thugs",  # (high) The article describes 'Telingana Thugs' as a group from the Telangana region, but it is a category of thugs based on geographic origin, not a single organization with unified leadership.
    #     tag:   all-nodes

    "Terrorgram Collective",  # (high) The description refers to 'Terrorgram Collective' as a network or collective of individuals, not a single structured organization.
    #     tag:   all-nodes

    "The Com",  # (high) The article describes 'The Com' as a larger global hacking community, not a single organization.
    #     tag:   all-nodes

    "The Golden Triangle Alliance",  # (high) The description states it was an alliance of drug lords and gangs from three states, not a single organization.
    #     tag:   all-nodes

    "Tokuryū",  # (high) The description defines Tokuryū as a term for loosely organized criminal groups, not a single organization.
    #     desc:  "Tokuryū is a term coined by Japan's National Police Agency for loosely organized criminal groups that have emerged as an…"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=Tokury%C5%AB&oldid=1355311021

    "Triadas",  # (high) The article describes 'Triadas' as a general term for various Chinese criminal organizations, not a single group.
    #     tag:   all-nodes

    "Triads of Vancouver",  # (high) The term 'Triads of Vancouver' is used as a collective label for various Triad groups operating in Vancouver, not a single organization.
    #     tag:   all-nodes

    "Turkish criminal organizations",  # (high) The phrase 'Turkish criminal organizations' is a general label for various distinct groups, not a single organization.
    #     tag:   all-nodes

    "Turkish organized crime",  # (high) The passage refers to 'Turkish organized crime' as a general category alongside specific groups, not a single organization.
    #     tag:   all-nodes

    "Unified Military Command of Eastern Ghouta",  # (high) The name 'Unified Military Command of Eastern Ghouta' suggests a coalition or command structure uniting multiple groups, not a single organization.
    #     tag:   all-nodes

    "Union des organisations islamiques en France",  # (high) The description identifies it as an umbrella organization with 200 member organizations, not a single criminal group.
    #     tag:   all-nodes

    "United Freedom Forces",  # (high) The passage lists 'United Freedom Forces' among a coalition of groups, suggesting it is a collective or umbrella term rather than a single organization.
    #     tag:   all-nodes

    "United Jihad Council",  # (high) The passage lists it as 'Part of' for multiple distinct militant groups, indicating it is an umbrella coalition.
    #     tag:   all-nodes

    "United Motorcycle Council of NSW",  # (high) The United Motorcycle Council of NSW is a coalition of multiple outlaw motorcycle clubs, not a single criminal organization.
    #     tag:   all-nodes

    "United Nicaraguan Opposition",  # (high) The article describes UNO as a reorganization of multiple Contra groups, not a single criminal organization.
    #     tag:   all-nodes

    "Vietnam",  # (high) The entry refers to a country, not a criminal organization.
    #     tag:   all-nodes

    "Vietnamese crime groups",  # (high) The term 'Vietnamese crime groups' is a general label for various criminal organizations of Vietnamese origin, not a single specific group.
    #     tag:   all-nodes

    "Waray-Waray gangs",  # (high) The description explicitly calls it a 'generic term for criminal groups of Waray ethnicity', indicating it is a collective category, not a single organization.
    #     desc:  "Generic term for criminal groups of Waray ethnicity in the Philippines, originating from Leyte and Samar. They engage in…"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=Waray-Waray_gangs&oldid=1359582277

    "Western Sydney gangs",  # (high) The term refers to multiple distinct gangs in the Western Sydney area, not a single organization.
    #     tag:   all-nodes

    "White Lotus",  # (high) The passage describes White Lotus as a historical secret society from the 14th century that influenced triads, not a specific criminal organization.
    #     tag:   all-nodes

    "White Lotus Society",  # (high) The White Lotus Society is described as a historical secretive folk religious sect and ancestral organization, not a single criminal group.
    #     tag:   all-nodes

    "White power Skinheads",  # (high) The term 'White power Skinheads' is a general label for various white supremacist skinhead groups, not a single organization.
    #     tag:   all-nodes

    "Yadav caste gangs",  # (high) The name refers to gangs associated with the Yadav caste, which is a broad social group, not a specific organization.
    #     tag:   all-nodes

    "Yardie gangs",  # (high) The term 'Yardie gangs' is a colloquial label for various Jamaican criminal groups, not a single organization.
    #     tag:   all-nodes

    "Yardies",  # (high) The article refers to 'Yardies' as a general term for Jamaican criminal groups, not a single organization.
    #     tag:   all-nodes

    "Yugoslavian Crime Syndicate",  # (high) The term 'Yugoslavian crime syndicate' is used generically in the passage to refer to organized crime from the Yugoslav region, not a specific group.
    #     tag:   all-nodes

    "'Ndrina",  # (high) The term 'ndrina refers to a single family unit within the 'Ndrangheta, not a specific organization, but the entry is a mention-only node with no description, and the passage describes it as a component of the larger 'Ndrangheta, making it a category rather than a distinct group.
    #     tag:   all-nodes

    "Al-Islah (Somalia)",  # (high) Al-Islah is a political party in Yemen, not a criminal organization, and the mention in Somalia is likely a misattribution or umbrella term.
    #     tag:   all-nodes

    "Albanian mafia groups",  # (high) The phrase 'Albanian mafia groups' is a general label for various distinct criminal organizations from Albania, not a single entity.
    #     tag:   all-nodes

    "Balkan cartel",  # (high) The article describes 'Balkan cartel' as a term for a network of multiple organized crime groups, not a single organization.
    #     tag:   all-nodes

    "Bari crime groups",  # (high) The article refers to 'Bari crime groups' as a collective category alongside other regional organized crime syndicates, not as a single specific organization.
    #     tag:   all-nodes

    "Black Power",  # (high) The passages refer to 'Black Power' as a New Zealand gang, but the name is also a general term for a political movement, and the article treats it as a specific gang in context.
    #     tag:   all-nodes

    "Calabrian mafia",  # (high) The term 'Calabrian mafia' is a general label for organized crime groups from Calabria, not a specific organization.
    #     tag:   all-nodes

    "Colombian Drug Trafficking Groups",  # (high) The article uses 'Colombian drug trafficking groups' as a general category alongside other national/ethnic groupings, not as a specific organization.
    #     tag:   all-nodes

    "Cuban Mafia",  # (high) The article uses 'Cuban mafia' as a general term for Cuban criminal groups, not a specific organization.
    #     tag:   all-nodes

    "Cults in Nigeria",  # (high) The entry is listed alongside other umbrella terms like 'Mafia mexicana' and 'Triadas de China', and 'Cults in Nigeria' refers to a general phenomenon of cult-like criminal groups in Nigeria, not a specific organization.
    #     tag:   all-nodes

    "Einsatzgruppen",  # (high) Einsatzgruppen were mobile killing squads of Nazi Germany, not a single criminal organization but a collective term for multiple units.
    #     tag:   all-nodes

    "EPL dissidents",  # (high) The term 'EPL dissidents' refers to various splinter groups from the EPL, not a single organization.
    #     tag:   all-nodes

    "Estonian Mafia",  # (high) The article describes 'Estonian mafia' as a national label for various groups, not a single organization.
    #     tag:   all-nodes

    "Federal Political Negotiation and Consultative Committee",  # (high) The FPNCC is a coalition of multiple ethnic armed organizations formed for peace talks, not a single criminal organization.
    #     tag:   all-nodes

    "Gargano group",  # (high) The passage describes 'a group active around Gargano' as a mafia subgroup, but the entry is a mention-only node with no specific structure or leadership, and the article treats it as a geographic grouping.
    #     tag:   all-nodes

    "Glasgow razor gangs",  # (high) The description refers to multiple violent gangs in Glasgow, not a single organization.
    #     desc:  "Violent gangs in Glasgow, Scotland during the late 1920s and 1930s, named for their use of razors. They operated primari…"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=Glasgow_razor_gangs&oldid=1314490337

    "Grand Alliance",  # (high) The article lists 'Grand Alliance' among various militias and guerrilla groups in the Niger Delta, suggesting it is a collective term for a coalition rather than a single organization.
    #     tag:   all-nodes

    "Grupos de Autodefensa Popular y Comunitaria",  # (high) The passage describes them as civilian self-defense groups formed against drug cartels, indicating a collective category rather than a single organization.
    #     tag:   all-nodes

    "Indian Thuggee",  # (high) The article refers to 'Indian thuggee' as a historical phenomenon or category of organized crime, not a specific group.
    #     tag:   all-nodes

    "Indonesian Preman",  # (high) The passage refers to 'Indonesian preman' as a type of organized crime group alongside other general categories like 'Chinese triads' and 'Japanese yakuza', indicating it is a collective term for various groups in Indonesia.
    #     tag:   all-nodes

    "Japanese yakuza",  # (high) The term 'yakuza' refers to various Japanese organized crime groups, not a single organization.
    #     tag:   all-nodes

    "Kkangpae",  # (high) The description defines 'Kkangpae' as a general Korean term for gangsters or thugs, not a specific organization.
    #     desc:  "Kkangpae is a Korean term for gangsters or thugs, often referring to unorganized street gangs, while organized crime gro…"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=Kkangpae&oldid=1355368508

    "Korean Criminal Groups",  # (high) The passage lists 'Korean criminal groups' alongside other broad categories like 'ethnic Chinese criminal groups' and 'Nigerian organized crime groups', indicating it is a collective term for multiple distinct organizations.
    #     tag:   all-nodes

    "Kuki-Chin militants",  # (high) The term 'Kuki-Chin militants' refers to various armed groups from the Kuki and Chin ethnic communities, not a single organization.
    #     tag:   all-nodes

    "Luen Kwan Ying",  # (high) Listed as a subgroup under 'Sze Tai' and 'Luen Group', suggesting it is a collective category rather than a single organization.
    #     tag:   all-nodes

    "Mafia",  # (high) The term 'Mafia' is used generically in the passages to refer to various organized crime groups, not a single organization.
    #     tag:   all-nodes

    "Mafia nigeriana",  # (high) The article uses 'mafia nigeriana' as a general term for various Nigerian criminal organizations operating in Italy, not a single specific group.
    #     tag:   all-nodes

    "Mano nera",  # (high) The article describes 'Mano nera' as a term for various extortion gangs within Italian communities, not a single organization.
    #     tag:   all-nodes

    "Maravilla gangs",  # (high) The passage refers to 'Maravilla gangs' as a group of gangs in East Los Angeles, not a single organization.
    #     tag:   all-nodes

    "National Revolutionary Front",  # (high) The passage describes it as 'consisting mainly of anti-government gangs and former soldiers', indicating it is a coalition of multiple groups, not a single organization.
    #     tag:   all-nodes

    "Nigerian organized crime",  # (high) The article describes 'Nigerian organized crime' as a general phenomenon, not a specific group.
    #     tag:   all-nodes

    "Nigerian Organized Crime Groups",  # (high) The passage refers to 'Nigerian organized crime groups' as a category alongside other national/ethnic groupings, not a single organization.
    #     tag:   all-nodes

    "Novi Beograd gangs",  # (high) The description refers to 'organized in different Blokovi (neighbourhoods)' and 'smaller groups', indicating a collective category for multiple gangs from the Novi Beograd area.
    #     tag:   all-nodes

    "Pashtun Mafia",  # (high) The passage lists 'Pashtun mafia' alongside other ethnic mafias and explicitly states these are not homogeneous organizations under a single leadership, indicating it is a general label for various groups.
    #     tag:   all-nodes

    "Pink Panthers (organized crime group)",  # (high) The description explicitly states it is a name given to an international jewel thief network by Interpol, implying it is a label for a network of unrelated groups rather than a single organization.
    #     tag:   all-nodes

    "Razor gang",  # (high) The description refers to multiple criminal gangs in Sydney, not a single organization.
    #     desc:  "Criminal gangs that dominated Sydney's crime scene in the 1920s, known for using razors as weapons after handguns were c…"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=Razor_gang&oldid=1276370120

    "Russian organized crime",  # (high) The term 'Russian organized crime' is a general label for various criminal groups of Russian origin, not a single organization.
    #     tag:   all-nodes

    "Syria",  # (high) The entry refers to the country Syria, not a criminal organization.
    #     tag:   all-nodes

    "Tarantino",  # (high) The passage uses 'tarantino' as a geographic reference to the Taranto area, not as a criminal organization.
    #     tag:   all-nodes

    "Teen gangs in Bangladesh",  # (high) The description refers to a general phenomenon of youth gangs in Bangladesh, not a specific organization with a single structure or leadership.
    #     desc:  "Organized youth gangs in Bangladesh composed primarily of teenagers involved in criminal activities such as drug traffic…"
    #     tag:   all-nodes
    #     own:   https://en.wikipedia.org/w/index.php?title=Teen_gangs_in_Bangladesh&oldid=1321887338

    "Triad Society",  # (high) The passage lists 'Triad Society' alongside other general terms like 'Russian mafia' and 'Jewish mafia', suggesting it refers to a category of Chinese organized crime groups rather than a specific organization.
    #     tag:   all-nodes

    "Triadi cinesi",  # (high) The article refers to 'Triadi cinesi' as a general term for Chinese criminal organizations, not a specific group.
    #     tag:   all-nodes

    "Triads",  # (high) The article describes Triads as a general term for various Chinese criminal organizations, not a single structured group.
    #     tag:   all-nodes

    "White Brotherhood",  # (high) The name refers to at least two distinct groups (a Ukrainian drug trafficking ring and a US white supremacist group), indicating it is a reused label rather than a single organization.
    #     tag:   all-nodes

    "Wo Kwan Lok",  # (high) Listed as a subgroup under the Wo Group, which is a collective of triad branches, not a single organization.
    #     tag:   all-nodes

    "Wo Li Wo",  # (high) Wo Li Wo is listed as a subgroup under the Wo Group, which is a collective category of triad clans, not a single organization.
    #     tag:   all-nodes

    "Wo Yee Ping",  # (high) Wo Yee Ping is listed as a subgroup under the Wo Group, which is a collective category of triads, not a single organization.
    #     tag:   all-nodes

    "Yazidis clan",  # (medium) The name 'Yazidis clan' likely refers to a collective of clans or groups associated with the Yazidi ethnic group, not a single criminal organization.
    #     tag:   all-nodes

}
